### ISSUE TITLE
v3.5.10 no longer finds packages in home folder library

### ISSUE THREAD

**Issue by SlowMo24** [rpy2/rpy2#1004]
**Describtion**

My R package-library is located in my `/home` directory. It is correctly recognised when starting R, along with the default locations:

```
> .libPaths()
[1] "/home/userName/R/x86_64-pc-linux-gnu-library/4.2"
[2] "/usr/local/lib/R/site-library"                  
[3] "/usr/lib/R/site-library"                        
[4] "/usr/lib/R/library"   
```

rpy v3.5.9 is also able to access these packages, even though it does not explicitly list that location:

`python -m rpy2.situation`:

```
rpy2 version:
 3.5.9
Python version:
 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
 Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /usr/lib/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
R version:
    In the PATH: R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"
    Loading R library from rpy2: OK
dditional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/share/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'tirpc', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib/R/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-Bsymbolic-functions', '-flto=auto', '-ffat-lto-objects', '-flto=auto', '-Wl,-z,relro']
Directory for the R shared library:
lib
```

but v3.9.10 no longer has access to this directory. Yet, it produces the exact same "situation" output, except for the version number in the second line and this addition at the bottom:

```
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: ABSENT
```

**To Reproduce**

I guess its: Upgrade from v3.5.9 to 3.5.10 and have your library in your home folder but maybe there are some local configs involved.

**Expected behavior**

Find the library in the home folder in 3.5.10 just as standard R and v3.5.9 do.

**Error**

Mainly: `In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :` and ` Library ‘/usr/local/lib/R/site-library’ enthält keine Pakete`

**Comment by lgautier** [comment]
My first thought is that an R configuration file has been added to your setup between your use of rpy2 3.5.9 and 3.5.10, and *that* is the cause of the difference.

Default R's initialization options for rpy2 are have remained unchanged for quite a while now:

```python
import rpy2.rinterface as ri
ri.embedded.get_initoptions()
# here it is ('rpy2', '--quiet', '--no-save')
```

> but v3.9.10 no longer has access to this directory.

What does the following return in Python?

```python
import rpy2.robjects as ro
print(ro.r('.libPaths()')
```


> Yet, it produces the exact same "situation" output, except for the version number in the second line and this addition at the bottom:
>
> ```
> CFFI extension type
>  Environment variable: RPY2_CFFI_MODE
>  Value: CFFI_MODE.ANY
>  ABI: PRESENT
>  API: ABSENT
> ```

This addition indicates whether your are able to run the rpy2-cffi interface to R in ABI or API mode. The API mode is better (some functionalities are only available there). Did you install rpy2 using a non-pypi package repository (e.g., conda) or did you `pip install` ?

**Comment by SlowMo24** [comment]
I'm sorry to have bothered you! I created a minimum example (which I should have done before opening the issue, sorry again) and `libPaths()` does in fact report my personal library and I can load the packages in both versions. so the error is somewhere else in my program and I need to investigate further, but I will close this issue for now.

This warning is though thrown regardless:

```R[write to console]: Warnmeldungen:

R[write to console]: 1: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
 
R[write to console]:  Library ‘/usr/local/lib/R/site-library’ enthält keine Pakete
```

but I guess I can mitigate that by setting a proper library path.

> he API mode is better (some functionalities are only available there). Did you install rpy2 using a non-pypi package repository (e.g., conda) or did you pip install ?

how do I activate the API-mode? I have installed using [poetry](https://python-poetry.org/) which uses `pip`, I think.
