### ISSUE TITLE
rpy2 calls slower than in R, with marginaleffects

### ISSUE THREAD

**Issue by bernardodionisi** [rpy2/rpy2#1007]
Hi

I have been using rpy2 to access the functionality of the R package named [marginaleffects](https://github.com/vincentarelbundock/marginaleffects), in combination with another R package named [fixest](https://github.com/lrberge/fixest). When I call marginaleffects's functions through rpy2, they are significantly slower than when I call them directly in R (through R Studio).

I am using:
- mac x86_64-apple-darwin
- python 3.10
- rpy2 3.5.10
- R 4.2.2
- R fixest 0.11.1
- R marginaleffects 0.11.0

I am not sure why. My guess is that when calling marginaleffects through rpy2, marginaleffects is unable to recognize where the model is coming from (in this case fixest). However, the speed differences using marginaleffects through rpy2 (compared to using it directly in R) are also present when used in combination with other R packages, for example R stats package.

Do you have any suggestions?

Thank you for your assistance! 
And thank you very much for developing and maintaining this incredible package!

## Example code

in the comments below I report the seconds for each call of functions from the marginaleffects package. When I call these functions through rpy2, in the example below, it takes a total 40 seconds while the same functionality in R takes about 0.16 seconds.

### python

```
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import Formula, pandas2ri

from pandas import DataFrame, Categorical
from numpy.random import choice, normal
from time import perf_counter

n = 100000

pd_df = DataFrame({
    'y': normal(size=n),
    'cond': Categorical(choice(list('01'), size=n)),
    'episode': Categorical(choice(list('01234'), size=n)),
})

fixest = importr("fixest")
marginaleffects = importr("marginaleffects")

with (ro.default_converter + pandas2ri.converter).context():
    r_from_pd_df = ro.conversion.get_conversion().py2rpy(pd_df)

model = fixest.feols(Formula('y ~ cond * episode'), data=r_from_pd_df)

# timing marginaleffects's datagrid (through rpy2)

start = perf_counter()

g = marginaleffects.datagrid(model=model, cond=ro.r('0:1'), episode=ro.r('1:3'))

print(f'---> elapsed time  {round(perf_counter() - start, 3)} secs <---')
# ---> elapsed time  28.752 secs <---

# timing marginaleffects's perdictions (through rpy2)

start = perf_counter()

p = marginaleffects.predictions(model=model, newdata=g)

print(f'---> elapsed time  {round(perf_counter() - start, 3)} secs <---')
# ---> elapsed time  12.874 secs <---
```

### R

```
library(marginaleffects)
library(fixest)

n <- 100000

d <- data.frame(
  y = rnorm(n),
  cond = as.factor(sample(0:1, n, TRUE)),
  episode = as.factor(sample(0:4, n, TRUE))
)

model <- fixest::feols(y ~ cond * episode, data = d)

# -------------- timing marginaleffects's datagrid ---------------------

startTime <- Sys.time()

g <- datagrid(model=model, cond = 0:1, episode = 1:3)

endTime <- Sys.time()

print(endTime - startTime)
# Time difference of 0.0740099 secs

# -------------- timing marginaleffects's perdictions -------------------


startTime <- Sys.time()

p <- predictions(model, newdata=g)

endTime <- Sys.time()

print(endTime - startTime)
# Time difference of 0.08031297 secs
```

**Comment by lgautier** [comment]
I don't have fixest. I am guessing here. Conversions can be expensive operations. Trying toggling the conversion rules for what is returned from `marginaleffects.datagrid` to see if this helps.

```python
g = ro.conversion.noconversion(marginaleffects.datagrid)(
    model=model,
    cond=ro.r('0:1'),
    episode=ro.r('1:3'))
```

An other place where performance can take a hit is because in Python expressions in arguments are eagerly evaluated, which results in anonymous data structures being passed around rather than expressions or symbols in R. Binding your argument to an R symbol using call arguments that are unevaluated R language objects (see https://rpy2.github.io/doc/v3.5.x/html/robjects_language.html) will help if this is the root of the performance issue.

```python
ro.globalenv['my_model] = model
g = marginaleffects.datagrid)(
    model=ro.rl('my_model'),
    cond=ro.rl('0:1'),
    episode=ro.rl('1:3'))
```

**Comment by lgautier** [comment]
I am unsure about the enhancement request here. This is seems more like a usage question. Closing.

**Comment by bernardodionisi** [comment]
thank you for your reply!

I am still having the same performance issue with the suggested solutions.

I think the issue may not be related to converting what is coming out from the call, which in this case is a (6, 3) dataframe. I think it is probably related to what is going in, so I thought the second solution might work but I see the same performance as before

**Comment by lgautier** [comment]
Try adding this to the second option to also make `model` an R symbol.

```python
ro.globalenv['my_dataf'] = r_from_pd_df 
model = fixest.feols(
    ro.rl('y ~ cond * episode'),
    data=ro.rl('my_dataf')
)
```

**Comment by lgautier** [comment]
Or to prevent a conversion out of `feols`:

```python
model = ro.conversion.noconversion(fixest.feols)(
    ro.rl('y ~ cond * episode'),
    data=ro.rl('my_dataf')
)
```

**Comment by lgautier** [comment]
If still not resulting in performance improvement, this is truly puzzling. Does the following print the same numbers as in R?

```python
rcode = """
library(marginaleffects)
library(fixest)

n <- 100000

d <- data.frame(
  y = rnorm(n),
  cond = as.factor(sample(0:1, n, TRUE)),
  episode = as.factor(sample(0:4, n, TRUE))
)

model <- fixest::feols(y ~ cond * episode, data = d)

# -------------- timing marginaleffects's datagrid ---------------------

startTime <- Sys.time()

g <- datagrid(model=model, cond = 0:1, episode = 1:3)

endTime <- Sys.time()

print(endTime - startTime)
# Time difference of 0.0740099 secs
"""
ro.r(rcode)
```

**Comment by bernardodionisi** [comment]
Making the input data frame an R symbol seems to do the trick! even with the rest as the original code. Thanks, I had not thought of trying that! There is still a bit of overhead but I imagine that's expected.

Thank you very much for your help!

**Comment by bernardodionisi** [comment]
and I apologize for the enhancement tag, my mistake

**Comment by lgautier** [comment]
> Making the input data frame an R symbol seems to do the trick! even with the rest as the original code. Thanks, I had not thought of trying that! There is still a bit of overhead but I imagine that's expected.
> 
> Thank you very much for your help!

Good. Whether this kind of trick is necessary depends on what is happening in the R code (here likely the package `fixest`). What I provided can results in having to manage objects in `globalenv`. For example being careful about code overwriting objects by using the same symbol name, or deleting them when no longer needed.

A local context can be used to let rpy2 manage that.
https://rpy2.github.io/doc/v3.5.x/html/robjects_environments.html#environments-as-temporary-local-contexts
