### ISSUE TITLE
RRuntimeError while loading 'ggplot2' due to missing 'libRlapack.so'

### ISSUE THREAD

**Issue by thekingofall** [rpy2/rpy2#1015]
Hello,

I encountered an issue while trying to load the 'ggplot2' package using rpy2 in my Python environment. I received an RRuntimeError, and I would appreciate it if you could help me resolve the issue.

Here's the error message I received:
RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  Unable to load shared object '/usr/local/R-4.1.0/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

The error occurred when running the following code:
import rpy2.robjects as robjects
from rpy2.robjects.packages import importr

rscript = '''
data(iris)
print(mean(iris$Sepal.Length))
'''
robjects.r(rscript)
importr("ggplot2")

My environment setup is as follows:

Python version: 3.9
rpy2 version: 3.5.10
R version: 4.1.0
Operating system: centos7
It seems that the 'libRlapack.so' file is missing, causing the error. I'm unsure about the cause of the issue and how to resolve it. Could you please provide some guidance or a possible solution?

Thank you for your assistance.

**Comment by lgautier** [comment]
This is almost certainly because the linker does not know where to find the shared libraries. Check this: https://github.com/rpy2/rpy2/blob/master/README.md#issues-loading-shared-c-libraries

Reopen is this not the issue.

**Comment by thekingofall** [comment]
你好,老茅已收到你的来信，稍后我会仔细查看，谢谢(这是自动回复，不用回复过来）
