### ISSUE TITLE
Issue using R and python in the same jupyter notebook

### ISSUE THREAD

**Issue by aj088** [rpy2/rpy2#1027]
Hi, I installed rpy2 in my conda environment using 

> conda install -c conda-forge rpy2

 Then I installed r kernel for my jupyter notebook.
> conda install -c conda-forge r-irkernel
> R -e 'IRkernel::installspec()'

However, I am unable to use R and python in the same notebook using rpy2. 

> import scanpy as sc

> import rpy2

> %load_ext rpy2.ipython
ImportError: dlopen(/opt/anaconda3/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: /opt/anaconda3/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/site-packages/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/site-packages/../../libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file)

Can you help with this?

**Comment by lgautier** [comment]
The R package `r-irkernel` is not required, and C library loading issues are conda packaging issues. You can try to see if setting `LD_LIBRARY_PATH` before launching jupyter helps (see https://github.com/rpy2/rpy2#issues-loading-shared-c-libraries).
