### ISSUE TITLE
ModuleNotFoundError: No module named '_rinterface_cffi_abi'

### ISSUE THREAD

**Issue by zivlang** [rpy2/rpy2#1034]
**Describe the issue or bug**
When running the python script, which includes importing rpy2, this error message is printed.
A clear and concise description of what the issue or bug is. 

Please note that this to report demonstrated or suspected issues or bugs with rpy2. Check the project's documentation or Stackoverflow to check whether the answer can be found there.

**To Reproduce**
import rpy2.robjects as robjects

Steps to reproduce the behavior are almost always required. This means a self-contained example, that is an example that contains everything needed to try reproduce the issue. If this looks like work to do for the reporter of issue, it is because it is indeed some effort to do so. This helps review and solve the issue.

If this is an issue about installing the software, provide as much information about your system as you think is related: conda used? virtualenv used? environment variables influencing the behavior of R or Python? version for R, Python, and rpy2? Provide also the exact steps followed.

If this is an issue about the rpy2 code, provide all the above, and a minimal code example to trigger the issue. If data is used, that data will be needed to reproduce the issue.

**Expected behavior**

**Error**
Failed to import the API mode with "No module named '_rinterface_cffi_api'" and unable to import the ABI mode.
Traceback (most recent call last):
  File "C:\Users\97254\Working_project\venv\lib\site-packages\rpy2\rinterface_lib\openrlib.py", line 18, in <module>
    import _rinterface_cffi_api as _rinterface_cffi  # type: ignore
ModuleNotFoundError: No module named '_rinterface_cffi_api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\97254\Working_project\venv\lib\site-packages\rpy2\robjects\__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "C:\Users\97254\Working_project\venv\lib\site-packages\rpy2\rinterface.py", line 16, in <module>
    from rpy2.rinterface_lib import openrlib
  File "C:\Users\97254\Working_project\venv\lib\site-packages\rpy2\rinterface_lib\openrlib.py", line 25, in <module>
    raise ie_abi
  File "C:\Users\97254\Working_project\venv\lib\site-packages\rpy2\rinterface_lib\openrlib.py", line 21, in <module>
    import _rinterface_cffi_abi as _rinterface_cffi  # type: ignore
ModuleNotFoundError: No module named '_rinterface_cffi_abi'

**Additional context**
Providing the output of running `python -m rpy2.situation` is highly recommended.
Running `python -m rpy2.situation` resulted in the error message:
`ModuleNotFoundError: No module named 'packaging'`

**Comment by lgautier** [comment]
The API access is preferred but the ABI access exists as a fallback. I don't how this happens. I am seeing that your on Windows, which I do not have to work with. How did you install `rpy2`. Hints about what is happening are likely in the logs / console ouput for that installation.

**Comment by zivlang** [comment]
Hi.
Thank you for the answer and sorry for the late response.
I installed the package by downloading it from its github page and
unzipping it, because the pip installation didn't work.
I posted a question about it on stackoverflow, where the error message is
detailed:
https://stackoverflow.com/questions/76399513/getting-the-error-message-getting-requirements-to-build-wheel-did-not-run-succe/76399531?noredirect=1#comment134718864_76399531
Please take a look and let me know what you think.
Thank you.


בתאריך שבת, 10 ביוני 2023, 21:41, מאת Laurent Gautier ‏<
***@***.***>:

**Comment by lgautier** [comment]
Unzipping will not be enough. There is a build step with cffi during which the API and/or ABI modules are created.

I am closing the issue since this is not installing the package the Python/cffi expect it.
