### ISSUE TITLE
Allow `tzlocal` 5.0+

### ISSUE THREAD

**Issue by nwalters512** [rpy2/rpy2#1035]
**Is your feature request related to a problem? Please describe.**

I'd like to upgrade to `tzlocal` 5.0 in my project. However, that conflicts with `rpy2`'s specified version range:

https://github.com/rpy2/rpy2/blob/e6ee7845094cb656db70b7886931caaa9fe836a7/pyproject.toml#L31

**Describe the solution you'd like**

Now that #1029 has been merged and this project presumably no longer depends at all on `pytz` objects being returned from `tzlocal`, it will hopefully be safe to allow `tzlocal` 5.0+.

**Describe alternatives you've considered**

I could permanently pin `tzlocal` to an older version; I'd rather not do that.

**Comment by lgautier** [comment]
It makes sense to no limit dependency to older version if it can be avoided. I created PR #1036.

**Comment by lgautier** [comment]
Fixed with #1036 .
