### ISSUE TITLE
error in R extraction with kwargs 

### ISSUE THREAD

**Issue by bernardodionisi** [rpy2/rpy2#1048]
Hi, I think there is a small bug here.

https://github.com/rpy2/rpy2/blob/3312af0f5e38d1a15262cef0b9b780834c514d7c/rpy2/robjects/vectors.py#L81

``values()`` is used in place of ``kwargs.items()``. Thanks!

**Comment by lgautier** [comment]
Indeed. Thanks. Fix on the way.
