### ISSUE TITLE
py2rpy conversion of an R object

### ISSUE THREAD

**Issue by jonathan-taylor** [rpy2/rpy2#1060]
**Describe the issue or bug**

Trying to use local conversion as follows:

```
import numpy as np

n, p = 1000, 50
X = np.random.standard_normal((n, p))
y = np.random.standard_normal(n)
W = np.ones(n)
intercept = standardize = True
from rpy2.robjects.packages import importr
from rpy2.robjects import numpy2ri
from rpy2.robjects import default_converter

glmnetR = importr('glmnet')
baseR = importr('base')
np_cv_rules = default_converter + numpy2ri.converter

with np_cv_rules.context():
       G = glmnetR.glmnet(X, y, weights=W, intercept=intercept, standardize=standardize)
       B = glmnetR.predict_glmnet(G, s=2 / np.sqrt(n), type="coef", exact=True, x=X, y=y, weights=W)
       soln_R = baseR.as_numeric(B)
       intercept_R = soln_R[0]
       coef_R = soln_R[1:]

```

The call to `glmnetR.glmnet` runs fine, but I get a conversion error when trying to call `glmnetR.predict_glmnet`: 

```
NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'rpy2.rlike.container.OrdDict'>'
```

**So, the question is, how to call an R function with an R object (i.e. G) and `np.ndarray` using local conversion rules?**

**To Reproduce**

Steps to reproduce the behavior are almost always required. This means a self-contained example, that is an example that contains everything needed to try reproduce the issue. If this looks like work to do for the reporter of issue, it is because it is indeed some effort to do so. This helps review and solve the issue.

If this is an issue about installing the software, provide as much information about your system as you think is related: conda used? virtualenv used? environment variables influencing the behavior of R or Python? version for R, Python, and rpy2? Provide also the exact steps followed.

If this is an issue about the rpy2 code, provide all the above, and a minimal code example to trigger the issue. If data is used, that data will be needed to reproduce the issue.

**Expected behavior**

This works with no exception using the global `numpy2ri.activate()`:

```
import numpy as np

n, p = 1000, 50
X = np.random.standard_normal((n, p))
y = np.random.standard_normal(n)
W = np.ones(n)
intercept = standardize = True
from rpy2.robjects.packages import importr
from rpy2.robjects import numpy2ri
from rpy2.robjects import default_converter

glmnetR = importr('glmnet')
baseR = importr('base')
np_cv_rules = default_converter + numpy2ri.converter

numpy2ri.activate()
G = glmnetR.glmnet(X, y, weights=W, intercept=intercept, standardize=standardize)
B = glmnetR.predict_glmnet(G, s=2 / np.sqrt(n), type="coef", exact=True, x=X, y=y, weights=W)
soln_R = baseR.as_numeric(B)
intercept_R = soln_R[0]
coef_R = soln_R[1:]
```

**Error**

```
NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'rpy2.rlike.container.OrdDict'>'
```

**Additional context**
Providing the output of running `python -m rpy2.situation` is highly recommended.

rpy2 version:
3.5.13
Python version:
3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /Library/Frameworks/R.framework/Resources
    Environment variable R_LIBS_USER: None
R's value for LD_LIBRARY_PATH:

R version:
    In the PATH: R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/Library/Frameworks/R.framework/Resources/include']
  libraries:
  ['pcre2-8', 'lzma', 'bz2', 'z', 'icucore', 'dl', 'm', 'iconv']
  library_dirs:
  ['/opt/R/arm64/lib', '/opt/R/arm64/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-F/Library/Frameworks/R.framework/..', '-framework', 'R']
Directory for the R shared library:
lib
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: PRESENT

**Comment by lgautier** [comment]
This might have been solved with https://github.com/rpy2/rpy2/pull/1056 . Does an update to rpy2 3.5.14 solve the issue?

**Comment by jonathan-taylor** [comment]
Seems to have fixed it

Thanks!
________________________________
