### ISSUE TITLE
Numpy Exception 

### ISSUE THREAD

**Issue by obrien-james** [rpy2/rpy2#1065]
**Describe the issue or bug**

Hi, when trying to run R inside my VSCode ipynb notebook using the magic cell %%R, I am getting a 2 exceptions:

`AttributeError: 'numpy.str_' object has no attribute '__sexp__'`

`ValueError: Not an rpy2 R object and unable to map it to one: 'value'`

These are my current versions:
rpy2 = 3.5.11
R = 4.3.1
Python = 3.10.12

Im trying to debug a bigger issue of using anndata2ri and rpy2 which throughs the same exceptions so I thought I would try some simple R to see if the same occurs.

**To Reproduce**

```
import numpy as np
import scipy as sp
import pandas as pd

import rpy2.rinterface_lib.callbacks
import logging

from rpy2.robjects import pandas2ri
from rpy2.robjects import numpy2ri
import anndata2ri
```
```
rpy2.rinterface_lib.callbacks.logger.setLevel(logging.ERROR)

pandas2ri.activate()
numpy2ri.activate()
anndata2ri.activate()

%load_ext rpy2.ipython
```
```
%%R
x<-5:6
x

```

**Error**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py:179](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py:179), in _get_cdata(obj)
    178 try:
--> 179     cdata = obj.__sexp__._cdata
    180 except AttributeError:

AttributeError: 'numpy.str_' object has no attribute '__sexp__'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/Users/james/Documents/Work/Research](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research) Job/Computational/Parse Test/analysis/R Demo .ipynb Cell 3 line 1
----> [1](vscode-notebook-cell:/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/R%20Demo%20.ipynb#X21sZmlsZQ%3D%3D?line=0) get_ipython().run_cell_magic('R', '', 'x<-5:6\nx\n')

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2493](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2493), in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2491 with self.builtin_trap:
   2492     args = (magic_arg_s, cell)
-> 2493     result = fn(*args, **kwargs)
   2495 # The code below prevents the output from being displayed
   2496 # when using magics with decorator @output_can_be_silenced
   2497 # when the last Python token in the expression is a ';'.
   2498 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/ipython/rmagic.py:935](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/ipython/rmagic.py:935), in RMagics.R(self, line, cell, local_ns)
    927                 if self.cache_display_data:
    928                     stack.enter_context(
    929                         rpy2.rinterface_lib
    930                         .callbacks
   (...)
    933                                        'consolewrite_print',
    934                                        self.write_console_regular))
--> 935                 cell_display(result, args)
    936                 text_output += self.flush()
    938 except RInterpreterError as e:
    939     # TODO: Maybe we should make this red or something?

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/ipython/rmagic.py:134](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/ipython/rmagic.py:134), in CELL_DISPLAY_DEFAULT(res, args)
    133 def CELL_DISPLAY_DEFAULT(res, args):
--> 134     return ro.r.show(res)

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/robjects/functions.py:208](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/robjects/functions.py:208), in SignatureTranslatedFunction.__call__(self, *args, **kwargs)
    206         v = kwargs.pop(k)
    207         kwargs[r_k] = v
--> 208 return (super(SignatureTranslatedFunction, self)
    209         .__call__(*args, **kwargs))

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/robjects/functions.py:131](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/robjects/functions.py:131), in Function.__call__(self, *args, **kwargs)
    129     else:
    130         new_kwargs[k] = cv.py2rpy(v)
--> 131 res = super(Function, self).__call__(*new_args, **new_kwargs)
    132 res = cv.rpy2py(res)
    133 return res

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py:45](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py:45), in _cdata_res_to_rinterface.<locals>._(*args, **kwargs)
     44 def _(*args, **kwargs):
---> 45     cdata = function(*args, **kwargs)
     46     # TODO: test cdata is of the expected CType
     47     return _cdata_to_rinterface(cdata)

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface.py:807](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface.py:807), in SexpClosure.__call__(self, *args, **kwargs)
    804 error_occured = _rinterface.ffi.new('int *', 0)
    805 with memorymanagement.rmemory() as rmemory:
    806     call_r = rmemory.protect(
--> 807         _rinterface.build_rcall(self.__sexp__._cdata, args,
    808                                 kwargs.items()))
    809     call_context = evaluation_context.get()
    810     res = rmemory.protect(
    811         openrlib.rlib.R_tryEval(
    812             call_r,
    813             call_context.__sexp__._cdata,
    814             error_occured)
    815     )

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/_rinterface_capi.py:317](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/_rinterface_capi.py:317), in build_rcall(rfunction, args, kwargs)
    315 item = rlib.CDR(rcall)
    316 for val in args:
--> 317     cdata = rmemory.protect(conversion._get_cdata(val))
    318     rlib.SETCAR(item, cdata)
    319     item = rlib.CDR(item)

File [~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py:181](https://file+.vscode-resource.vscode-cdn.net/Users/james/Documents/Work/Research%20Job/Computational/Parse%20Test/analysis/~/miniconda3/envs/lilacs/lib/python3.10/site-packages/rpy2/rinterface_lib/conversion.py:181), in _get_cdata(obj)
    179         cdata = obj.__sexp__._cdata
    180     except AttributeError:
--> 181         raise ValueError('Not an rpy2 R object and unable '
    182                          'to map it to one: %s' % repr(obj))
    183 else:
    184     cdata = cls(obj)

ValueError: Not an rpy2 R object and unable to map it to one: 'value'

**Additional context**
`python -m rpy2.situation`:

rpy2 version:
3.5.11
Python version:
3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:39:40) [Clang 15.0.7 ]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /Users/james/miniconda3/envs/lilacs/lib/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:

R version:
    In the PATH: R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/Users/james/miniconda3/envs/lilacs/lib/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'dl', 'm', 'iconv', 'icuuc', 'icui18n']
  library_dirs:
  ['/Users/james/miniconda3/envs/lilacs/lib', '/Users/james/miniconda3/envs/lilacs/lib/R/lib', '/Users/james/miniconda3/envs/lilacs/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-fopenmp', '-Wl,-dead_strip_dylibs', '-Wl,-pie', '-Wl,-headerpad_max_install_names', '-Wl,-dead_strip_dylibs', '-Wl,-rpath,/Users/james/miniconda3/envs/lilacs/lib']
Directory for the R shared library:
lib
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: PRESENT

**Comment by obrien-james** [comment]
Hi, 

I turns out this was an issue with anndata2ri - when I ran the code again without anndata2ri imported it worked. There must be a compatibility issue, as I've downgraded my anndata2ri and rpy2 packages and it all works ok. 

anndata2ri version now 1.1
rpy2 version now 3.5.1

Hopefully this helps someone in the future.

**Comment by thisisamirv** [comment]
Same issue here

**Comment by leipnerm** [comment]
I had the same issue, with a nearly identical traceback.

Previous install versions were:
rpy2 = 3.5.11
anndata2ri = 1.3.1
R = 4.2.2
python = 3.9.18

after downgrading anndata2ri to 1.1 everything seems to work ok again.
Thanks @obrien-james!

**Comment by fredsamhaak** [comment]
> Hi,
> 
> I turns out this was an issue with anndata2ri - when I ran the code again without anndata2ri imported it worked. There must be a compatibility issue, as I've downgraded my anndata2ri and rpy2 packages and it all works ok.
> 
> anndata2ri version now 1.1 rpy2 version now 3.5.1
> 
> Hopefully this helps someone in the future.

Thx @obrien-james, downgrading anndata2ri to 1.1 works fine.
