### ISSUE TITLE
Pandas Categorial data 

### ISSUE THREAD

**Issue by obrien-james** [rpy2/rpy2#1072]
Hi,

Im using rpy2 and pandas2ri to convert a pandas data from to an R data frame, in a magic cell in JupyterNotebook. 

2 of the columns in the pandas data frame are categorical in nature, but when using the below code, the columns which are categories and text are converted to numbers which I assume represent the category index.

```
%%R -i df
rdf <- df
```

Is there a way to prevent this from happening, or to map the category as text rather than as part of an indexed list?

**Comment by lgautier** [comment]
I don't see any issue with rpy2.

Code cells:

```python
import pandas
df = pandas.DataFrame({'x': pandas.Categorical(('a', 'b', 'a'))})
```
```python
%load_ext rpy2.ipython
```
```
%%R -i df
 rdf <- df
 str(rdf)
```

The output of the last cell shows an R `data.frame` with a column of type 'factor`, which is the counterpart of pandas's Categorical arrays:
```
'data.frame':	3 obs. of  1 variable:
 $ x: Factor w/ 2 levels "a","b": 1 2 1
```
