### ISSUE TITLE
Issue on %%R in Google Colab

### ISSUE THREAD

**Issue by SciComp8** [rpy2/rpy2#1074]
**Describe the issue or bug**

In the Jupyter notebook of Google colab , %%R fails with the `NotImplementedError`:
NotImplementedError: 
    Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.

I look forward to learning your advice or suggestions! Thank you so so much in advance.

**To Reproduce**
```
!pip install anndata2ri # Install the latest 1.3.1 version
import anndata2ri
anndata2ri.activate()
%load_ext rpy2.ipython
%%R
a = 1
```

**Error**
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[6], line 1
----> 1 get_ipython().run_cell_magic('R', '', 'a = 1\n')

File /usr/local/lib/python3.10/dist-packages/google/colab/_shell.py:334, in Shell.run_cell_magic(self, magic_name, line, cell)
    332 if line and not cell:
    333   cell = ' '
--> 334 return super().run_cell_magic(magic_name, line, cell)

File /usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:2515, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2513 with self.builtin_trap:
   2514     args = (magic_arg_s, cell)
-> 2515     result = fn(*args, **kwargs)
   2517 # The code below prevents the output from being displayed
   2518 # when using magics with decorator @output_can_be_silenced
   2519 # when the last Python token in the expression is a ';'.
   2520 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File /usr/local/lib/python3.10/dist-packages/rpy2/ipython/rmagic.py:929, in RMagics.R(self, line, cell, local_ns)
    926 else:
    927     cell_display = CELL_DISPLAY_DEFAULT
--> 929 tmpd = self.setup_graphics(args)
    931 text_output = ''
    932 display_data = []

File /usr/local/lib/python3.10/dist-packages/rpy2/ipython/rmagic.py:631, in RMagics.setup_graphics(self, args)
    628 if self.device in DEVICES_STATIC_RASTER:
    629     # Note: that %% is to pass into R for interpolation there.
    630     rfunc = getattr(grdevices, self.device)
--> 631     rfunc(f'{tmpd_fix_slashes}/Rplots%%03d.{self.device}',
    632           **argdict)
    633 elif self.device == 'svg':
    634     self.cairo.CairoSVG(f'{tmpd_fix_slashes}/Rplot.svg',
    635                         **argdict)

File /usr/local/lib/python3.10/dist-packages/rpy2/robjects/functions.py:208, in SignatureTranslatedFunction.__call__(self, *args, **kwargs)
    206         v = kwargs.pop(k)
    207         kwargs[r_k] = v
--> 208 return (super(SignatureTranslatedFunction, self)
    209         .__call__(*args, **kwargs))

File /usr/local/lib/python3.10/dist-packages/rpy2/robjects/functions.py:123, in Function.__call__(self, *args, **kwargs)
    121 def __call__(self, *args, **kwargs):
    122     cv = conversion.get_conversion()
--> 123     new_args = [cv.py2rpy(a) for a in args]
    124     new_kwargs = {}
    125     for k, v in kwargs.items():
    126         # TODO: shouldn't this be handled by the conversion itself ?

File /usr/local/lib/python3.10/dist-packages/rpy2/robjects/functions.py:123, in <listcomp>(.0)
    121 def __call__(self, *args, **kwargs):
    122     cv = conversion.get_conversion()
--> 123     new_args = [cv.py2rpy(a) for a in args]
    124     new_kwargs = {}
    125     for k, v in kwargs.items():
    126         # TODO: shouldn't this be handled by the conversion itself ?

File /usr/lib/python3.10/functools.py:889, in singledispatch.<locals>.wrapper(*args, **kw)
    885 if not args:
    886     raise TypeError(f'{funcname} requires at least '
    887                     '1 positional argument')
--> 889 return dispatch(args[0].__class__)(*args, **kw)

File /usr/local/lib/python3.10/dist-packages/rpy2/robjects/conversion.py:383, in _raise_missingconverter(obj)
    377 def _raise_missingconverter(obj):
    378     _missingconverter_msg = """
    379     Conversion rules for `rpy2.robjects` appear to be missing. Those
    380     rules are in a Python contextvars.ContextVar. This could be caused
    381     by multithreading code not passing context to the thread.
    382     """
--> 383     raise NotImplementedError(_missingconverter_msg)

NotImplementedError: 
    Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.
    

**Additional context**
```
!python -m rpy2.situation
```
rpy2 version:
3.5.14
Python version:
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Looking for R's HOME:
    Environment variable R_HOME: /usr/lib/R
    Calling `R RHOME`: /usr/lib/R
    Environment variable R_LIBS_USER: /root/R/x86_64-pc-linux-gnu-library/4.3
R's value for LD_LIBRARY_PATH:
/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server:/usr/lib/R/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
R version:
    In the PATH: R version 4.3.2 (2023-10-31) -- "Eye Holes"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/share/R/include']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'tirpc', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib/R/lib']
  extra_compile_args:
  ['-std=c99']
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-Bsymbolic-functions', '-flto=auto', '-ffat-lto-objects', '-flto=auto', '-Wl,-z,relro']
Directory for the R shared library:
lib
CFFI extension type
  Environment variable: RPY2_CFFI_MODE
  Value: CFFI_MODE.ANY
  ABI: PRESENT
  API: PRESENT

**Comment by ScienceComputing** [comment]
> Duplicate of #965 (See [#965 (comment)](https://github.com/rpy2/rpy2/issues/965#issuecomment-1366816256)). The issue is with Colab.
> 
> A workaround is to specify the converter to use with each `%%R` cell (option `-c`).

Thank you. Could you show me a simple example about how to specify the converter?

**Comment by lgautier** [comment]
> > Duplicate of #965 (See [#965 (comment)](https://github.com/rpy2/rpy2/issues/965#issuecomment-1366816256)). The issue is with Colab.
> > A workaround is to specify the converter to use with each `%%R` cell (option `-c`).
> 
> Thank you. Could you show me a simple example about how to specify the converter?

Check the code example in the second box "Note" here: https://rpy2.github.io/doc/v3.5.x/html/robjects_convert.html#local-conversion-rules
