### ISSUE TITLE
Issues Integrating Library Functions with Python via rpy2

### ISSUE THREAD

**Issue by Arminkhayati** [rpy2/rpy2#1096]
Hello,

I am currently working on integrating `grplasso` library functions from R into a Python project using `rpy2`. Specifically, I'm attempting to call the `grplasso` function with the following parameters in R:

```r
grplasso::grplasso(X.con.W, Y.con, index=grpindex.with.NA,
                   lambda=grplambda, penscale=sqrt, model=grplasso::LinReg(), center=FALSE,
                   standardize=FALSE, control = grplasso::grpl.control(trace=0))
```

However, I've encountered a couple of issues during this process:

1. **Keyword Conflict with `lambda`:** When trying to call this function through `rpy2`, the `lambda` argument leads to a syntax error because it is a reserved keyword in Python. Is there a recommended workaround or an alternative method to bypass this conflict?

2. **Passing the `sqrt` Function for `penscale`:** The `penscale` argument requires the square root function from R. How can I correctly pass this function using `rpy2` to ensure proper execution?

To reproduce these issues, I am using the following Python code snippet:

```python
from rpy2 import robjects
from rpy2.robjects.packages import importr

grplasso = importr("grplasso")

grplasso.grplasso(X_con_W, Y_con, index=grpindex_with_NA, lambda=grplambda, penscale=robjects.r['sqrt'], 
                              model=grplasso.LinReg(), center=False,
                              standardize=False, control=grplasso.grpl_control(trace=0))
```

I appreciate any guidance or suggestions on how to resolve these issues to achieve seamless integration between `rpy2` and the `grplasso` library.

Thank you for your time and assistance.

**Comment by lgautier** [comment]
Not a bug. Use the `**kwargs` syntax (see the doc here: https://rpy2.github.io/doc/v3.5.x/html/robjects_functions.html#callable).

**Comment by Arminkhayati** [comment]
> Not a bug. Use the `**kwargs` syntax (see the doc here: https://rpy2.github.io/doc/v3.5.x/html/robjects_functions.html#callable).

Thank you. So my function call will be look like this?

```
grplasso.grplasso(X_con_W, Y_con, index=grpindex_with_NA=, penscale=robjects.r['sqrt'], 
                              model=grplasso.LinReg(), center=False,
                              standardize=False, control=grplasso.grpl_control(trace=0),
                              **{'lambda':grplambda, } )
```
