### ISSUE TITLE
Installation on linux platform

### ISSUE THREAD

**Issue by EQUIWDH** [rpy2/rpy2#1101]
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Unable to determine R home: [Errno 2] No such file or directory: 'R'
      cffi mode is CFFI_MODE.ANY
      Looking for R home with: R RHOME
      Unable to determine R home: [Errno 2] No such file or directory: 'R'
      R home found: None
      Error: rpy2 in API mode cannot be built without R in the PATH or R_HOME defined. Correct this or force ABI mode-only by defining the environment variable RPY2_CFFI_MODE=ABI
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I added `R_HOME` on the `~/.bashrc`, It still can not work, what should I do

**Comment by lgautier** [comment]
Then your `R_HOME` is likely incorrect. Make sure `R` is in your `PATH`  (that is when you type `R` in a terminal you get R to start), and unset `R_HOME`.
