### ISSUE TITLE
NotImplementedError: Conversion rules for `rpy2.robjects` appear to be missing. Those rules are in a Python contextvars.ContextVar. This could be caused by multithreading code not passing context to the thread.

### ISSUE THREAD

**Issue by PARODBE** [rpy2/rpy2#1102]
Hi!

I'm developing an application using streamlit. And I get the error in the title when I try to convert pandas df in r dataframe. It's very curious because when I use rpy2==3.5.15 I don't get this error, but I am dockering my app and only allow me install rpy2==3.5.11 version. The code that I'm using is:

with (ro.default_converter + pandas2ri.converter).context():
    pandas_df_2_r = ro.conversion.py2rpy(pd.DataFrame(df_nuevo_def3))
    r.assign("df_r", pandas_df_2_r)

Any idea of how install rpy2==3.5.15 in docker or how can I solve this problem using 3.5.11 version???

Thanks!
Pablo

pd. I don't reproduce this error in a jupyter notebook only in my streamlit app

**Comment by lgautier** [comment]
Hi, this is a duplicate. This has been reported a few time now. This is because streamlit's multhreading does not manage contexts. Wrap your calls to R wit the local converter of your choice. The doc rebuild will have this:

https://github.com/rpy2/rpy2/pull/1076/files#diff-0f477f4ec1a1057412d1907d470a84b42251161f3581383d2713e7775b6a62bfR88

**Comment by PARODBE** [comment]
I worked with an older version of rpy2 (3.5.1) instead of the newest and I created this code:

def py2rpy_pandasdataframe(obj):
    from collections import OrderedDict
    od = OrderedDict()
    for name, values in obj.items():  # Cambio de iteritems() a items()
        try:
            od[name] = pandas2ri.py2rpy(values)
        except Exception as e:
            print('Error while trying to convert the column "%s". Fall back to string conversion. The error is: %s' % (name, str(e)))
            od[name] = ro.StrVector(values)
    return ro.DataFrame(od)

Because it gives me an iteritem error, indeed the previous code was:
@py2rpy.register(PandasDataFrame)
def py2rpy_pandasdataframe(obj):
    od = OrderedDict()
    for name, values in obj.iteritems():
        try:
            od[name] = conversion.py2rpy(values)
        except Exception as e:
            warnings.warn('Error while trying to convert '
                          'the column "%s". Fall back to string conversion. '
                          'The error is: %s'
                          % (name, str(e)))
            od[name] = StrVector(values)

    return DataFrame(od)

With the above code, It solved my problem in streamlit for docker. However, for streamlit in my local with rpy2==3.5.15 was ok doing something like this:

with (ro.default_converter + pandas2ri.converter).context():
    pandas_df_2_r = ro.conversion.py2rpy(df)
    r.assign("df_r", pandas_df_2_r)

and after I create the r code:

script_r = r('''
                  ''')

And, now imagen if I create a dataframe in this script_r and I convert it to a pandas dataframe format:

with localconverter(default_converter + pandas2ri.converter) as cv:
        dm_tks = robjects.conversion.rpy2py(robjects.r['df_created_in_r'])
        
Everything worked for me in streamlit, if you want you can put this message as a solution for the rest of users...
