### ISSUE TITLE
Cannot import packages

### ISSUE THREAD

**Issue by ryrl970311** [rpy2/rpy2#1109]
**Describe the issue or bug**
![Xnip2024-05-20_14-13-12](https://github.com/rpy2/rpy2/assets/74189428/77510f2f-a151-4138-b337-d979ac38e3b6)

A clear and concise description of what the issue or bug is. 

Please note that this to report demonstrated or suspected issues or bugs with rpy2. Check the project's documentation or Stackoverflow to check whether the answer can be found there.

**To Reproduce**

Steps to reproduce the behavior are almost always required. This means a self-contained example, that is an example that contains everything needed to try reproduce the issue. If this looks like work to do for the reporter of issue, it is because it is indeed some effort to do so. This helps review and solve the issue.

If this is an issue about installing the software, provide as much information about your system as you think is related: conda used? virtualenv used? environment variables influencing the behavior of R or Python? version for R, Python, and rpy2? Provide also the exact steps followed.

If this is an issue about the rpy2 code, provide all the above, and a minimal code example to trigger the issue. If data is used, that data will be needed to reproduce the issue.

**Expected behavior**

**Error**
A copy of the error message.

**Additional context**
Providing the output of running `python -m rpy2.situation` is highly recommended.

**Comment by lgautier** [comment]
I presume that rpy2 was indeed installed in an usual way. I am closing. Reopen when more information is available.
