### ISSUE TITLE
unable to load shared object '/usr/lib/R/library/methods/libs/methods.so':   /usr/lib/R/library/methods/libs/methods.so: undefined symbol: R_typeToChar

### ISSUE THREAD

**Issue by Luk-stip** [rpy2/rpy2#1110]
When importing rpy2.robjects I get the following error message: 

import rpy2.robjects as objects

(the first print is due to: print(os.system('R --version'))
R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

0
Warning messages:
1: package ‘methods’ was built under R version 4.4.0 
2: package "methods" in options("defaultPackages") was not found 
During startup - There were 11 warnings (use warnings() to see them)
R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/methods/libs/methods.so':
  /usr/lib/R/library/methods/libs/methods.so: undefined symbol: R_typeToChar

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lstippel/Documents/Projects/running_on_server-main/Predicting/Predictionmodels.py", line 8, in <module>
    from Dennis_oco_package import running_dennis,basic_functions_dennis
  File "/home/lstippel/Documents/Projects/running_on_server-main/Dennis_oco_package/running_dennis.py", line 4, in <module>
    from Dennis_oco_package import  basic_functions_dennis as bd
  File "/home/lstippel/Documents/Projects/running_on_server-main/Dennis_oco_package/basic_functions_dennis.py", line 16, in <module>
    import rpy2.robjects as robjects
  File "/home/lstippel/.conda/envs/running_on_server-main/lib/python3.9/site-packages/rpy2/robjects/__init__.py", line 18, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/home/lstippel/.conda/envs/running_on_server-main/lib/python3.9/site-packages/rpy2/robjects/robject.py", line 81, in <module>
    class RObjectMixin(abc.ABC):
  File "/home/lstippel/.conda/envs/running_on_server-main/lib/python3.9/site-packages/rpy2/robjects/robject.py", line 93, in RObjectMixin
    __show = _get_exported_value('methods', 'show')
  File "/home/lstippel/.conda/envs/running_on_server-main/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/lstippel/.conda/envs/running_on_server-main/lib/python3.9/site-packages/rpy2/rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/methods/libs/methods.so':
  /usr/lib/R/library/methods/libs/methods.so: undefined symbol: R_typeToChar

I followed the instructions and set: 
os.environ['R_HOME'] = '/usr/lib/R'
Where our R distribution is saved .

In R if I execute .libPaths() it returns as one of the paths /usr/lib/R/library/ 
and states methods is already existing
 I tried: os.environ['R_LIBS_USER'] = '/home/lstippel/R/x86_64-pc-linux-gnu-library/4.4' also as it is a local copy of mine.
.

On my local machine it runs without any issue, hence I assume I made an error with some path, but  I don't see the issue as the package is where it should be and is built correctly as far as I know. 

Thank you!

**Comment by walidabualafia** [comment]
Hi folks. Getting the same error. Does anyone know a workaround? Thanks! :)

**Comment by lgautier** [comment]
Hi,

> I followed the instructions and set:
os.environ['R_HOME'] = '/usr/lib/R'
Where our R distribution is saved .

Putting R in the `PATH` might not be enough if the system's dynamic loading does not know where to find the R shared libraries for that executable, or R looks for packages installed for a different R version. You can spot of first sign of this when starting the embedded R.

```
R version 4.4.0 (2024-04-24) -- "Puppy Cup"
```
(...)
```
Warning messages:
1: package ‘methods’ was built under R version 4.4.0
2: package "methods" in options("defaultPackages") was not found
```
(...)
```
/usr/lib/R/library/methods/libs/methods.so: undefined symbol: R_typeToChar
```

The warning messages indicate that R libraries installed for different R version are picked up. It eventually ends with an incorrect shared library being loaded.

You appear to have installed at least some of the requirements with `conda`. Check whether all your packages are up-to-date, or have mixed conda-installed packages and R packages installed with R's package manager. Finally, if the issue persists tell the system how to load the correct R shared library as indicated here: https://github.com/rpy2/rpy2/blob/master/README.md#issues-loading-shared-c-libraries

**Comment by MaximilianNuber** [comment]
I wanted to ask.

> You appear to have installed at least some of the requirements with conda. Check whether all your packages are up-to-date, or have mixed conda-installed packages and R packages installed with R's package manager. 

Is it a problem to have mixed installs between conda and CRAN/Bioconductor packages? I currently don´t see another way, as conda/bioconda bioconductor version is still on 3.18 (current is 3.19), so I need to install from CRAN/Bioconductor directly.  Some packages, most of all Cairo, are cuase for install errors when required by packages I install from CRAN/Bioconductor, so I need to install with conda (didnt work otherwise). And then I get exactly `undefined symbol: R_typeToChar `.

Is there any way to solve this issue with a mix of CRAN/Bioconductor and conda install packages?

Thank you for any help.

**Comment by dajtxx** [comment]
I've hit this problem running with the following env:

* Apple M1 running a:
* Debian VM running a:
* Container based upon rocker/r-ver:4.5.0

I received exactly that error.

I found two copies of methods.so in the container. The one in /usr/lib/... does _not_ have that symbol, the one in /usr/local/lib/... _does_ have it.

The solution in the link above worked for me by making the shared library loader find the /usr/local/lib copy of methods.so first.
