### ISSUE TITLE
Dealing with R6 objects 

### ISSUE THREAD

**Issue by thierrymoudiki** [rpy2/rpy2#1112]
Not an issue, but a question: what's the best way to deal with [R6 objects](https://r6.r-lib.org/articles/Introduction.html) (**object oriented** variables which are imported in Python as R `Environment`s)? Here is what I did (but on some platforms, not all, there are either parsing errors, or the object instance can't be created twice with `$new()`): 

https://github.com/Techtonique/learningmachine_python/blob/main/learningmachine/classifier.py#L56  

This syntax is much better (and I've been using it successfully before) than what I did, and _ideally_ I'd like to be able to do something similar: https://rpy2.github.io/doc/latest/html/introduction.html#principal-component-analysis

**Comment by lgautier** [comment]
I don't know if this is the best way but `rpy2-r6` ( https://github.com/rpy2/rpy2-r6 ) proposes an interface to R6.

> https://github.com/Techtonique/learningmachine_python/blob/main/learningmachine/classifier.py#L56

The dynamic construction of strings to be evaluated as R code might have to account for LOCALE or encoding peculiarities. May be this what causes the parsing errors you mention. It is hard to tell more without knowing what the exact error is, on what platform, etc.

There is only a limited amount of documentation, but that should cover how to call `$new()` from Python/rpy2:
https://rpy2.github.io/rpy2-r6/version/master/html/index.html#a-first-example

**Comment by thierrymoudiki** [comment]
Looks great, thanks. I'll give it a try. 

For the platform, it's a Linux platform: Google Colab notebooks (getting either parsing errors, or the object instance can't be created **twice** with `$new()`).

**Comment by lgautier** [comment]
Colab has a long-standing issue with Python context variables (https://github.com/googlecolab/colabtools/issues/3212). You might have to specify the conversion context for each cell. Otherwise rpy2-r6 should do, or show, how to achieve what you want.
