### ISSUE TITLE
rpy2 Installation error

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#287]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/276) by Ryo Eng (Bitbucket: [Ryo Eng](https://bitbucket.org/Ryo Eng), ).**

----------------------------------------

Hi,

Nice to know the news that rpy2 maintain again. I am using Anaconda3 (Python3.4 version) and R3.2.0 tried to install rpy2 on Win8.1x64:-
1) *easy_install rpy2*
2) *pip install rpy2*
3) *python setup.py install* on downloaded extracted file

System prompted me *Error:Tried to guess R's HOME but no R command in the path*
[http://eurekastatistics.com/installing-rpy2](http://eurekastatistics.com/installing-rpy2)

Any solution? Thanks appreciated.

Best,
Ryo

**Comment by paulmueller** [comment]
I suggest to close this issue, because:
- Windows 8 (don't even get support from Microsoft anymore)
- There were several fixes recently and before that regarding R_HOME on Windows (via registry)

**Comment by lgautier** [comment]
Ok. Thanks. Closing.
