### ISSUE TITLE
Compile error in array.c (VC++ 2008, R 2.9.0)

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#30]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/21) by Anonymous.**

----------------------------------------

Compiling in windows against R 2.9.0 using VC++ 2008 results in the following:
    
    c:\OpenSource\ryp2\rpy2\rpy\rinterface\rpy_rinterface.h(19) : warning C4114: same type qualifier used more than once
    c:\OpenSource\ryp2\rpy2\rpy\rinterface\rpy_rinterface.h(20) : warning C4114: same type qualifier used more than once
    rpy\rinterface\array.c(115) : error C2275: 'PyArrayInterface' : illegal use of this type as an expression
            rpy\rinterface\array.c(27) : see declaration of 'PyArrayInterface'
    rpy\rinterface\array.c(115) : error C2065: 'inter' : undeclared identifier
    rpy\rinterface\array.c(116) : error C2143: syntax error : missing ';' before 'type'
    rpy\rinterface\array.c(117) : error C2065: 'typekind' : undeclared identifier
    rpy\rinterface\array.c(121) : warning C4047: '=' : 'int' differs in levels of indirection from 'PyArrayInterface *'
    rpy\rinterface\array.c(125) : error C2143: syntax error : missing ';' before 'type'
    rpy\rinterface\array.c(126) : error C2143: syntax error : missing ';' before 'type'
    rpy\rinterface\array.c(127) : error C2223: left of '->version' must point to struct/union
    rpy\rinterface\array.c(128) : error C2223: left of '->nd' must point to struct/union
    rpy\rinterface\array.c(128) : error C2065: 'nd' : undeclared identifier
    rpy\rinterface\array.c(129) : error C2223: left of '->typekind' must point to struct/union
    rpy\rinterface\array.c(130) : error C2223: left of '->itemsize' must point to struct/union
    rpy\rinterface\array.c(131) : error C2223: left of '->flags' must point to struct/union
    rpy\rinterface\array.c(132) : error C2223: left of '->shape' must point to struct/union
    rpy\rinterface\array.c(133) : error C2223: left of '->shape' must point to struct/union
    rpy\rinterface\array.c(133) : warning C4047: 'function' : 'Py_intptr_t *' differs in levels of indirection from 'int'
    rpy\rinterface\array.c(133) : error C2198: 'sexp_shape' : too few arguments for call through pointer-to-function
    rpy\rinterface\array.c(134) : error C2223: left of '->strides' must point to struct/union
    rpy\rinterface\array.c(134) : error C2223: left of '->shape' must point to struct/union
    rpy\rinterface\array.c(135) : error C2275: 'Py_intptr_t' : illegal use of this type as an expression
            c:\Python25\include\pyport.h(90) : see declaration of 'Py_intptr_t'
    rpy\rinterface\array.c(135) : error C2146: syntax error : missing ';' before identifier 'stride'
    rpy\rinterface\array.c(135) : error C2144: syntax error : '<Unknown>' should be preceded by '<Unknown>'
    rpy\rinterface\array.c(135) : error C2144: syntax error : '<Unknown>' should be preceded by '<Unknown>'
    rpy\rinterface\array.c(135) : error C2143: syntax error : missing ';' before 'identifier'
    rpy\rinterface\array.c(135) : error C2065: 'stride' : undeclared identifier
    rpy\rinterface\array.c(135) : error C2223: left of '->itemsize' must point to struct/union
    rpy\rinterface\array.c(136) : error C2223: left of '->strides' must point to struct/union
    rpy\rinterface\array.c(137) : error C2065: 'i' : undeclared identifier
    rpy\rinterface\array.c(138) : error C2223: left of '->shape' must point to struct/union
    rpy\rinterface\array.c(139) : error C2223: left of '->strides' must point to struct/union
    rpy\rinterface\array.c(141) : error C2223: left of '->data' must point to struct/union
    rpy\rinterface\array.c(142) : error C2223: left of '->data' must point to struct/union
    rpy\rinterface\array.c(147) : warning C4022: 'PyCObject_FromVoidPtrAndDesc' : pointer mismatch for actual parameter 1
    error: command '"c:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\bin\cl.exe"' failed with exit status 2

**Comment by paulmueller** [comment]
I would suggest to close this stale issue.

This issue is over 10 years old. Nobody serious about it is working with VC++ 2008 anymore.

**Comment by lgautier** [comment]
VC++ 2008 was the recommended compiler for Python on Windows for quite a while I think. But that was Python 2. Closing.
