### ISSUE TITLE
Incorrect size checking in numpy2ri unsigned integer conversion

### ISSUE THREAD

**Issue by JustBob81** [rpy2/rpy2#355]
Unsigned integer conversion uses **total array memory size** (numpy.ndarray.nbytes) instead of **the size of individual entries** (numpy.ndarray.itemsize) to determine if conversion is possible. This means that a numpy array of uint8, for example, would not be converted to an R integer vector unless it had fewer than 8 values.

I may be misunderstanding the size check, but the bits to byte conversion divides by 4 rather than 8. R's integer limit is 4 bytes (signed), so I believe (RINT_SIZE /4)  below should be (RINT_SIZE/8 - 1). This would exclude 4 byte unsigned numbers greater than 2^31 - 1.

Finally, the current behavior during a pandas conversion is to handle failed conversions by defaulting to converting to strings. In this case, however, converting unsigned integers that are out of range to floats with an appropriate warning would make more sense. This would require changes in the error handling that may or may not be worthwhile, but thought I would raise it here for consideration.

<pre>
def unsignednumpyint_to_rint(intarray):
    """Convert a numpy array of unsigned integers to an R array."""
    if <b>intarray.nbytes</b> >= <b>(RINT_SIZE / 4)</b>:
        raise ValueError(
            'Cannot convert numpy array of unsigned integers '
            'with {RINT_SIZE} bits or more.'.format(RINT_SIZE=RINT_SIZE)
        )
    else:
        res = _numpyarray_to_r(intarray, _kinds['i'])
    return res
</pre>

**Comment by lgautier** [comment]
Yes, the limit should be set to any number greater than 2^31 - 1. The code is trying to find avoid tests for all values though.

You are correct that it should be divided by 8 instead of 4 (since 8 bits per bytes, which makes it 4 bytes). Normally `intarray` has already been tested for signed-ness when it reaches this place (or at list that was the intent from the name of the function and the docstring) so this should be sufficient.

**Comment by lgautier** [comment]
I am less sure about whether to convert to floats would be better because of possible silent loss of precision (and the rather painful troubleshooting of a user code that may result out of it).

I'd rather let a user decide what to with that type of vector and cast as deemed suitable.

**Comment by JustBob81** [comment]
Not doing the float conversion makes sense.

The larger issue is actually how memory size is being checked. Currently the memory size of the entire array is being checked and not the size of individual entries. The uint8 vector below would currently raise the ValueError.

```
x = [1 0 1 1 0 1 0]
x.itemsize = 1
x.nbytes = 7
```

[ndarray.nbytes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.nbytes.html)
Total bytes consumed by the elements of the array.

[ndarray.itemsize](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.itemsize.html)
Length of one array element in bytes.

**Comment by lgautier** [comment]
Yes. I did figure a bit later that I misunderstood what `nbytes` was reporting.

The revision 404c44f11f19a432a781fa6cb3b58c0543f3933d is hopefully solving it for good. I also added unit tests.

**Comment by lgautier** [comment]
And I forget the most important: thanks for the bug report.
