### ISSUE TITLE
Test failing on windows due to improperly escaped path

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#358]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/344) by bugmenot (Bitbucket: [bugmenot](https://bitbucket.org/bugmenot), GitHub: [bugmenot](https://github.com/bugmenot)).**

----------------------------------------

Hey guys,
running "python -m rpy2.tests" on my Windows (8) machine fails on the testInterruptR function in test_EmbeddedR.py, line194 in the latest repo if I saw correctly.

```
#!python

rpy2_path = os.path.dirname(rpy2.__path__[0])
```
results in a string that looks like

```
#!python

sys.path.insert(0, 'C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages')
```
and since there are only single backslashes it is interpreted as escaping. A fix would be to prepend an r to the string in the test code like:

```
#!python

sys.path.insert(0, r'%s')
```
though I'm not sure if this is the best solution.

See also:
[http://stackoverflow.com/a/18084594](Link URL)

(note: I'm posting from an throwaway account.)

**Comment by paulmueller** [comment]
`pytest tests` runs through on Windows 10 without any errors:
- 657 passed
- 116 skipped
- 4 xfailed
- 2 warnings

I did not have pandas installed.

I assume that with the migration to Python3 (or 3.6?), this issue has resolved itself.

**Comment by lgautier** [comment]
Thanks a lot for checking this. Closing.

Note: The requirement is becoming Python >= 3.7 (for now that's only in dev branch though, IIRC).
