### ISSUE TITLE
Build and host the documentation

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#436]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/422) by Laurent Gautier (Bitbucket: [lgautier](https://bitbucket.org/lgautier), GitHub: [lgautier](https://github.com/lgautier)).**

----------------------------------------

The build of the documentation is broken and there does not seem to be a way to fix it. A solution is needed, and it is currently looking like a move away from ReadTheDocs.

**Comment by lgautier** [comment]
There is now a Github workflow to build the doc.

**Comment by flying-sheep** [comment]
Would it be possible to add a way to get a nonfunctional but importable version of rpy2?

Currently, that’s pretty involved and very likely to break. I just mocked out everything I happen to use, it would be better to just have everything be there and not mocked, without actually requiring R to be there.

My setup:

```py
sys.modules["rpy2.rinterface_lib"] = MagicMock()
submods = ["embedded", "conversion", "memorymanagement", "sexp", "bufferprotocol", "callbacks", "_rinterface_capi"]
sys.modules.update({f"rpy2.rinterface_lib.{sub}": MagicMock() for sub in submods})

from rpy2.rinterface_lib import sexp
sexp.Sexp = sexp.SexpVector = sexp.SexpEnvironment = sexp.StrSexpVector = MagicMock
sexp.SexpVector.from_iterable = MagicMock()

import rpy2.rinterface
rpy2.rinterface._MissingArgType = object
```

**Comment by lgautier** [comment]
> Would it be possible to add a way to get a nonfunctional but importable version of rpy2 for things like ReadTheDocs?

Do you mean something that does not dynamically load the R shared library? I don't think that this would be possible
because `rpy2` is designed around being a wrapper for that library.

I think that there are other designs that could allow that. That would require a bit of rewrite though, even if it would probably be mostly restricted to rpy2's "rinterface" level.

> Currently, that’s pretty involved and very likely to break. I just mocked out everything I happen to use, it would be better to just have everything be there and not mocked, without actually requiring R to be there.

Isn't mocking the way people usually modify a codebase to to isolate parts of the code for which the original functionality (or any functionality) is not needed (for example for the purpose of running tests)?
 
> The idea would be to have some global flag (e.g. a env variable) that skips all import-time checks if linking to R worked.

What would be the use-case? Implementing this as flag places on the package maintainer(s) the burden of ensuring that everything is working no matter how and when the flag is changed. A redesign (see sub-comment above) would likely be more reasonable in terms of distributing the responsibility that the code is working, but still would require a use-case that justifies the effort.

**Comment by flying-sheep** [comment]
The use case is that while installing rpy2 is possible in circumstances where R is not available, it’s not possible to actually refer to its objects and their metadata (documentation, module structure, …) that way.

I like to use sphinx extensions like `autosummary` and `sphinx-autodoc-typehints` which end up actually importing those. I use those extensions because docs tend to get outdated fast if one replicates a lot of the structure like where to import what from, or function signatures.

**Comment by lgautier** [comment]
rpy2 is a wrapper for a C library (libR.so). If R is not available, wanting to load rpy2 seems rather niche. What about using the Sphinx extensions autosummary and sphinx-autodoc-typehints on a system where R is installed?

**Comment by flying-sheep** [comment]
I rather want the convenience of having ReadTheDocs build things for me and have it also [run as CI for PRs](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html).

**Comment by lgautier** [comment]
If this is the use-case that motivates asking for the change, and other way to look at this that this is more about a limitation in Readthedocs as a service. Essentially it cannot handle C-extensions Python module wrapping external libraries. rpy2 tried to use Readthedocs in the beginning but I moved away from it because of this very issue.
 
Mocking is what Readthedocs itself presents as a workaround (https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules).

**Comment by flying-sheep** [comment]
Okay! Maybe the better request would then be:

Can we refactor the checks in a way that only a small, well-defined subset of functions, modules, or classes has to be mocked out in order to make rpy2 importable without R being available.

**Comment by flying-sheep** [comment]
This would still be great to have

**Comment by lgautier** [comment]
The documentation is built using Github Actions and hosted on Github Pages.
