### ISSUE TITLE
FutureWarning: from_items is deprecated.

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#509]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/495) by Annette Spooner (Bitbucket: [panda675](https://bitbucket.org/panda675), ).**

----------------------------------------

I just wanted to make sure you are aware that the pandas function 'from_items'  has been deprecated. I am getting the following warning when passing some pandas dataframes to R and displaying their structure:

```
#!python

C:\Users\Annette\Anaconda3\lib\site-packages\rpy2\robjects\pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)
```

It seems to happen when the dataframe has factors or mixed types. Here is an example that reproduces it:

```
#!python

d = {'one' : pd.Series(['cat', 2., 3.], index=['a', 'b', 'c']),
     'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)

%%R -i df
str(df)
```

I am using rpy2 2.9.5, R 3.5.1, Python 3 on WIndows in a Jupyter notebook.
Thanks.

**Comment by drorata** [comment]
FWIW: I just faced the same issue and realized that `conda` installs version 2.9.4 where the problem exists. Trying to install using `pip` ended with something like: `Library not loaded: @rpath/libncurses.6.dylib
  Referenced from: /Users/user/anaconda3/envs/myenv/lib/libreadline.8.dylib`
