### ISSUE TITLE
Latest pandas breaking rpy2 conversion

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#523]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/509) by Laurent Gautier (Bitbucket: [lgautier](https://bitbucket.org/lgautier), GitHub: [lgautier](https://github.com/lgautier)).**

----------------------------------------

The error is:
```
TypeError: Parameter 'categories' must be list-like, was <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x7f101d317fc8> [RTYPES.STRSXP]
```

This seems like what can be argued be a bug (or design issue) on the pandas side, but we need a workaround to keep rpy2 conversion working with pandas.

**Comment by krassowski** [comment]
If anyone needs to install an old project without dependency pins, the last pandas version that is supported on 2.9.x is 0.23.4.
