### ISSUE TITLE
rpy2 build problem on win32

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#61]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/52) by Anonymous.**

----------------------------------------

I have just tried to build rpy2 2.1.3 on win32 with R 2.11.1 using msys and related tools along with mingw32.  I get the following errors:

$ /c/Python26/python setup.py build --r-home /c/R --r-home-lib /c/R install
running build
running build_py
running build_ext
building 'rpy2.rinterface.rinterface' extension
c:\Rtools\mingw\bin\gcc.exe -mno-cygwin -mdll -O -Wall -DWin32=1 -DCSTACK_DEFNS=1 -DRIF_HAS_RSIGHAND=1 -Irpy\rinterface -Ic:\Python26\include -Ic:\Python26\PC -Ic:/R/include -c rpy\rinterface\rinterface.c -o build\temp.win32-2.6\Release\rpy\rinterface\rinterface.o -Lc:/R/bin -lR -Lc:/R/bin -lRlapack -Lc:/R/bin -lRblas
In file included from c:/R/include/R.h:50,
                 from rpy\rinterface\rinterface.c:61:
c:/R/include/R_ext/RS.h:43:1: warning: "ERROR" redefined
In file included from c:\rtools\mingw\bin\../lib/gcc/mingw32/4.2.1-sjlj/../../../../include/windows.h:52,
                 from c:\rtools\mingw\bin\../lib/gcc/mingw32/4.2.1-sjlj/../../../../include/winsock2.h:22,
                 from rpy\rinterface\rinterface.c:58:
c:\rtools\mingw\bin\../lib/gcc/mingw32/4.2.1-sjlj/../../../../include/wingdi.h:313:1: warning: this is the location of the previous definition
In file included from rpy\rinterface\rinterface.c:100:
rpy\rinterface\/na_values.c:146: error: initializer element is not constant
rpy\rinterface\/na_values.c:146: error: (near initialization for 'NAInteger_Type.tp_base')
rpy\rinterface\/na_values.c:316: error: initializer element is not constant
rpy\rinterface\/na_values.c:316: error: (near initialization for 'NALogical_Type.tp_base')
rpy\rinterface\/na_values.c:442: error: initializer element is not constant
rpy\rinterface\/na_values.c:442: error: (near initialization for 'NAReal_Type.tp_base')
rpy\rinterface\/na_values.c:520: error: initializer element is not constant
rpy\rinterface\/na_values.c:520: error: (near initialization for 'NACharacter_Type.tp_base')
In file included from rpy\rinterface\rinterface.c:105:
rpy\rinterface\/sequence.c: In function 'VectorSexp_ass_slice':
rpy\rinterface\/sequence.c:447: warning: unused variable 'sexp_item'
rpy\rinterface\/sequence.c:447: warning: unused variable 'tmp'
rpy\rinterface\/sequence.c:446: warning: unused variable 'vs'
rpy\rinterface\/sequence.c:386: warning: unused variable 'self_typeof'
rpy\rinterface\rinterface.c: In function 'EmbeddedR_init':
rpy\rinterface\rinterface.c:1009: warning: assignment from incompatible pointer type
rpy\rinterface\rinterface.c:1011: warning: assignment from incompatible pointer type
rpy\rinterface\rinterface.c: In function 'EmbeddedR_end':
rpy\rinterface\rinterface.c:1112: warning: unused variable 'str'
error: command 'gcc' failed with exit status 1
  
I started by compiling R from sources with the appropriate –enable-R-shlib option at the configure step.  Everything went smoothly at that level, but I as you can see, I am having trouble with rpy2.  Any insight on the source of the problem?  This compiles perfectly on my Linux box, but I need to build a win32 version to share with some research colleagues.  It looks to me like perhaps the items identified in the following post have not yet been addressed:

http://hg.io/lgautier/rpy2/issue/27/patch-to-fix-build-on-win32

However, the followup postings make it seem otherwise.

Any assistance would be much appreciated.

Thanks.

Dave Louton
dlouton@bryant.edu

**Comment by paulmueller** [comment]
This one of many duplicates. I would like to close it and create a new pinned and locked issue "Windows support" and link to a new project board.

**Comment by lgautier** [comment]
I see how Windows support could be thought of as an issue (e.g., a user would like rpy2 officially supported). But also think that rpy2 does work with Windows, but with limitations. Here the issue was about compiling the C extension. That issue is still mostly present with the API mode (it builds but crashed on import, IIRC) but rpy2 can be imported in ABI mode (IIRC here as well).

Since this issue is about the C-extension, it is fine to close it.
