### ISSUE TITLE
Compile `rpy2` (API mode) on Windows

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#624]
`rpy2` is designed to function in ABI or API mode. Currently neither is working on Windows (see issue #584 ).

The default compilation setup for Python C extensions on Windows should be with MSVC (or so I understand), while R does not reportedly compile at all with MSVC. Any effort toward compiling rpy2 should likely start with setting up an environment that uses for example `mingw` as the C compiler.

**Comment by grayver** [comment]
I've tried to build rpy2 on Windows in API mode with mingw32 compiler and I met following issues:

- Python distutils use MSVC as a default compiler, so I have to specify 'mingw32' compiler explicilty either in setup.py, either via `python setup.py build --compiler=mingw32` command.
- Python distutils Mingw32 compiler wrapper tries to determine msvcrXXX.dll library version based on Python version info. However the latest MSVC version it knows about is 1600, while latest Python version (3.7, 3.8) was compiled with MSVC 1916 version. I had to fix this by adding explicit mapping for this compiler version in distutils code.
- Despite of msvcr120.dll library was in the system path (C:\Windows\System32), compile command wasn't able to find it, so I had to specify it explicitly with option `-LC:/Windows/System32` in setup.py.
- After all of this linker started to throw errors about multiple function declarations:
```
d000027.o:(.idata$5+0x0): multiple definition of `__imp___C_specific_handler'
d000024.o:(.idata$5+0x0): first defined here
d000057.o:(.idata$5+0x0): multiple definition of `__imp___iob_func'
d000031.o:(.idata$5+0x0): first defined here
d000057.o:(.idata$6+0x0): multiple definition of `__nm___iob_func'
d000031.o:(.idata$6+0x0): first defined here
d000058.o:(.idata$5+0x0): multiple definition of `__imp___setusermatherr'
d000034.o:(.idata$5+0x0): first defined here
d000058.o:(.idata$6+0x0): multiple definition of `__nm___setusermatherr'
d000034.o:(.idata$6+0x0): first defined here
```
and I have to add option `-Wl,-allow-multiple-definition` in setup.py
- Next I discovered, that compiler can't find file 'sys/select.h' included in 'R_API_eventloop.h' for importing fd_set type. Googling helped me to understand, that 'sys/select.h' exists only on Linux, and on Windows I should use 'winsock2.h' instead. So, I fixed 'R_API_eventloop.h' file.
- Then I met errors connected with undefined macro variable 'OSNAME_NT' and I had to define it explicitly.
- Finally I've got stuck with following error:
```
build\temp.win-amd64-3.7\Release\_rinterface_cffi_api.c:7787:21: error: 'structRstart' has no member named 'WriteConsoleA'
   { "WriteConsole", offsetof(structRstart, WriteConsole),
                     ^
build\temp.win-amd64-3.7\Release\_rinterface_cffi_api.c:7788:47: error: 'structRstart' has no member named 'WriteConsoleA'
                     sizeof(((structRstart *)0)->WriteConsole),
```
and currently I have no idea how to fix this :(

Probably, I will try to use MSVC compiler.

**Comment by grayver** [comment]
Finally I've got rpy2 compiled in CFFI API mode with MSVC compiler. I made a lot of fixes in R header files and build script. Interesting point, that MSVC had the same error as mingw32 (`error: 'structRstart' has no member named 'WriteConsoleA'`). The cause of problem was in the Windows macros defined in one of headers:
```
#ifdef UNICODE
#define WriteConsole  WriteConsoleW
#else
#define WriteConsole  WriteConsoleA
#endif // !UNICODE

#ifdef UNICODE
#define ReadConsole  ReadConsoleW
#else
#define ReadConsole  ReadConsoleA
#endif // !UNICODE
```

But now Python crashes in the very beginning of Python script. So I will try to investigate it.

**Comment by CristiFati** [comment]
I too ran into the same issues (and many more), and fixed them. So far, I'm stuck with:
```
c:\Install\pc032\Microsoft\VisualStudioCommunity\2019\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:e:\Work\Dev\CristiFati\Builds\Win\RPy2\src /LIBPATH:c:\Install\pc064\Python\Python\03.07.06\Libs /LIBPATH:e:\Work\Dev\VEnvs\py_pc064_03.07.06_test0\libs /LIBPATH:e:\Work\Dev\VEnvs\py_pc064_03.07.06_test0\PCbuild\amd64 /LIBPATH:c:\Install\pc032\Microsoft\VisualStudioCommunity\2019\VC\Tools\MSVC\14.25.28610\ATLMFC\lib\x64 /LIBPATH:c:\Install\pc032\Microsoft\VisualStudioCommunity\2019\VC\Tools\MSVC\14.25.28610\lib\x64 "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" R-3.6.3-pc064.lib /EXPORT:PyInit__rinterface_cffi_api build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_rinterface_cffi_api.obj /OUT:build\lib.win-amd64-3.7\_rinterface_cffi_api.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_rinterface_cffi_api.cp37-win_amd64.lib
   Creating library build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_rinterface_cffi_api.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\build\temp.win-amd64-3.7\Release\_rinterface_cffi_api.cp37-win_amd64.exp
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol R_checkActivity
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol getInputHandler
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol R_SetWin32
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ClearerrConsole
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_savehistory
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol R_InputHandlers
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ChooseFile
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ReadConsole
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol GA_initapp
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol R_PolledEvents
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol editorcleanall
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_CleanUp
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol R_runHandlers
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_Busy
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_loadhistory
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol GA_appcleanup
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_FlushConsole
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_do_dataviewer
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol addInputHandler
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ProcessEvents
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol removeInputHandler
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_WriteConsoleEx
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol initStdinHandler
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ShowMessage
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_do_dataentry
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_addhistory
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol R_wait_usec
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ResetConsole
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_do_selectlist
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_WriteConsole
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_ShowFiles
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_EditFiles
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_EditFile
_rinterface_cffi_api.obj : error LNK2001: unresolved external symbol ptr_R_Suicide
build\lib.win-amd64-3.7\_rinterface_cffi_api.cp37-win_amd64.pyd : fatal error LNK1120: 34 unresolved externals
```

Some of them are  local but some of them are from *R.dll* (at least, they are exported on *Nix*).

**Comment by grayver** [comment]
Yep, I got them too. I believe, that ptr_R_* symbols are UNIX-way to set callbacks, while on Windows they are set up via `struct Rstart` (with less callback options though). So, I tried to comment all those symbols out. Probably, if they are not exported from R.dll, they are not supported on Windows.

However, my compiled rpy2 version is crashing now and I will try to investigate it.

**Comment by lgautier** [comment]
In the list of unresolved symbols on Windows from 2 comments ago there is `R_SetWin32`. I would have expected this to be Windows-specific.

**Comment by grayver** [comment]
> In the list of unresolved symbols on Windows from 2 comments ago there is `R_SetWin32`. I would have expected this to be Windows-specific.

However, this symbol is not exported in R.dll :(

**Comment by lgautier** [comment]
I just checked the R source and oddly `R_SetWin32` appears defined for all platforms. It is in `include/R_ext/RStartup.h`.

However, it is further listed in the file `src/gnuwin32/Rdll.hide`, which make it unavailable to users of R.dll.

**Comment by OnlyBelter** [comment]
Please support Windows officially!

**Comment by lgautier** [comment]
A dev version with windows binary wheels should install with: 
```sh
pip install -U --pre rpy2
```
