### ISSUE TITLE
readthedocs /stable/ seem to not have an objects.inv for intersphinx.

### ISSUE THREAD

**Issue by Carreau** [rpy2/rpy2#625]
/latest/ have it. 

FOr whatever reason IPython was trying to get it from `https://rpy2.readthedocs.io/en/version_2.8.x/`, which is gone, so I tried to update to /stable/; which does not have  objects.inv, but latest seem to have it. 

/latest/ is fine for me; but just letting you know. Feel free to close if that's expected or low priority.

**Comment by lgautier** [comment]
Thanks for the report. See issue #436 .

Documentation building on readthedocs is broken. It is has been so for quite a while, and I have pondering taking the readthedocs versions down. In the meantime the docs are (manually) built here:  https://rpy2.github.io/index_doc.html

**Comment by lgautier** [comment]
The readthedoc pages are now deleted. It was impossible to build and the old doc versions were causing too much confusion by bubbling to the top of Google search results.
