### ISSUE TITLE
Insalling rpy2 on Red Hat linux 7.5 with no internet

### ISSUE THREAD

**Issue by MrPhilosopher** [rpy2/rpy2#629]
I'm trying to install rpy2 on redhat linux 7.5 with no internet connection but haven't yet succeeded.

I've tried two methods

**Method #1**

1. Downloaded rpy2 (conda distribution) library from https://anaconda.org/r/rpy2/2.9.4/download/linux-64/rpy2-2.9.4-py37r36h481b005_0.tar.bz2
2. Run `conda install rpy2-2.9.4-py37r36h481b005_0.tar.bz2`
Output:

```
Preparing transaction: done
Verifying transaction: done  
Executing transaction: done
```
But it's still not installed; when I check by importing rpy2, it still gave me the error of module not found

**Method #2**

Downloaded rpy2 (pip distribution) from https://pypi.org/project/rpy2/#files
Run `pip install rpy2-3.2.4.tar.gz`
Output:

```
Processing ./rpy2-3.2.4.tar.gz
Complete output from command python setup.py egg_info:
There is no R_HOME and the R executable cannot be found.
```
**Can anyone please help me in getting rpy2 install successfully?**

**Comment by lgautier** [comment]
This seems like either a conda packaging issue (in which case conda lists/support will better be able to answer), or an operator error (rpy2 does need R installed, and the easiest is to have it in the PATH).
