### ISSUE TITLE
errors when trying to import specific parts of rpy2

### ISSUE THREAD

**Issue by zbrasseaux** [rpy2/rpy2#630]
I am trying to do what I believe is essentially the hello world for rpy2, with the following code: 
```python
from rpy2.robjects.packages import importr
import rpy2.robjects as ro
import pandas.rpy.common as com
import rpy2

test = ro.r('./return_string.r')

print(rpy2.__version__)
```
The errors are output here:
[wrap_it.err.txt](https://github.com/rpy2/rpy2/files/4100506/wrap_it.err.txt)

I'm on Linux Mint 18.2, Python version 3.7, rpy2 version 3.3.0.dev

**Comment by lgautier** [comment]
`'./return_string.r'` is not a string that contains R source code. It is the (relative) path to file that likely contains R code (from the `.r` extension).

Read the content of that file as a string, and then call `ro.r()` on that string.
