### ISSUE TITLE
Cannot import rpy2.rinterface

### ISSUE THREAD

**Issue by imk1** [rpy2/rpy2#642]
When I try to import rpy2.rinterface, I get the following error:
ImportError: libtre.so.5: cannot open shared object file: No such file or directory
I tried this with R versions 3.3.1 and 3.6.0 and got the same error both times.  I am using rpy2 version 2.8.5.  The end of my LD_LIBRARY_PATH is /opt/packages/R/3.3.1-mkl/lib64/R/lib (I switched it to 3.6.0 when trying R version 3.6.0).  I also ran "pip install libtree" before importing rpy2.rinterface.
Thanks so much!

**Comment by lgautier** [comment]
`LD_LIBRARY_PATH` should match the R version with which you installed rpy2.

Otherwise, rpy2-2.8.5 is quite old. You should really try to upgrade to the current release.

**Comment by lgautier** [comment]
This is a dynamic linking issue. Since no further comment, setting `LD_LIBRARY_PATH` has presumably solved the issue. The next rpy2 release (3.5.0) will fetch the search path for the linker from the R executable by default (which should make this kind of issue report less frequent).
