### ISSUE TITLE
pip install error on GCP virtual machine

### ISSUE THREAD

**Issue by YvesJacquot** [rpy2/rpy2#648]
Hi

I am trying to install rpy2 on a GCP virtual machine but without any success so far.
*setuptools version is 45.2.0.*
*Python 2.7.13.*
`sudo pip install rpy2` produces the following error message.
I saw there has been a few issues related to this already posted, but I haven't found the solution yet. 
Any help would be greatly appreciated.

>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-em95meem/rpy2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-em95meem/rpy2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-em95meem/rpy2/pip-egg-info
>          cwd: /tmp/pip-install-em95meem/rpy2/
>     Complete output (26 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-em95meem/rpy2/setup.py", line 183, in <module>
>         'rinterface_lib/R_API_eventloop.h']}
>       File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 144, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 448, in __init__
>         k: v for k, v in attrs.items()
>       File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
>         self.finalize_options()
>       File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 740, in finalize_options
>         ep.load()(self)
>       File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
>         ep.load()(self, ep.name, value)
>       File "/tmp/pip-install-em95meem/rpy2/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
>         add_cffi_module(dist, cffi_module)
>       File "/tmp/pip-install-em95meem/rpy2/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
>         execfile(build_file_name, mod_vars)
>       File "/tmp/pip-install-em95meem/rpy2/.eggs/cffi-1.14.0-py3.5-linux-x86_64.egg/cffi/setuptools_ext.py", line 24, in execfile
>         code = compile(src, filename, 'exec')
>       File "rpy2/_rinterface_cffi_build.py", line 127
>         """,
>           ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
>  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Thank you

**Comment by lgautier** [comment]
rpy2 dropped support for Python 2 yeeeeeeaaaaars ago. Use Python >= 3.5 (preferably >= 3.6).

**Comment by YvesJacquot** [comment]
There was a typo, sorry. I do use Python 3. 
Can you see any obvious issue?
Many thanks
