### ISSUE TITLE
Include essentials in base module as prelude

### ISSUE THREAD

**Issue by buckle2000** [rpy2/rpy2#651]
Importing essential functions into the base/root module is a common practice in Python. For example, `pandas.DataFrame` is from `pandas.core.frame.DataFrame`.

I wish the following line would work.
```
from rpy2 import importr
```

Also, the above example should also enable converters if possible. For example:

```
try:
    __import__('numpy')
    __import__('rpy2.robjects.numpy2ri', fromlist=('activate',)).activate()
except ModuleNotFoundError:
    pass
```

**Comment by lgautier** [comment]
This is currently no something considered. rpy2 binds to a C library (libR) that can be initialized in several possible ways, and moving `importr` to the top level `rpy2` would break this. Beside this, connectivity with `numpy` is made optional on purpose.

However, it is really easy to write your own module that imports all what you want from rpy2.
