### ISSUE TITLE
Keeping column names unchanged when importing DataFrame from Python to R

### ISSUE THREAD

**Issue by krassowski** [rpy2/rpy2#660]
Currently, the column names containing spaces, special characters, or starting from a digit are automatically converted to [syntactically valid names](https://stat.ethz.ch/R-manual/R-devel/library/base/html/make.names.html). This behaviour was the default for quite a while, and I do not want to challenge it, as indeed there are some benefits to having column names which can be used as valid variable names as well (i.e. when specifying a model).

For example, this pandas DataFrame:

```python
from pandas import DataFrame
df = DataFrame([[1, 2, 3]], columns=['1st', 'second column', "third's a charm"])
df
```

1st | second column | third's a charm
-- | -- | --
1 | 2 | 3

is converted to:

```python
%R -i df
%R df
```

X1st | second.column | third.s.a.charm
-- | -- | --
1 | 2 | 3

However, oftentimes I find this counterproductive and destructive. The converters system allows for a workaround:

```python
import warnings
from collections import OrderedDict
from pandas.core.frame import DataFrame as PandasDataFrame

from rpy2.robjects.vectors import DataFrame, StrVector
from rpy2.robjects import pandas2ri, numpy2ri, default_converter
from rpy2.robjects.conversion import Converter, py2rpy
import rpy2.robjects.conversion as conversion

data_frame_converter = Converter('Pandas converter preserving names')

@data_frame_converter.py2rpy.register(PandasDataFrame)
def py2rpy_pandasdataframe(obj):
    od = OrderedDict()
    for name, values in obj.iteritems():

        try:
            od[name] = conversion.py2rpy(values)
        except Exception as e:
            warnings.warn('Error while trying to convert '
                          'the column "%s". Fall back to string conversion. '
                          'The error is: %s'
                          % (name, str(e)))
            od[name] = StrVector(values)

    df = DataFrame(od)
    df.colnames = obj.columns
    return df

converter = default_converter + numpy2ri.converter + pandas2ri.converter + data_frame_converter
```

```python
%R -i df -c converter
%R df
```
1st | second column | third's a charm
-- | -- | --
1 | 2 | 3

Which is quite verbose. **Only one line of code was added:**

```python
df.colnames = obj.columns
```

Why I am opening this issue:
 - to show others how to work around the problem
 - to ask if there is a better solution which could be implemented, e.g. could we have a pre-defined Pandas converter which would take arguments (such as `convert_colnames=False`). Something like:
```python
converter = default_converter + pandas2ri.create_converter(convert_colnames=False)
```
or maybe `pandas2ri.Converter(convert_colnames=False)`.

Another use of such a converter would be to specify a custom series fallback conversion method.

**Comment by lgautier** [comment]
It makes sense.

The underlying R constructor has a parameter `check.names` (default to `TRUE`) that indicates whether column names should be changed to syntactically valid column names. That parameter should be exposed in the constructor for the rpy2 object `DataFrame`.

The idea of having parametric constructor for converters is a promising one, but in the meantime the case can be made that, for the conversion to `pandas`, the column names left unchanged should be the default behaviour.

**Comment by lgautier** [comment]
Fixed.
