### ISSUE TITLE
methods.so: undefined symbol: ALTREP_LENGTH

### ISSUE THREAD

**Issue by friedpine** [rpy2/rpy2#661]
I installed the rpy2 using:
`pip install git+https://github.com/rpy2/rpy2.git`

While trying to load "import rpy2.robjects as robjects", I meet errors:

`Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  /usr/local/lib/R/library/methods/libs/methods.so: undefined symbol: ALTREP_LENGTH
Warning message:
package "methods" in options("defaultPackages") was not found 
Error: package or namespace load failed for ‘utils’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/utils/libs/utils.so':
  /usr/local/lib/R/library/utils/libs/utils.so: undefined symbol: ALTREP_LENGTH
Error: package or namespace load failed for ‘grDevices’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib/R/library/grDevices/libs/grDevices.so: undefined symbol: ALTREP_LENGTH
Error: package or namespace load failed for ‘graphics’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib/R/library/grDevices/libs/grDevices.so: undefined symbol: ALTREP_LENGTH
Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/grDevices/libs/grDevices.so':
  /usr/local/lib/R/library/grDevices/libs/grDevices.so: undefined symbol: ALTREP_LENGTH
Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  /usr/local/lib/R/library/methods/libs/methods.so: undefined symbol: ALTREP_LENGTH
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘grDevices’ in options("defaultPackages") was not found 
3: package ‘graphics’ in options("defaultPackages") was not found 
4: package ‘stats’ in options("defaultPackages") was not found 
5: package ‘methods’ in options("defaultPackages") was not found 
R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  /usr/local/lib/R/library/methods/libs/methods.so: undefined symbol: ALTREP_LENGTH

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/usr/local/lib/python3.5/dist-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/usr/local/lib/python3.5/dist-packages/rpy2/robjects/robject.py", line 70, in RObjectMixin
    __show = _get_exported_value('methods', 'show')
  File "/usr/local/lib/python3.5/dist-packages/rpy2/rinterface_lib/conversion.py", line 40, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rpy2/rinterface.py", line 791, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  /usr/local/lib/R/library/methods/libs/methods.so: undefined symbol: ALTREP_LENGTH
`

The R version is `R version 3.5.1 (2018-07-02) -- "Feather Spray"`.

Desperate to get help!

**Comment by lgautier** [comment]
Updating to R >= 3.6.0 would solve your issue. Or use an older rpy2 release.

**Comment by lgautier** [comment]
R-3.5 is no longer supported. Closing the issue.

**Comment by duocang** [comment]
Hi.

I still met this issue with R 4.0+ and new/old py2.

```
ile ~/anaconda3/envs/new_base/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py:45, in _cdata_res_to_rinterface.<locals>._(*args, **kwargs)
     44 def _(*args, **kwargs):
---> 45     cdata = function(*args, **kwargs)
     46     # TODO: test cdata is of the expected CType
     47     return _cdata_to_rinterface(cdata)


--> 680         raise embedded.RRuntimeError(_rinterface._geterrmessage())
    681 return res

RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib64/R/library/methods/libs/methods.so':
```

**Comment by wJDKnight** [comment]
same

> RRuntimeError:` Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/opt/R/3.6.3/lib/R/library/methods/libs/methods.so':
libR.so: cannot open shared object file: No such file or directory

I've checked that '/opt/R/3.6.3/lib/R/library/methods/libs/methods.so' exists. I have tried to set directories of R library. And here is the output of%run -m rpy2.situation

> rpy2 version:
3.4.2
Python version:
3.8.13 (default, Oct 21 2022, 23:50:54)
[GCC 11.2.0]
Looking for R's HOME:
Environment variable R_HOME: /opt/R/3.6.3/
Calling R RHOME: /opt/R/3.6.3/lib/R
Environment variable R_LIBS_USER: /opt/R/3.6.3/lib/R/library
Warning: The environment variable R_HOME differs from the default R in the PATH.
R's additions to LD_LIBRARY_PATH:
:/opt/R/3.6.3/lib/R/library/methods/libs:/opt/R/3.6.3/lib/R/library/
R version:
In the PATH: R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
include:
['/opt/R/3.6.3/lib/R/include']
libraries:
['R', 'pcre2-8', 'pcre', 'lzma', 'bz2', 'z', 'tirpc', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
library_dirs:
['/usr/local/lib', '/opt/R/3.6.3/lib/R/lib']
extra_compile_args:
[]
extra_link_args:
['-Wl,--export-dynamic', '-fopenmp']

**Comment by lgautier** [comment]
Did you try setting `LD_LIBRARY_PATH`? (see https://github.com/rpy2/rpy2#non-system-r-installations)
