### ISSUE TITLE
Update links to the rpy2 source

### ISSUE THREAD

**Issue by timokau** [rpy2/rpy2#662]
If I search for `rpy2` on google right now, the first three links I get are
- https://rpy2.readthedocs.io/en/latest/
- https://pypi.org/project/rpy2/
- https://rpy2.bitbucket.io/

The first two still link to the bitbucket repository. The third is the bitbucket repository itself. It might be helpful to update those links and add a move notice to the rpy2 repository.

This is similar to https://github.com/rpy2/rpy2/issues/261 from the previous move.

**Comment by lgautier** [comment]
Thanks. I had missed the second one (the URL is fixed in `master` but wasn't in the branch `v3.2.x`.

For readthedoc, I have considered just deleting all pages but so far thought that they might be missed by people still using an older rpy2 release.

**Comment by timokau** [comment]
Thanks for fixing the pypi one already. Is there a reason you're not using readthedoc anymore for recent releases?

**Comment by lgautier** [comment]
Building the doc requires, R and additional packages, and compile a C extension (optional now). This couldn't be achieved on readthedoc.

**Comment by timokau** [comment]
Ah, makes sense. That's a shame.

**Comment by lgautier** [comment]
I deleted the bitbucket page. I will look at at whether I could upload built doc to readthedoc.

**Comment by lgautier** [comment]
I also deleted the readthedoc page (all versions there are completely outdated)

**Comment by timokau** [comment]
Thank you!
