### ISSUE TITLE
Cannot convert a DataFrame with string columns if they contain NaNs

### ISSUE THREAD

**Issue by krassowski** [rpy2/rpy2#668]
The pandas to R converter handles missing values represented with `None` in a Series of numbers:

```python
from pandas import Series
numeric = Series([1, None])
%R -i numeric
```

or strings:

```python
from pandas import Series
characters = Series(['a', None])
%R -i characters
```

However, it fails badly when the representation uses numpy's `nan`, which is the default representation that we will get when reading a data frame from a file, or after inferring types:

```python
from numpy import nan
characters_nan = Series(['a', nan])
%R -i characters_nan    # raises ValueError
```

Raising:

```python
~/.pyenv/versions/3.8.1/envs/<redacted>/lib/python3.8/site-packages/rpy2/robjects/pandas2ri.py in py2rpy_pandasseries(obj)
    124                 continue
    125             if type(x) is not homogeneous_type:
--> 126                 raise ValueError('Series can only be of one type, or None.')
    127         # TODO: Could this be merged with obj.type.name == 'O' case above ?
    128         res = {

ValueError: Series can only be of one type, or None.
```

I very often run into this issue, because as I mentioned, `nan` is the way the missing values are stored in pandas by default. I once answered a related question at [SO](https://stackoverflow.com/a/60197946/6646912).

Workaround: replace NaNs with `None`:

```python
characters_nan_as_None = Series(['a', nan]).replace({nan: None})
%R -i characters_nan_as_None   # works ok
```

However, in a DataFrame, it is not enough:

```python
df = DataFrame([{'col1': 'a', 'col2': 1}, {'col1': nan, 'col2': nan}])
df = df.replace({nan: None})
%R -i df    # raises ValueError
```
we now also need to add `infer_objects()`

```python
df = DataFrame([{'col1': 'a', 'col2': 1}, {'col1': nan, 'col2': nan}])
df = df.replace({nan: None}).infer_objects()
%R -i df    # works ok
```

**Question**: Could we consider adding the two steps (replace nans and infer_objects) into the converter itself to streamline the user experience?

**Comment by lgautier** [comment]
I see your point.

R is making a distinction between 'NaN` and `NA` for decimal values (doubles) whereas numpy used `nan` to express both.

While I believe that `None` is unequivocally representing the notion of `NA`, I can also see it that there is no possible ambiguity for `Series` of strings and it should accept `nan`.

**Comment by lgautier** [comment]
Fixed. Will be in release 3.3.0.

**Comment by krassowski** [comment]
Thank you for a quick fix. I've just upgrade to 3.3.1 in another project and found it does not in some cases:

```python
from pandas import Series
from numpy import nan
```

This works ok:

```python
characters_nan = Series(['a', nan])
%R -i characters_nan
```

This raises an exception:

```python
nan_characters = Series([nan, 'a'])
%R -i nan_characters    # raises ValueError
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-108-35ae5e90c024> in <module>
      1 nan_characters = Series([nan, 'a'])
----> 2 get_ipython().run_line_magic('R', '-i nan_characters    # raises ValueError')

-/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

-/site-packages/decorator.py:decorator-gen-133> in R(self, line, cell, local_ns)

-/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

-/site-packages/rpy2/ipython/rmagic.py in R(self, line, cell, local_ns)
    735                         raise NameError("name '%s' is not defined" % input)
    736                 with localconverter(converter) as cv:
--> 737                     ro.r.assign(input, val)
    738 
    739         if args.display:

-/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    195                 v = kwargs.pop(k)
    196                 kwargs[r_k] = v
--> 197         return (super(SignatureTranslatedFunction, self)
    198                 .__call__(*args, **kwargs))
    199 

-/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
    115 
    116     def __call__(self, *args, **kwargs):
--> 117         new_args = [conversion.py2rpy(a) for a in args]
    118         new_kwargs = {}
    119         for k, v in kwargs.items():

-/site-packages/rpy2/robjects/functions.py in <listcomp>(.0)
    115 
    116     def __call__(self, *args, **kwargs):
--> 117         new_args = [conversion.py2rpy(a) for a in args]
    118         new_kwargs = {}
    119         for k, v in kwargs.items():

-/functools.py in wrapper(*args, **kw)
    872                             '1 positional argument')
    873 
--> 874         return dispatch(args[0].__class__)(*args, **kw)
    875 
    876     funcname = getattr(func, '__name__', 'singledispatch function')

-/site-packages/rpy2/robjects/pandas2ri.py in py2rpy_pandasseries(obj)
    180                 ((isinstance(x, float) and math.isnan(x))
    181                  or x is pandas.NA)):
--> 182                 raise ValueError('Series can only be of one type, or None '
    183                                  '(and here we have %s and %s).' %
    184                                  (homogeneous_type, type(x)))

ValueError: Series can only be of one type, or None (and here we have <class 'float'> and <class 'str'>).
```

PS. I also rejoiced on the sight of the improved ValueError message :)

Versions:
```
pandas: 1.0.3
rpy2: 3.3.1
R: 3.6.3
Python 3.8.1
```

**Comment by lgautier** [comment]
That error is expected. Not to say that this is perfect, but the intent is to raise an error.

This is what is currently happening:
- a `pandas` `Series` such as this one without a `dtype` specified will have it set to "O" (essentially like a Python sequence with items of any possible type).
- When the `dtype` is "O", the rpy2 converter will inspect all items to assess whether they are all of the same type. `None` is handled specially, in the sense that its type does count when checking the homogeneity of types (the code is here: https://github.com/rpy2/rpy2/blob/master/rpy2/robjects/pandas2ri.py#L170)

So a question might be "why not treat `nan` like `None` ? The initial issue I had with that is that `nan` is a float, and means `NaN` (Not a Number) in R. For example, what if I have a Series like `[1, 2, nan, 4, None]` ? The Series should arguably convert to an R vector of floats, with only the last value a missing value.

An other question might be "why not make a best-guess matching R type from the types of the items in the `Series` ? I initially considered this, but this opens the door to inconsistency/type unpredictability issues. For example:

```python
characters_nan = Series(['a', nan])
%R -i characters_nan
# characters_nan will be an R vector of strings
```

```python
characters_nan = Series([nan, nan])
%R -i characters_nan
# characters_nan will be an R vector of what type ?
```

Currently, the way to address the issue you have it to specify the `dtype` (for example to `pandas.StringDtype()`).

May be I am missing something, or there is a better way. Let me know.
