### ISSUE TITLE
 libRblas.so: cannot open shared object file....but it's there??

### ISSUE THREAD

**Issue by brobr** [rpy2/rpy2#675]
Hi,
On my Slackware64-current box R-3.6.3 is built as shared libraries
These are located here:
>bash-5.0$ ls -l /usr/lib64/R/lib
total 5400
-rwxr-xr-x 1 root root 3416864 Apr  7 02:37 libR.so
-rwxr-xr-x 1 root root  178080 Apr  7 02:37 libRblas.so
-rwxr-xr-x 1 root root 1926864 Apr  7 02:37 libRlapack.so

still, within the rpy2-3.2.7 source folder `python3 setup.py build --help`
produces this:
>bash-5.0$ python3 setup.py build --help
/usr/bin/ld: warning: libRblas.so, needed by /usr/lib64/R/lib/libR.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `zgemm_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `daxpy_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dgemv_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dscal_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dnrm2_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dgemm_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dtrsm_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dcopy_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dsyrk_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dasum_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `ddot_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `drotg_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `drot_'
/usr/bin/ld: /usr/lib64/R/lib/libR.so: undefined reference to `dswap_'
collect2: error: ld returned 1 exit status

In order to create a package that can be distributed; istallation of rpy2 goes via a buildscript that uses `python3 setup.py install --root=$PKG`
After installation of the built package, I need to start my terminal with
`export LD_LIBRARY_PATH=/usr/lib64/R/lib/`
before starting python3
>\>>> import rpy2.
\>>> import rpy2.robjects
\>>> import rpy2.rinterface

then that will work; otherwise (without the export call):
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/site-packages/rpy2/robjects/__init__.py", line 14, in <module>
    import rpy2.rinterface as rinterface
  File "/usr/lib64/python3.8/site-packages/rpy2/rinterface.py", line 6, in <module>
    from rpy2.rinterface_lib import openrlib
  File "/usr/lib64/python3.8/site-packages/rpy2/rinterface_lib/openrlib.py", line 43, in <module>
    rlib = _dlopen_rlib(R_HOME)
  File "/usr/lib64/python3.8/site-packages/rpy2/rinterface_lib/openrlib.py", line 36, in _dlopen_rlib
    rlib = ffi.dlopen(lib_path)
OSError: cannot load library '/usr/lib64/R/lib/libR.so': libRblas.so: cannot open shared object file: No such file or directory

How come? I do not understand what is going wrong during building/installation of the package.

BTW on Slackware `echo LD_LIBRARY_PATH` does not normally produce a library path
BLAS comes from Openblas

**Comment by brobr** [comment]
When I just run some of the code in rpy2/rpyinterface_lib:
>bash-5.0$ python3
Python 3.8.2 (default, Feb 27 2020, 19:54:55) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import platform
\>>> import threading
\>>> import rpy2.situation
\>>> R_HOME = rpy2.situation.get_r_home()
\>>> R_HOME
'/usr/lib64/R'
\>>> exit()

And this is without `export LD_LIBRARY_PATH=/usr/lib64/R/lib/` beforehand.
>bash-5.0$ echo $LD_LIBRARY_PATH
>
>bash-5.0$ 
So the path is found OK, and the 'lib' is attached in rpy2.situation:
>def get_rlib_path(r_home: str, system: str) -> str:
    """Get the path for the R shared library."""
    if system == 'Linux':
        lib_path = os.path.join(r_home, 'lib', 'libR.so')
...

But where gets  libRblas.so included? This is sought for according to the raised error....


PS rpy2 is complaining about pandas-1:

**Comment by lgautier** [comment]
`R` in (I guess) `/usr/bin/R` is shell script that sets few environment variables before starting the R binary. Depending on how R was installed, `LD_LIBRARY_PATH` might be required prior to starting Python in order for the linker to find R shared libraries at run time.

Here the path of your R installation seems quite standard. May be there is something missing from the way it was packaged ?

**Comment by brobr** [comment]
Thanks for the feedback (and the rpy2 program of course), 

It is a vanilla install of R (see below for how its compilation was configured). The command `R RHOME` yields the correct path, `/usr/lib64/R`

[ A post on stackoverflow](https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux) pointed out the solution: 
create a file in `/etc/ld.so.conf.d/`, say `/etc/Rlib.conf` (only the '.conf' extension is important) with as content `/usr/lib64/R/lib` followed by `sudo ldconfig`. 

After that, when R import bottled up earlier, in the same python session the next `import rpy2.robjects` call works.

Now I can test how stuff gets passed between python and R via rpy2, fabulous..;-)



R is built with:
>./configure \
  --prefix=/usr \
  --libdir=/usr/lib64 \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  rdocdir=/usr/doc/R-3.6.3 \
  --enable-R-shlib \
  --enable-BLAS-shlib \
  --build=$ARCH-slackware-linux
>
>make
make install DESTDIR=$PKG
make install-tests DESTDIR=$PKG

**Comment by lgautier** [comment]
I forgot to mention that compatibility with pandas >= 1.0 is currently in `master` (and will be in rpy2-3.3.0 when released, which I hope to be soon).

**Comment by brobr** [comment]
Even better! Thanks a lot.

**Comment by brobr** [comment]
Hi Laurent,
The documentation on [https://rpy2.github.io/doc/latest/html/overview.html#source-archive](url)
mentions build options for setup.py. When tested, like this:
>python3 setup.py  build --r-home-lib=/usr/lib64/R/lib

the same ld-output as above is produced, but with the extra bit
>usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
>
>error: option --r-home-lib not recognized

(or in another try: `error: option --r-home not recognized`)
Did I set this option incorrectly or is the documentation no longer accurate in this respect?

**Comment by lgautier** [comment]
It looks like the doc is no longer accurate.

The easiest it to have the R you want to build against in your `PATH`. There is also an option to set the env variable `R_HOME`, but I have not tested it in ages (and this is not covered by the continuous tests at the moment). Setting up `LD_LIBRARY_PATH` will still be needed though (if the linker doesn't know where to find the R shared libraries).

With rpy2-3.3.0 (to be released soon, currently in `master`), there is a utility to help set up `LD_LIBRARY_PATH`. Try:
```bash 
python -m rpy2.situation LD_LIBRARY_PATH
```

**Comment by lgautier** [comment]
The doc was fixed with a7b3a50a8784bf3a1a2bef03ed6bd684f3a6039c

**Comment by brobr** [comment]
Thanks for the update; it was more about the outdated doc than anything else; the above solution with a simple conf file in `/etc/ld.so.conf.d/` bypasses all hassle of setting up a python-environment (ipython, jupyter etc) that knows where R is, so will stick to that ;-)

**Comment by brobr** [comment]
I have submitted a slackbuild for rpy2 to SlackBuilds.org (as a user of python and R; and not so much as a developer). Taking other slackbuilds as an example, rpy2 could be built without the above warnings by putting an export `LD_LIBRARY_PATH` before the `python setup.py build` instruction:

>if ! [ -x "$(command -v R)" ]; then
  echo 'Error: R is not installed.' >&2
  exit 1
fi
RHOMLIB=$(R RHOME)/lib
echo "R libs are in $RHOMLIB"
if ! [ "$(readelf -h $RHOMLIB/libR*.so | grep DYN)" ]; then
  echo 'Error: R is not compiled with shared libraries in $RHOMLIB.' >&2  
  exit 1
fi
>
>export LD_LIBRARY_PATH="${RHOMLIB}:${LD_LIBRARY_PATH}"
echo "LD_LIBRARY_PATH set to ${LD_LIBRARY_PATH}"

and this runs nicely:
>..
rpy2-3.2.7/NEWS
R libs are in /usr/lib64/R/lib
LD_LIBRARY_PATH set to /usr/lib64/R/lib:
running build
running build_py


After installing the package, that file in /etc/ld.so.conf.d/ is still needed to make rpy2 work. 

Thus building rpy2 can be done independently of the shared libs being found? Is this because of the way setup.py works when not going via the pip-install route?

**Comment by lgautier** [comment]
Thanks for the suggestion to test whether R was built with a shared library. This used to be a source of many spurious issue reports, and while it no longer seems the case I should still add it.

Whether settting `LD_LIBRARY_PATH` is needed or not depends solely on how R was installed, and if the R shared library/libraries can be found by the linker.

For example, this is the way binary builds are made in CI (no `LD_LIBRARY_PATH`):
https://github.com/rpy2/rpy2/blob/master/.github/workflows/pythonpublish.yml#L42

If setting it is needed, `rpy2.situation` can help: 
https://github.com/rpy2/rpy2/blob/master/.github/workflows/sphinx-doc.yml#L31

> Thus building rpy2 can be done independently of the shared libs being found? Is this because of the way setup.py works when not going via the pip-install route?

I am not sure that I fully understand the questions.

rpy2 can be installed in ABI or in API mode. The ABI mode is meant to be fallback mode for when the API mode can be built (C compilation needed). 

Otherwise, yes. A different R library than the one used to build/install rpy2 can be used. It will work, at least as long they there are no API-breaking (or ABI-breaking) changes.

**Comment by brobr** [comment]
Thanks a lot for the feedback. I am afraid the kind of install I have been talking about might not have been clear enough:
1) the installation of R and rpy2 will be a system-wide install (as shown above to: /usr/lib{64}/R and /usr/lib{64}/{python}/site_packages)
2) in the case of a Slackware-package, this install goes in two steps: build a package (i.e. an archive) with all the files as will be installed by `python setup.py install`; install that package (i.e. copy all files inside the package to the system folders).
3) Installing a python module by means of a Slackware.package does not rely on `wheel`; nor on pip. 
4) the above method allows to distribute a pkg in the sense that the program can be built on one computer (to create the package) and then be installed on a number of other computers running the same software without the need to run pip on each of them; dependency tracking is done by the maintainer/packager, who creates an info file describing which python packages need to be installed beforehand (or are required at run time).

So, as far as I understand this all, a pip-/ or wheel-install enables that ` R shared library/libraries can be found by the linker`, which is somehow missed in the Slackware install route. As described, the small file in `/etc/ld.conf.d/` giving the path to the Rlibs is an easy work-around.

This still begs the question (at least for a noob like me) what would be missing from the R-install, if `--enable {shared libs}` is not sufficient?

**Comment by thistleknot** [comment]
> export LD_LIBRARY_PATH=/usr/lib64/R/lib/

I did this inside my service file
Environment="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mnt/distvol/R/4.0.5/lib64/R/lib/"

**Comment by lgautier** [comment]
Note that the `LD_LIBRARY_PATH` can be obtained with:

```bash
python -m rpy2.situation LD_LIBRARY_PATH
```

This can be used in a shell expression. For example:

```bash
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}":$(python -m rpy2.situation LD_LIBRARY_PATH)
```

**Comment by matthieuheitz** [comment]
I just wanted to say that I was having the same issue, but the previous solutions only worked when testing it on Python, but not in a Jupyter notebook.
My notebook is actually run from JupyterHub, so this is how I fixed the issue (it might also work simply with Jupyter (not Hub)).

#### For only my user

- run `/path/to/jupyter notebook --generate-config`. The path to jupyter must be the one used by JupyterHub.
This generates the following config file in your home folder: `~/.jupyter/jupyter_notebook_config.py`
Then add the following lines at the top of this file:
```
import os
c = get_config()
libpath = os.environ["LD_LIBRARY_PATH"] if "LD_LIBRARY_PATH" in os.environ else ""
os.environ['LD_LIBRARY_PATH'] = '/path/to/R/lib:' + libpath
c.Spawner.env.update('LD_LIBRARY_PATH')
c.Spawner.env_keep.append('LD_LIBRARY_PATH') 
```
It seems to also work without the last 2 lines, I don't really know what they're useful for, but I keep them just in case.
Then, you have to restart Jupyter/JupyterHub:
- by cmd line: you can kill the process in `htop`
- by graphical interface, go to `[your.usual.jupyter.url]/hub/home`, and click on `Stop My Server".

Then, go to `[your.usual.jupyter.url]/hub/home`, and click on `Start My Server`.
Now, when you open a notebook, you should be able to do `import r2py.robjects` without errors.
You can check if the `LD_LIBRARY_PATH` is set correctly by running
```
import os
print(os.environ["LD_LIBRARY_PATH"])
```

Sources:
https://github.com/jupyter/notebook/issues/1290#issuecomment-204388895

**Comment by brobr** [comment]
On Tue, 30 Nov 2021 00:30:08 -0800
Matthieu Heitz ***@***.***> wrote:

> I just wanted to say that I was having the same issue, but the
> previous solutions only worked when testing it on Python, but not in
> a Jupyter notebook. My notebook is actually run from JupyterHub, so
> this is how I fixed the issue (it might also work simply with Jupyter
> (not Hub)).
> 
> #### For only my user
> 
> - run `/path/to/jupyter notebook --generate-config`. The path to
> jupyter must be the one used by JupyterHub. This generates the
> following config file in your home folder:
> `~/.jupyter/jupyter_notebook_config.py` Then add the following lines
> at the top of this file: ``` import os
> c = get_config()
> libpath = os.environ["LD_LIBRARY_PATH"] if "LD_LIBRARY_PATH" in
> os.environ else "" os.environ['LD_LIBRARY_PATH'] = '/path/to/R/lib:'
> + libpath c.Spawner.env.update('LD_LIBRARY_PATH')
> c.Spawner.env_keep.append('LD_LIBRARY_PATH') 
> ```
> It seems to also work without the last 2 lines, I don't really know
> what they're useful for, but I keep them just in case. Then, you have
> to restart Jupyter/JupyterHub:
> - by cmd line: you can kill the process in `htop`
> - by graphical interface, go to `[your.usual.jupyter.url]/hub/home`,
> and click on `Stop My Server".
> 
> Then, go to `[your.usual.jupyter.url]/hub/home`, and click on `Start
> My Server`. Now, when you open a notebook, you should be able to do
> `import r2py.robjects` without errors. You can check if the
> `LD_LIBRARY_PATH` is set correctly by running ```
> import os
> print(os.environ["LD_LIBRARY_PATH"])
> ```
> 
> Sources:
> https://github.com/jupyter/notebook/issues/1290#issuecomment-204388895
> 
> 

Fwiw, I just went halfway through
https://rpy2.github.io/doc/latest/html/generated_rst/notebooks.html
without a hitch on a jupyter-notebook and without needing to adapt
jupyter. In what environment (apart from jupyterhub) have you been
trying this?

**Comment by brobr** [comment]
I checked what was installed at my end:
../python3.9/site-packages/ipykernel-5.5.3-py3.9.egg-info

and noticed this:
https://github.com/ipython/ipykernel/issues/795
Are you on ipykernel 6? That could explain why it (still) works at my
end...

**Comment by brobr** [comment]
On Tue, 30 Nov 2021 08:10:00 -0800
Matthieu Heitz ***@***.***> wrote:

Hi Matthieu,

I have no experience with anaconda environments. But what would happen
if you have your R installed there as well (incl. rpy2) ??
https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/

hth
Rob

**Comment by matthieuheitz** [comment]
Oh yeah! I could try that. Thanks!

**Comment by lgautier** [comment]
> I just wanted to say that I was having the same issue, but the previous solutions only worked when testing it on Python, but not in a Jupyter notebook. My notebook is actually run from JupyterHub, so this is how I fixed the issue (it might also work simply with Jupyter (not Hub)).
> #### For only your own user
> 
>     * run `/path/to/jupyter notebook --generate-config`. The path to jupyter must be the one used by JupyterHub.
>       This generates the following config file in your home folder: `~/.jupyter/jupyter_notebook_config.py`
>       Then add the following lines at the top of this file:
> 
> 
> ```
> import os
> c = get_config()
> libpath = os.environ["LD_LIBRARY_PATH"] if "LD_LIBRARY_PATH" in os.environ else ""
> os.environ['LD_LIBRARY_PATH'] = '/path/to/R/lib:' + libpath
> c.Spawner.env.update('LD_LIBRARY_PATH')
> c.Spawner.env_keep.append('LD_LIBRARY_PATH') 
> ```
> 
> It seems to also work without the last 2 lines, I don't really know what they're useful for, but I keep them just in case. Then, you have to restart Jupyter/JupyterHub:
> 
>     * by cmd line: you can kill the process in `htop`
> 
>     * by graphical interface, go to `[your.usual.jupyter.url]/hub/home`, and click on `Stop My Server".
> 
> 
> Then, go to `[your.usual.jupyter.url]/hub/home`, and click on `Start My Server`. Now, when you open a notebook, you should be able to do `import r2py.robjects` without errors. You can check if the `LD_LIBRARY_PATH` is set correctly by running
> 
> ```
> import os
> print(os.environ["LD_LIBRARY_PATH"])
> ```
> 
> #### For all users
> 
> Do the same, except that the config file is `jupyterhub_config_global.py`. You can find it by running `locate jupyterhub_config_global.py`.
> 
> Sources: [jupyter/notebook#1290 (comment)](https://github.com/jupyter/notebook/issues/1290#issuecomment-204388895) [jupyterhub/jupyterhub#592](https://github.com/jupyterhub/jupyterhub/issues/592)

On Linux, calling`R` from a terminal runs a shell script where a few environment environment variables are set, including `LD_LIBRARY_PATH` (technically set in `${R_HOME}/etc${R_ARCH}/ldpaths` called from that `R` script).
 
I have relied on `LD_LIBRARY_PATH` myself whenever not a system R but a few users tripped on this. There is no reason other than my lack of bandwidth to not have what is happening in the R script replicated by rpy2. I'll open a issue to track progress on this.

**Comment by lgautier** [comment]
An enhancement to make the import of rpy2 even when `LD_LIBRARY_PATH` is required but not set work is tracked in issue #833.

**Comment by lgautier** [comment]
I am working on #833. @matthieuheitz 's code snippet can be slightly modified to ensure that `LD_LIBRARY_PATH` is set given any R in the `PATH`: 

```python
import os
from rpy2.rinterface_lib import openrlib
import rpy2.situation

c = get_config()
libpath = os.environ.get('LD_LIBRARY_PATH', '')
os.environ['LD_LIBRARY_PATH'] = (
    rpy2.situation.r_ld_library_path_from_subprocess(openrlib.R_HOME) +
    libpath
)
```

**Comment by lgautier** [comment]
> I am working on #833. @matthieuheitz 's code snippet can be slightly modified to ensure that `LD_LIBRARY_PATH` is set given any R in the `PATH`:
> 
> ```python
> import os
> from rpy2.rinterface_lib import openrlib
> import rpy2.situation
> 
> c = get_config()
> libpath = os.environ.get('LD_LIBRARY_PATH', '')
> os.environ['LD_LIBRARY_PATH'] = (
>     rpy2.situation.r_ld_library_path_from_subprocess(openrlib.R_HOME) +
>     libpath
> )
> ```

Note: this does not work from within the same Python process though. Changing the environment variable is no longer matters after the process started.
