### ISSUE TITLE
Error in Rblas through windows

### ISSUE THREAD

**Issue by BrunoLQS** [rpy2/rpy2#679]
Rblas.dll is missing, even I make sure that there is Rblas. python -m rpy2.situation shows it can't be possible load R.dll file. Yes, I added the PATHS in enviroment variables. 

Can anyone help me to fix it ?

**Comment by lgautier** [comment]
rpy2 is not supported on Windows. May be you'll get better luck asking on StackOverflow.

**Comment by BrunoLQS** [comment]
But the version in anaconda (2.94) plays well. WTF??

Em qui., 9 de abr. de 2020 às 23:28, Laurent Gautier <
notifications@github.com> escreveu:

**Comment by lgautier** [comment]
Until rpy2 version 3.0.0, and in no small part thanks to contributions from rpy2 users, it was possible to compile and run it on Windows, albeit with missing features and few issues. Christoph Gohlke made binary builds available: https://www.lfd.uci.edu/~gohlke/pythonlibs/.

Anaconda is likely doing not much more than re-using this.

rpy2 >= 3.0.0 is not known to function on Windows.

**Comment by BrunoLQS** [comment]
Hello, I'm back ahahahah. Could I  to build and to release an guide to use
rpy2 ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 9 de abr. de 2020 às 23:28, Laurent Gautier <
notifications@github.com> escreveu:
