### ISSUE TITLE
Why does rpy2 v3.x return numpy array instead of rpy2 object? 

### ISSUE THREAD

**Issue by jolespin** [rpy2/rpy2#690]
I'm trying to port my code to rpy2 v3.x from rpy2 v2.x to account for the pandas v1.x compatibility issues.   I've hit several road blocks.  Some I've been able to fix.  Others I can't figure out for example: https://stackoverflow.com/questions/61398908/how-to-use-hclust-function-from-r-in-python-via-rpy2-v3

One aspect I noticed is that rpy2 keeps returning numpy arrays when I need it to return rpy2 objects. 

```
from scipy.spatial.distance import squareform
import pandas as pd
import numpy as np
from rpy2 import robjects as ro
from rpy2 import rinterface as ri
from rpy2.robjects.packages import importr
R = ro.r
# r_stats = importr("stats")

fastcluster = importr("fastcluster")

def pandas_to_rpy2(df):
    return ro.conversion.py2rpy(df)
    
def rpy2_to_pandas(r_df):
    return ro.conversion.rpy2py(r_df)

# Convert to R dataframe
dist = squareform(df_dism.values)
r_dist = R.matrix(dist)

type(r_dist) is np.ndarray
# True
```

**Comment by lgautier** [comment]
Did you check the documentation about interoperability with pandas: https://rpy2.github.io/doc/v3.3.x/html/pandas.html ?

**Comment by jolespin** [comment]
Yea, that's how I figured out how to do the conversion from pandas to rpy2 (made this feature request https://github.com/rpy2/rpy2/issues/689).  

Do you know why `R.matrix(dist)` is return ` numpy` array?  Even if I convert this to an R vector it still does this.  Can you help me figure out how to get the functionality so I can run `hclust`?

**Comment by lgautier** [comment]
> Do you know why R.matrix(dist) is return numpy array?

This looks suprising. Can you work out a self-contained example ?

**Comment by jolespin** [comment]
Sorry about that! I didn’t realize I left out that chunk of code.

`

X_iris = pd.DataFrame({'sepal_length': {'iris_0': 5.1, 'iris_1': 4.9, 'iris_2': 4.7, 'iris_3': 4.6, 'iris_4': 5.0, 'iris_5': 5.4, 'iris_6': 4.6, 'iris_7': 5.0, 'iris_8': 4.4, 'iris_9': 4.9, 'iris_10': 5.4, 'iris_11': 4.8, 'iris_12': 4.8, 'iris_13': 4.3, 'iris_14': 5.8, 'iris_15': 5.7, 'iris_16': 5.4, 'iris_17': 5.1, 'iris_18': 5.7, 'iris_19': 5.1, 'iris_20': 5.4, 'iris_21': 5.1, 'iris_22': 4.6, 'iris_23': 5.1, 'iris_24': 4.8, 'iris_25': 5.0, 'iris_26': 5.0, 'iris_27': 5.2, 'iris_28': 5.2, 'iris_29': 4.7, 'iris_30': 4.8, 'iris_31': 5.4, 'iris_32': 5.2, 'iris_33': 5.5, 'iris_34': 4.9, 'iris_35': 5.0, 'iris_36': 5.5, 'iris_37': 4.9, 'iris_38': 4.4, 'iris_39': 5.1, 'iris_40': 5.0, 'iris_41': 4.5, 'iris_42': 4.4, 'iris_43': 5.0, 'iris_44': 5.1, 'iris_45': 4.8, 'iris_46': 5.1, 'iris_47': 4.6, 'iris_48': 5.3, 'iris_49': 5.0, 'iris_50': 7.0, 'iris_51': 6.4, 'iris_52': 6.9, 'iris_53': 5.5, 'iris_54': 6.5, 'iris_55': 5.7, 'iris_56': 6.3, 'iris_57': 4.9, 'iris_58': 6.6, 'iris_59': 5.2, 'iris_60': 5.0, 'iris_61': 5.9, 'iris_62': 6.0, 'iris_63': 6.1, 'iris_64': 5.6, 'iris_65': 6.7, 'iris_66': 5.6, 'iris_67': 5.8, 'iris_68': 6.2, 'iris_69': 5.6, 'iris_70': 5.9, 'iris_71': 6.1, 'iris_72': 6.3, 'iris_73': 6.1, 'iris_74': 6.4, 'iris_75': 6.6, 'iris_76': 6.8, 'iris_77': 6.7, 'iris_78': 6.0, 'iris_79': 5.7, 'iris_80': 5.5, 'iris_81': 5.5, 'iris_82': 5.8, 'iris_83': 6.0, 'iris_84': 5.4, 'iris_85': 6.0, 'iris_86': 6.7, 'iris_87': 6.3, 'iris_88': 5.6, 'iris_89': 5.5, 'iris_90': 5.5, 'iris_91': 6.1, 'iris_92': 5.8, 'iris_93': 5.0, 'iris_94': 5.6, 'iris_95': 5.7, 'iris_96': 5.7, 'iris_97': 6.2, 'iris_98': 5.1, 'iris_99': 5.7, 'iris_100': 6.3, 'iris_101': 5.8, 'iris_102': 7.1, 'iris_103': 6.3, 'iris_104': 6.5, 'iris_105': 7.6, 'iris_106': 4.9, 'iris_107': 7.3, 'iris_108': 6.7, 'iris_109': 7.2, 'iris_110': 6.5, 'iris_111': 6.4, 'iris_112': 6.8, 'iris_113': 5.7, 'iris_114': 5.8, 'iris_115': 6.4, 'iris_116': 6.5, 'iris_117': 7.7, 'iris_118': 7.7, 'iris_119': 6.0, 'iris_120': 6.9, 'iris_121': 5.6, 'iris_122': 7.7, 'iris_123': 6.3, 'iris_124': 6.7, 'iris_125': 7.2, 'iris_126': 6.2, 'iris_127': 6.1, 'iris_128': 6.4, 'iris_129': 7.2, 'iris_130': 7.4, 'iris_131': 7.9, 'iris_132': 6.4, 'iris_133': 6.3, 'iris_134': 6.1, 'iris_135': 7.7, 'iris_136': 6.3, 'iris_137': 6.4, 'iris_138': 6.0, 'iris_139': 6.9, 'iris_140': 6.7, 'iris_141': 6.9, 'iris_142': 5.8, 'iris_143': 6.8, 'iris_144': 6.7, 'iris_145': 6.7, 'iris_146': 6.3, 'iris_147': 6.5, 'iris_148': 6.2, 'iris_149': 5.9}, 'sepal_width': {'iris_0': 3.5, 'iris_1': 3.0, 'iris_2': 3.2, 'iris_3': 3.1, 'iris_4': 3.6, 'iris_5': 3.9, 'iris_6': 3.4, 'iris_7': 3.4, 'iris_8': 2.9, 'iris_9': 3.1, 'iris_10': 3.7, 'iris_11': 3.4, 'iris_12': 3.0, 'iris_13': 3.0, 'iris_14': 4.0, 'iris_15': 4.4, 'iris_16': 3.9, 'iris_17': 3.5, 'iris_18': 3.8, 'iris_19': 3.8, 'iris_20': 3.4, 'iris_21': 3.7, 'iris_22': 3.6, 'iris_23': 3.3, 'iris_24': 3.4, 'iris_25': 3.0, 'iris_26': 3.4, 'iris_27': 3.5, 'iris_28': 3.4, 'iris_29': 3.2, 'iris_30': 3.1, 'iris_31': 3.4, 'iris_32': 4.1, 'iris_33': 4.2, 'iris_34': 3.1, 'iris_35': 3.2, 'iris_36': 3.5, 'iris_37': 3.6, 'iris_38': 3.0, 'iris_39': 3.4, 'iris_40': 3.5, 'iris_41': 2.3, 'iris_42': 3.2, 'iris_43': 3.5, 'iris_44': 3.8, 'iris_45': 3.0, 'iris_46': 3.8, 'iris_47': 3.2, 'iris_48': 3.7, 'iris_49': 3.3, 'iris_50': 3.2, 'iris_51': 3.2, 'iris_52': 3.1, 'iris_53': 2.3, 'iris_54': 2.8, 'iris_55': 2.8, 'iris_56': 3.3, 'iris_57': 2.4, 'iris_58': 2.9, 'iris_59': 2.7, 'iris_60': 2.0, 'iris_61': 3.0, 'iris_62': 2.2, 'iris_63': 2.9, 'iris_64': 2.9, 'iris_65': 3.1, 'iris_66': 3.0, 'iris_67': 2.7, 'iris_68': 2.2, 'iris_69': 2.5, 'iris_70': 3.2, 'iris_71': 2.8, 'iris_72': 2.5, 'iris_73': 2.8, 'iris_74': 2.9, 'iris_75': 3.0, 'iris_76': 2.8, 'iris_77': 3.0, 'iris_78': 2.9, 'iris_79': 2.6, 'iris_80': 2.4, 'iris_81': 2.4, 'iris_82': 2.7, 'iris_83': 2.7, 'iris_84': 3.0, 'iris_85': 3.4, 'iris_86': 3.1, 'iris_87': 2.3, 'iris_88': 3.0, 'iris_89': 2.5, 'iris_90': 2.6, 'iris_91': 3.0, 'iris_92': 2.6, 'iris_93': 2.3, 'iris_94': 2.7, 'iris_95': 3.0, 'iris_96': 2.9, 'iris_97': 2.9, 'iris_98': 2.5, 'iris_99': 2.8, 'iris_100': 3.3, 'iris_101': 2.7, 'iris_102': 3.0, 'iris_103': 2.9, 'iris_104': 3.0, 'iris_105': 3.0, 'iris_106': 2.5, 'iris_107': 2.9, 'iris_108': 2.5, 'iris_109': 3.6, 'iris_110': 3.2, 'iris_111': 2.7, 'iris_112': 3.0, 'iris_113': 2.5, 'iris_114': 2.8, 'iris_115': 3.2, 'iris_116': 3.0, 'iris_117': 3.8, 'iris_118': 2.6, 'iris_119': 2.2, 'iris_120': 3.2, 'iris_121': 2.8, 'iris_122': 2.8, 'iris_123': 2.7, 'iris_124': 3.3, 'iris_125': 3.2, 'iris_126': 2.8, 'iris_127': 3.0, 'iris_128': 2.8, 'iris_129': 3.0, 'iris_130': 2.8, 'iris_131': 3.8, 'iris_132': 2.8, 'iris_133': 2.8, 'iris_134': 2.6, 'iris_135': 3.0, 'iris_136': 3.4, 'iris_137': 3.1, 'iris_138': 3.0, 'iris_139': 3.1, 'iris_140': 3.1, 'iris_141': 3.1, 'iris_142': 2.7, 'iris_143': 3.2, 'iris_144': 3.3, 'iris_145': 3.0, 'iris_146': 2.5, 'iris_147': 3.0, 'iris_148': 3.4, 'iris_149': 3.0}, 'petal_length': {'iris_0': 1.4, 'iris_1': 1.4, 'iris_2': 1.3, 'iris_3': 1.5, 'iris_4': 1.4, 'iris_5': 1.7, 'iris_6': 1.4, 'iris_7': 1.5, 'iris_8': 1.4, 'iris_9': 1.5, 'iris_10': 1.5, 'iris_11': 1.6, 'iris_12': 1.4, 'iris_13': 1.1, 'iris_14': 1.2, 'iris_15': 1.5, 'iris_16': 1.3, 'iris_17': 1.4, 'iris_18': 1.7, 'iris_19': 1.5, 'iris_20': 1.7, 'iris_21': 1.5, 'iris_22': 1.0, 'iris_23': 1.7, 'iris_24': 1.9, 'iris_25': 1.6, 'iris_26': 1.6, 'iris_27': 1.5, 'iris_28': 1.4, 'iris_29': 1.6, 'iris_30': 1.6, 'iris_31': 1.5, 'iris_32': 1.5, 'iris_33': 1.4, 'iris_34': 1.5, 'iris_35': 1.2, 'iris_36': 1.3, 'iris_37': 1.4, 'iris_38': 1.3, 'iris_39': 1.5, 'iris_40': 1.3, 'iris_41': 1.3, 'iris_42': 1.3, 'iris_43': 1.6, 'iris_44': 1.9, 'iris_45': 1.4, 'iris_46': 1.6, 'iris_47': 1.4, 'iris_48': 1.5, 'iris_49': 1.4, 'iris_50': 4.7, 'iris_51': 4.5, 'iris_52': 4.9, 'iris_53': 4.0, 'iris_54': 4.6, 'iris_55': 4.5, 'iris_56': 4.7, 'iris_57': 3.3, 'iris_58': 4.6, 'iris_59': 3.9, 'iris_60': 3.5, 'iris_61': 4.2, 'iris_62': 4.0, 'iris_63': 4.7, 'iris_64': 3.6, 'iris_65': 4.4, 'iris_66': 4.5, 'iris_67': 4.1, 'iris_68': 4.5, 'iris_69': 3.9, 'iris_70': 4.8, 'iris_71': 4.0, 'iris_72': 4.9, 'iris_73': 4.7, 'iris_74': 4.3, 'iris_75': 4.4, 'iris_76': 4.8, 'iris_77': 5.0, 'iris_78': 4.5, 'iris_79': 3.5, 'iris_80': 3.8, 'iris_81': 3.7, 'iris_82': 3.9, 'iris_83': 5.1, 'iris_84': 4.5, 'iris_85': 4.5, 'iris_86': 4.7, 'iris_87': 4.4, 'iris_88': 4.1, 'iris_89': 4.0, 'iris_90': 4.4, 'iris_91': 4.6, 'iris_92': 4.0, 'iris_93': 3.3, 'iris_94': 4.2, 'iris_95': 4.2, 'iris_96': 4.2, 'iris_97': 4.3, 'iris_98': 3.0, 'iris_99': 4.1, 'iris_100': 6.0, 'iris_101': 5.1, 'iris_102': 5.9, 'iris_103': 5.6, 'iris_104': 5.8, 'iris_105': 6.6, 'iris_106': 4.5, 'iris_107': 6.3, 'iris_108': 5.8, 'iris_109': 6.1, 'iris_110': 5.1, 'iris_111': 5.3, 'iris_112': 5.5, 'iris_113': 5.0, 'iris_114': 5.1, 'iris_115': 5.3, 'iris_116': 5.5, 'iris_117': 6.7, 'iris_118': 6.9, 'iris_119': 5.0, 'iris_120': 5.7, 'iris_121': 4.9, 'iris_122': 6.7, 'iris_123': 4.9, 'iris_124': 5.7, 'iris_125': 6.0, 'iris_126': 4.8, 'iris_127': 4.9, 'iris_128': 5.6, 'iris_129': 5.8, 'iris_130': 6.1, 'iris_131': 6.4, 'iris_132': 5.6, 'iris_133': 5.1, 'iris_134': 5.6, 'iris_135': 6.1, 'iris_136': 5.6, 'iris_137': 5.5, 'iris_138': 4.8, 'iris_139': 5.4, 'iris_140': 5.6, 'iris_141': 5.1, 'iris_142': 5.1, 'iris_143': 5.9, 'iris_144': 5.7, 'iris_145': 5.2, 'iris_146': 5.0, 'iris_147': 5.2, 'iris_148': 5.4, 'iris_149': 5.1}, 'petal_width': {'iris_0': 0.2, 'iris_1': 0.2, 'iris_2': 0.2, 'iris_3': 0.2, 'iris_4': 0.2, 'iris_5': 0.4, 'iris_6': 0.3, 'iris_7': 0.2, 'iris_8': 0.2, 'iris_9': 0.1, 'iris_10': 0.2, 'iris_11': 0.2, 'iris_12': 0.1, 'iris_13': 0.1, 'iris_14': 0.2, 'iris_15': 0.4, 'iris_16': 0.4, 'iris_17': 0.3, 'iris_18': 0.3, 'iris_19': 0.3, 'iris_20': 0.2, 'iris_21': 0.4, 'iris_22': 0.2, 'iris_23': 0.5, 'iris_24': 0.2, 'iris_25': 0.2, 'iris_26': 0.4, 'iris_27': 0.2, 'iris_28': 0.2, 'iris_29': 0.2, 'iris_30': 0.2, 'iris_31': 0.4, 'iris_32': 0.1, 'iris_33': 0.2, 'iris_34': 0.2, 'iris_35': 0.2, 'iris_36': 0.2, 'iris_37': 0.1, 'iris_38': 0.2, 'iris_39': 0.2, 'iris_40': 0.3, 'iris_41': 0.3, 'iris_42': 0.2, 'iris_43': 0.6, 'iris_44': 0.4, 'iris_45': 0.3, 'iris_46': 0.2, 'iris_47': 0.2, 'iris_48': 0.2, 'iris_49': 0.2, 'iris_50': 1.4, 'iris_51': 1.5, 'iris_52': 1.5, 'iris_53': 1.3, 'iris_54': 1.5, 'iris_55': 1.3, 'iris_56': 1.6, 'iris_57': 1.0, 'iris_58': 1.3, 'iris_59': 1.4, 'iris_60': 1.0, 'iris_61': 1.5, 'iris_62': 1.0, 'iris_63': 1.4, 'iris_64': 1.3, 'iris_65': 1.4, 'iris_66': 1.5, 'iris_67': 1.0, 'iris_68': 1.5, 'iris_69': 1.1, 'iris_70': 1.8, 'iris_71': 1.3, 'iris_72': 1.5, 'iris_73': 1.2, 'iris_74': 1.3, 'iris_75': 1.4, 'iris_76': 1.4, 'iris_77': 1.7, 'iris_78': 1.5, 'iris_79': 1.0, 'iris_80': 1.1, 'iris_81': 1.0, 'iris_82': 1.2, 'iris_83': 1.6, 'iris_84': 1.5, 'iris_85': 1.6, 'iris_86': 1.5, 'iris_87': 1.3, 'iris_88': 1.3, 'iris_89': 1.3, 'iris_90': 1.2, 'iris_91': 1.4, 'iris_92': 1.2, 'iris_93': 1.0, 'iris_94': 1.3, 'iris_95': 1.2, 'iris_96': 1.3, 'iris_97': 1.3, 'iris_98': 1.1, 'iris_99': 1.3, 'iris_100': 2.5, 'iris_101': 1.9, 'iris_102': 2.1, 'iris_103': 1.8, 'iris_104': 2.2, 'iris_105': 2.1, 'iris_106': 1.7, 'iris_107': 1.8, 'iris_108': 1.8, 'iris_109': 2.5, 'iris_110': 2.0, 'iris_111': 1.9, 'iris_112': 2.1, 'iris_113': 2.0, 'iris_114': 2.4, 'iris_115': 2.3, 'iris_116': 1.8, 'iris_117': 2.2, 'iris_118': 2.3, 'iris_119': 1.5, 'iris_120': 2.3, 'iris_121': 2.0, 'iris_122': 2.0, 'iris_123': 1.8, 'iris_124': 2.1, 'iris_125': 1.8, 'iris_126': 1.8, 'iris_127': 1.8, 'iris_128': 2.1, 'iris_129': 1.6, 'iris_130': 1.9, 'iris_131': 2.0, 'iris_132': 2.2, 'iris_133': 1.5, 'iris_134': 1.4, 'iris_135': 2.3, 'iris_136': 2.4, 'iris_137': 1.8, 'iris_138': 1.8, 'iris_139': 2.1, 'iris_140': 2.4, 'iris_141': 2.3, 'iris_142': 1.9, 'iris_143': 2.3, 'iris_144': 2.5, 'iris_145': 2.3, 'iris_146': 1.9, 'iris_147': 2.0, 'iris_148': 2.3, 'iris_149': 1.8}})

df_dism = 1 - X_iris.T.corr().abs()
`

This should be the missing piece to run. I’m not at my computer now but I believe that’s it.

**Comment by jolespin** [comment]
Here is a self contained example. I'm showing how the functionality of R works, how rpy2 v2.x worked, and how rpy2 v3.x does not work.  

This is the expected behavior in `R`:
```
%%R
# Load data
X_iris = read.table("https://pastebin.com/raw/bxNwt3Cd", sep="\t", row.names=1, header = TRUE, check.names=FALSE)

# Create  distance matrix
df_dism = 1 - abs(cor(t(X_iris)))
print(class(df_dism))
# [1] "matrix"

dist = as.dist(df_dism)
print(class(dist))
# [1] "dist"

# Clustering
clustering = hclust(dist)
print(class(clustering))
# [1] "hclust"
```

This is the functionality from v2.9.4 and it works:

```
from scipy.spatial.distance import squareform
import pandas as pd
import numpy as np
import rpy2
from rpy2 import robjects as ro
from rpy2 import rinterface as ri

from rpy2.robjects.packages import importr
try:
    from rpy2.rinterface import RRuntimeError
except ImportError:
    from rpy2.rinterface_lib.embedded import RRuntimeError
    from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri



pandas2ri.activate()
R = ro.r

# Converters
def pandas_to_rpy2(df):
    try: # v2.x
        return pandas2ri.py2ri(df)
    except AttributeError: # v3.x
        with localconverter(ro.default_converter + pandas2ri.converter):
            return ro.conversion.py2rpy(df)
def rpy2_to_pandas(r_df):
    try: # v2.x
        return pandas2ri.ri2py(r_df)
    except AttributeError: # v3.x
        with localconverter(ro.default_converter + pandas2ri.converter):
            return ro.conversion.rpy2py(r_df)


# Versions
print(R.version[-2])
# [1] "R version 3.6.1 (2019-07-05)"

print(sys.version)
# 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 

print(rpy2.__version__)
# 2.9.4


# Data
X_iris = pd.read_csv("https://pastebin.com/raw/bxNwt3Cd", sep="\t", index_col=0)
df_dism = 1 - X_iris.T.corr().abs()

# Convert to R dataframe
r_dism = pandas_to_rpy2(df_dism)
print(type(r_dism))
# <class 'rpy2.robjects.vectors.DataFrame'>

# Convert to `dist` object
r_dist = R["as.dist"](r_dism)

# This should not return a numpy array
print(type(r_dist) is np.ndarray)
# False

# This does not work with hclust
R.hclust(r_dist)
print("hclust worked")
# hclust worked

importr("fastcluster").hclust(r_dist)
print("fastcluster worked")
# fastcluster worked
```

The functionality adapted for v3.x doesn't work: 

```
from scipy.spatial.distance import squareform
import pandas as pd
import numpy as np
import rpy2
from rpy2 import robjects as ro
from rpy2 import rinterface as ri
from rpy2.robjects.packages import importr

R = ro.r

def pandas_to_rpy2(df):
    return ro.conversion.py2rpy(df)
    
def rpy2_to_pandas(r_df):
    return ro.conversion.rpy2py(r_df)

# Versions
print(R.version[-2])
# ['R version 3.6.1 (2019-07-05)']

print(sys.version)
# 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 

print(rpy2.__version__)
# '3.3.2'


# Data
X_iris = pd.read_csv("https://pastebin.com/raw/bxNwt3Cd", sep="\t", index_col=0)
df_dism = 1 - X_iris.T.corr().abs()

# Convert to R dataframe
r_dism = pandas_to_rpy2(df_dism)
print(type(r_dism))
# <class 'rpy2.robjects.vectors.DataFrame'>

# Convert to `dist` object
r_dist = R["as.dist"](r_dism)

# This should not return a numpy array
type(r_dist) is np.ndarray
# True

# This does not work with hclust
R.hclust(r_dist)

# R[write to console]: Error in (function (d, method = "complete", members = NULL)  : 
#   'N' must be a single integer.
# ---------------------------------------------------------------------------
# RRuntimeError                             Traceback (most recent call last)
# <ipython-input-83-16a8124e4090> in <module>
#      45 
#      46 # This does not work with hclust
# ---> 47 R.hclust(r_dist)

# ~/anaconda3/envs/soothsayer2_env/lib/python3.6/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
#     196                 kwargs[r_k] = v
#     197         return (super(SignatureTranslatedFunction, self)
# --> 198                 .__call__(*args, **kwargs))
#     199 
#     200 

# ~/anaconda3/envs/soothsayer2_env/lib/python3.6/site-packages/rpy2/robjects/functions.py in __call__(self, *args, **kwargs)
#     123             else:
#     124                 new_kwargs[k] = conversion.py2rpy(v)
# --> 125         res = super(Function, self).__call__(*new_args, **new_kwargs)
#     126         res = conversion.rpy2py(res)
#     127         return res

# ~/anaconda3/envs/soothsayer2_env/lib/python3.6/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
#      42 def _cdata_res_to_rinterface(function):
#      43     def _(*args, **kwargs):
# ---> 44         cdata = function(*args, **kwargs)
#      45         # TODO: test cdata is of the expected CType
#      46         return _cdata_to_rinterface(cdata)

# ~/anaconda3/envs/soothsayer2_env/lib/python3.6/site-packages/rpy2/rinterface.py in __call__(self, *args, **kwargs)
#     619                     error_occured))
#     620             if error_occured[0]:
# --> 621                 raise embedded.RRuntimeError(_rinterface._geterrmessage())
#     622         return res
#     623 

# RRuntimeError: Error in (function (d, method = "complete", members = NULL)  : 
#   'N' must be a single integer.
```

I can't just use v2.9.4 because it is not compatible with pandas v1.x:
https://github.com/rpy2/rpy2/issues/680

**Comment by krassowski** [comment]
It seems that you still have the old version of `pandas_to_rpy2` and `rpy2_to_pandas` in the v3.x example (they are ok in the 2.9.x example)

**Comment by jolespin** [comment]
Thanks for catching that.  I've updated it and I get a similar error.  I'll keep trying some things right now.

**Comment by jolespin** [comment]
Is it still necessary to use `pandas2ri.activate()` in v3.x? If so, at what version is this unnecessary? I'm trying to find the source of the error in my code base.

**Comment by jolespin** [comment]
Ok, I think I figured it out!
When you use `pandas2ri.activate()` on `v3.x` it forces `np.ndarray` from the `R["as.dist"]` function but in `v2.x` it doesn't. 

![image](https://user-images.githubusercontent.com/9061708/81003743-347d6a00-8e00-11ea-9fc2-309afa4f061a.png)


![image](https://user-images.githubusercontent.com/9061708/81003595-f84a0980-8dff-11ea-98d8-3ac872622c09.png)

![image](https://user-images.githubusercontent.com/9061708/81003650-09931600-8e00-11ea-9e58-133579a22021.png)

**Comment by jolespin** [comment]
This was all in the same notebook.

**Comment by lgautier** [comment]
Don't use `activate` if you can avoid it. Prefer local converters.

Check the (recently updated) documentation:
https://rpy2.github.io/doc/v3.3.x/html/robjects_convert.html

**Comment by jolespin** [comment]
Thanks, I realized that I had an activate command in my ipython profile.  

What does activate do exactly?

**Comment by NGluna03** [comment]
Hi, I have exactly the same problem with rpy2 v.3.x . Did you solve this issue removing the activate command? Because for me it doesn't work.  
Thank you in advance

**Comment by lgautier** [comment]
> What does activate do exactly?

`activate()` adds a set of conversion rules (say, the set of conversion rules for `pandas` objects) to the existing rules and makes the result the new default. There were quite a few issues with this, and local converters should fix at least some of them.

**Comment by genecell** [comment]
I downgraded rpy2 3.4 to rpy2 3.3.2, and the problem was solved.

**Comment by aaszodi** [comment]
> I downgraded rpy2 3.4 to rpy2 3.3.2, and the problem was solved.

Please don't get me wrong, I appreciate your contribution, but this is not a _solution_ but rather a _workaround_. 

Closer to a solution would be if I knew how to `deactivate()` this conversion to get back to RPy2-s default behaviour which is, I believe, to return `rpy2.robject` objects.

My problem is that I wrote a package that uses RPy2 and IPython, and the assumption that the operations in R return objects like `rpy2.robjects.vectors.IntVector`. This works on the IPython command line with Version 3.5 or RPy2 (so downgrading is not necessary). However, when I try to use the package in a JupyterLab "data science" notebook container (image is `jupyter/datascience-notebook:hub-2.3.1`), I get the unwanted conversions to NumPy arrays.

Example: on the IPython command line:

```
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import rpy2.robjects
In [2]: from IPython.core.getipython import get_ipython
In [3]: ipy = get_ipython()
In [5]: ipy.run_line_magic("load_ext", "rpy2.ipython")
[...pandas warning deleted...]

In [6]: ipy.run_line_magic("R","1:3")
Out[6]: 
<rpy2.robjects.vectors.IntVector object at 0x1114f0500> [RTYPES.INTSXP]
R classes: ('integer',)
[1, 2, 3]
```

Same thing in the JupyterLab "data science" notebook (I show the last line only:)

```
ipy.run_line_magic("R","1:3")
array([1, 2, 3], dtype=int32)
```

 I _suspect_ (but cannot confirm) that either there's some version mismatch between my command-line IPython and/or RPy2 and what's in the notebook image, or (worse) the notebook image contains a different conversion setting which I'd like to reset. Maybe it detects that NumPy is installed by default and tries to be helpful by activating the to-numpy-array conversions. I don't know.

Any help would be much appreciated...
