### ISSUE TITLE
R function outpust rpy2.robjects.vectors.ListVector when all elements are numeric

### ISSUE THREAD

**Issue by TremaMiguel** [rpy2/rpy2#693]
The following extract consider two different kind of outputs when calling the function `na_kalman` from the `imputeTS` package. In case of the item `FOODS_3_704_CA_2_validation` the output is `double` and `rpy2.robjects.vectors.FloatVector` when calling the `typeof` R function and `type` Python function respectively. The issue is that even thought all the elements of the vector are numbers, it could output the types `List` and `rpy2.robjects.vectors.ListVector`  when calling the function `na_kalman`. 

 Thus, if it outputs a `list` type, then, when running 
```
train = np.array(train)
``` 
it will output 
```
ValueError: Buffer for this type not yet supported
```
because it is not possible to convert a list to a numpy array. However, the [documentation](https://cran.r-project.org/web/packages/imputeTS/imputeTS.pdf) of the `imputeTS` package says that `na_kalman` and `na_ma` should ouput `Vector (vector) or Time Series (ts) object (dependent on given input at parameter x)`. Thus, notice on the code below that `na_kalman` and `na_ma` take as an input an `ts` object therefore it should output a similar object as the documentation states, but it outputs an `rpy2.robjects.vectors.ListVector` when running the process for the item `FOODS_3_714_CA_2_validation`. I think that there could be some problem within the conversion, because if you print `train`  after running `na_kalman` or `na_ma` all the values are numeric but it cannot convert it to a numeric vector, for example, one could add 
```
if type(train) == ro.vectors.ListVector:
    train = ro.vectors.FloatVector(train)
```
but it will output 
```
ValueError: Invalid SEXP type '19' (should be 14).
```
Thus, one way to manage this is to convert to a FloatVector after you're replacing the the zeros by NaN values, that is 
```
# Replace zeros with NA's
train = train.replace(to_replace=0, value=np.nan)  
train = ro.FloatVector(train)
```
and it will work. But my doubt is regarding the fact that the conversion is failling, it cannot be that the conversion of the `ts` object fails because it will output an invalid type error as follows

```
RRuntimeError: invalid 'type' (list) of argument
```

Therefore, I think the error is in converting the output of the function to an appropiate Python object. Here is the code for reproducting the error. The data could be get from the following [link](https://www.kaggle.com/c/m5-forecasting-accuracy/data)

```
from tqdm import tqdm 
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri
import rpy2.robjects as ro 
import pandas as pd

# Activate automatic conversion
pandas2ri.activate()

# Import R libraries
imputeTS, base = importr('imputeTS'), base = importr('base')

# Import R functions
na_ma, na_kalman =  imputeTS.na_ma, imputeTS.na_kalman

# Import R objects 
ts=ro.r('ts')

# Load data
dt_sales = pd.read_csv( 'data/sales_train_validation.csv')
items = [`FOODS_3_704_CA_2_validation`, `FOODS_3_714_CA_2_validation`]
iterable = dt_sales[dt_sales.id.isin(items)]

for index,row in tqdm(iterable.iterrows(), total=iterable.shape[0]):
    item_id, since_d1, zero_bin = row[0], row[-3], row[-1]
    
    # Split data
    sales = row[6+since_d1:-5]
    train = sales[-360:]
    
    # Replace zeros with NA's
    train = train.replace(to_replace=0, value=np.nan)  
    
    try:
        train = na_kalman(ts(train), smooth=True, maxgap=3)
    except rpy2.rinterface.RRuntimeError as e:
        train = na_ma(ts(train), maxgap=3)
        print(e)
  
    print(base.typeof(train))
    print(type(train))
    
    # Remove NaN values 
    train = np.array(train)
    train = train[~np.isnan(train)]
    
     # Some other operations
```

**Comment by lgautier** [comment]
> (...)
> ```python
> if type(train) == ro.vectors.ListVector:
>     train = ro.vectors.FloatVector(train)
> ```
> but it will output
> ```
> ValueError: Invalid SEXP type '19' (should be 14).
> ```

This is currently the expected behaviour. Rpy2's "<something>Vector" classes represent C-level R objects that are not compatible. The R `typeof`, you can get with `train.typeof` is 19 for R lists, and 14 for arrays of floats.

If you have, say, an R list where all items in the list are length-1 arrays of numerical values, the way to obtain an R array of floats would be:

```python
train = ro.vectors.FloatVector([elt[0] for elt in train])
```

**Comment by lgautier** [comment]
Also, check the (recently updated) documentation about the conversion system: https://rpy2.github.io/doc/v3.3.x/html/robjects_convert.html

**Comment by TremaMiguel** [comment]
Thanks @lgautier, for further use I'll definitively `Customize the conversion` and ensure the proper conversion is done when calling an ouput of an R function.
