### ISSUE TITLE
KeyError: "'str2lang' not found"

### ISSUE THREAD

**Issue by gopel** [rpy2/rpy2#694]
Hi,

I downloaded and installed rpy2 through pip, and it seemed to work well. However, whenever I try to import a package through my Jupyter Notebook, I get the error "KeyError: "'str2lang' not found" (details below).

I work on a distant machine running on R 3.4 and on which I have no sudo rights. I tried to download R 3.6 to correct it, and installed it in my personal user space. Then I created an alias (R=/home/gopel/good_R/bin/R, I verify with "R --version" that I do have R 3.6.3), reinstalled rpy2, and launched a Jupyter Notebook, but to no avail.
I also verified, and "str2lang" seems to be available in my R shell.
I did not spend much time looking at the python side, since I have been working on Python on this machine for several months now.

Could you help me please?
Thanks in advance for your time.

Here is the whole error:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-fb23c6edefe4> in <module>
----> 1 get_ipython().run_line_magic('load_ext', 'rpy2.ipython')

/usr/lib64/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

</usr/lib64/python3.6/site-packages/decorator.py:decorator-gen-64> in load_ext(self, module_str)

/usr/lib64/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/usr/lib64/python3.6/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     31         if not module_str:
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 
     35         if res == 'already loaded':

/usr/lib64/python3.6/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     78             if module_str not in sys.modules:
     79                 with prepended_to_syspath(self.ipython_extension_dir):
---> 80                     mod = import_module(module_str)
     81                     if mod.__file__.startswith(self.ipython_extension_dir):
     82                         print(("Loading extensions from {dir} is deprecated. "

/usr/lib64/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib64/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib64/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib64/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib64/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib64/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib64/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.local/lib64/python3.6/site-packages/rpy2/ipython/__init__.py in <module>
----> 1 from . import rmagic
      2 
      3 load_ipython_extension = rmagic.load_ipython_extension

~/.local/lib64/python3.6/site-packages/rpy2/ipython/rmagic.py in <module>
     55 import rpy2.rinterface as ri
     56 import rpy2.rinterface_lib.callbacks
---> 57 import rpy2.robjects as ro
     58 import rpy2.robjects.packages as rpacks
     59 from rpy2.robjects.lib import grdevices

~/.local/lib64/python3.6/site-packages/rpy2/robjects/__init__.py in <module>
     25 from . import conversion
     26 from . import vectors
---> 27 from . import language
     28 
     29 from rpy2.rinterface import (Sexp,

~/.local/lib64/python3.6/site-packages/rpy2/robjects/language.py in <module>
     14 _reval = ri.baseenv['eval']
     15 _parse = ri.parse
---> 16 _str2lang = ri.baseenv['str2lang']
     17 
     18 

~/.local/lib64/python3.6/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
     42 def _cdata_res_to_rinterface(function):
     43     def _(*args, **kwargs):
---> 44         cdata = function(*args, **kwargs)
     45         # TODO: test cdata is of the expected CType
     46         return _cdata_to_rinterface(cdata)

~/.local/lib64/python3.6/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in _(*args, **kwargs)
    280 def _evaluated_promise(function):
    281     def _(*args, **kwargs):
--> 282         robj = function(*args, **kwargs)
    283         if _TYPEOF(robj) == openrlib.rlib.PROMSXP:
    284             robj = openrlib.rlib.Rf_eval(

~/.local/lib64/python3.6/site-packages/rpy2/rinterface_lib/sexp.py in __getitem__(self, key)
    353         # TODO: move check of R_UnboundValue to _rinterface
    354         if res == openrlib.rlib.R_UnboundValue:
--> 355             raise KeyError("'%s' not found" % key)
    356         return res
    357 

KeyError: "'str2lang' not found"

**Comment by lgautier** [comment]
This seems like an R installation issue on your system rather than an rpy2 issue. Reopen if not the case.

Did you try to run a diagnosis of the rpy2/R setup with :  
```bash
python -m rpy2.situation
```
?
