### ISSUE TITLE
How to print out the full traceback when an `RRuntimeError` exception is raised.

### ISSUE THREAD

**Issue by kswann-imb** [rpy2/rpy2#698]
In python I'm calling some code that calls an R function from a package I wrote.

When an error is encountered in executing the function an `rpy2.rinterface.RRuntimeError` is raised, but the error message appears to be just the last line of the stack trace, which is an anonymous function, and I can't see the full stack trace to determine where the error originated.

Is there any way to get rpy2 to print out the full R side stack trace on errors in general and specifically on the `rpy2.rinterface.RRuntimeError`?

Here's the truncated error output. Any way to improve this?

```
rpy2.rinterface_lib.callbacks:callbacks.py:116 R[write to console]: Error in .f(.x[[i]], ...) : 
  (list) object cannot be coerced to type 'double'
Calls: <Anonymous> ... <Anonymous> -> lst_quos -> eval_tidy -> <Anonymous> -> .f
```

I tried the solution suggested here, but with no luck. https://stackoverflow.com/questions/40002972/capturing-traceback-from-r-when-an-rruntimeerror-is-raised

**Comment by lgautier** [comment]
There seems to be a bug when calling R's `traceback` (see issue #700).

**Comment by lgautier** [comment]
This seems to work:

```python
import rpy2.robjects as ro 
f = ro.r("""function() stop("foo")""") 

try:
  f()  # Error here
finally:
  tb = ro.r("traceback")()
  # repr(rb) will not because of issue #700 
```

Reopen if I missed something.
