### ISSUE TITLE
Setting contrasts using return values from r function calls

### ISSUE THREAD

**Issue by ejolly** [rpy2/rpy2#699]
I've noticed in the latest version of rpy2 a previous method for setting custom contrasts for a `lm` or `lmer` model no longer works and was wondering what the appropriate syntax is to do this using `robjects`. 

### Goal
In native R the (admittedly weird) syntax for setting a custom contrast for a factor, e.g. with 2 levels is:  
`contrasts(df$variable) <- c(0.5, -0.5)`

How do we perform this same operation using rpy2? 

### What never worked
In Python for example, we can't assign to a function call:  
```
import rpy2.robjects.packages import importr
stats = importr('stats')
stats.contrast(df['variable']) = np.array([0.5, -.05]) # obviously doesn't work
```
### What used to work
But a work around is writing a custom R function and calling it from Python using `robjects.r`. For example, let's say I have a 3 column pandas dataframe with rows as observations, 1 column for a dependent variable, 1 column for a categorical independent variable, and 1 column for a group identifier. 

| DV  | IV | Group|
| ---- | ---- | ---- |
| 1.5  | 'A'  | 1 |
| 3.1  | 'B'  | 1 |
| 2.2  | 'A'  | 2 |
| 4.8  | 'B'  | 2 |

The following used to work:

#### Step 0 imports and data loading:
```
# Setup
import numpy as np
import pandas as pd
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects
pandas2ri.activate()

# Load the dataframe described above
df = pd.read_csv('mydata.csv')

# Make sure the variable we want to set contrasts for a categorical type in pandas
df['IV'] = df['IV'].astype('category')
```

#### Step 1. Define a function in R that can be called from Python
```
# Define a function in R and call it from python 
# to set contrasts on the categorical variable
rstring = """
            function(df,f,c){
            contrasts(df[,f]) <- c(c)
            return(df)
            }
            """

# Turn into an callable function
make_contrasts = robjects.r(rstring)
```
#### Step 2. Set contrast values in Python and call the function
```
# Set up the desired contrasts in python
contrasts = np.array([-0.5, 0.5])

# Get a version of the dataframe with contrasts set
r_df  = make_contrasts(df, 'IV', contrasts)
```

#### Step 3. Run the model
```
# Import lme4
lmer = importr('lme4')

# Using the r_df dataframe with contrasts set
model = lmer.lmer('DV~IV+(1|Group)',data=r_df)

# Do whatever with the model...
```

While there are no errors with this workflow, the `make_contrasts` function never has any effect because R does not pick up these new contrast values. I'm guessing this is because the outputted pandas dataframe from that function call, i.e. `r_df = make_contrasts(df, 'IV', contrasts)` has no attributes that save the contrasts? However, in previous versions of rpy2 (e.g. <= 3.1 as far as I can tell) this would work just fine and the computed contrasts would work as expected. 

Is there a different approach that should be taken for manipulating and setting contrasts in this way? The confusing thing is how to convert `contrasts(df$variable) <- c(0.5,-0.5)` into python code, because in python that would require assigning to a function call which isn't possible.

**Comment by lgautier** [comment]
Activating the pandas conversion globally will try to turn all R data frames into pandas and pands data frames into R data frames.

Using a local converter would limit the scope of the conversion, and is the recommended approach.

**Comment by ejolly** [comment]
Thanks for the reply @lgautier. Is there an example I can reference somewhere to see how to use a local converter? Also do you have any insight as to why the approach I outlined _used to_ work, but no longer does?

**Comment by lgautier** [comment]
An answer to the first question is:
https://rpy2.github.io/doc/v3.3.x/html/robjects_convert.html?highlight=localconverter#local-conversion-rules

Regarding the second question, the use of a global converter was working but was extremely brittle in case addition custom conversions where added. The current attempt fix this resulted in "breaking" breakage `activate`, while in fact `activate` was somewhat broken by design.

**Comment by ejolly** [comment]
Ah I see thanks much!

**Comment by lgautier** [comment]
To the best of my understanding the issue is solved. Reopen if not the case.
