### ISSUE TITLE
Calling pROC.roc.test fail

### ISSUE THREAD

**Issue by LLYXC** [rpy2/rpy2#703]
Hi, thank you so much for this contribution. I am new to R and rpy2. I was going to calling roc.test from the R package pROC package, but it seems I can only import('pROC') and calling the first object roc.  

My code is as follows:
`pROC = rpkg.importr('pROC');
print(pROC.roc);
print(pROC.roc.test)`
It could be observed that pROC.roc is an R function object, but the second one failed with an error message:
`AttributeError: 'DocumentedSTFunction' object has no attribute 'test'`

In R, the code should be as follows:
`library(pROC);
roc.test(roc_1_to_compare, roc_2_to_compare)`

I wonder how can I use this function?

**Comment by lgautier** [comment]
`.` is not a valid character for attribute names in Python. `print(pROC.roc_test)` will work.

More explanations are in the documentation:
https://rpy2.github.io/doc/v3.3.x/html/introduction.html#importing-packages
