### ISSUE TITLE
Possible bug in packages.isinstalled()

### ISSUE THREAD

**Issue by PolinaBevad** [rpy2/rpy2#705]
Hi all!

I guess there is a possible bug in this line: https://github.com/rpy2/rpy2/blob/a1f471a3de7a48eeda75a34a5052123e18181d2a/rpy2/robjects/packages.py#L469

When we import packages, we can provide `lib_loc` parameter to import library from a specific directory. In my case I want to load some "standard" packages (which are in default library path with libraries collection folder where I don't have access to remove or add libraries, so it is in `.libPaths()`), and other packages from a different location where I can add new one. 

So I've tried: 
`importr(package, lib_loc='/path/to/my/libraries')` 
and got the error:
`rpy2.robjects.packages.PackageNotInstalledError: 'The R package "%s" is not installed.' % name`

Then I've checked the list of libraries in `InstalledPackages` and see that it checks on libraries in default path only. In this case `lib_loc` never used in `isinstalled()` check, so only the default libraries path will be checked. I think the line must be: `if not isinstalled(name, lib_loc)` to fix this.

If I'm wrong, can you please tell what is the purpose of `lib_loc` then?
Thanks!

**Comment by lgautier** [comment]
You are right. This is a bug.

**Comment by lgautier** [comment]
Fixed in `v3.3.x` and in `master`. Will be included in release 3.3.4.
