### ISSUE TITLE
Help wanted: rpy2 cannot load R on Windows

### ISSUE THREAD

**Issue by loikein** [rpy2/rpy2#708]
Hi. I am trying to test a Python function which is a translation of an R function, for a package where we use `conda` for environment management.

When setting up, `rpy2` is installed with `environment.yml` through `pip`, which succeeded.

When testing, rpy2 seems not able to find the R path, with `python -m rpy2.situation` output:

```
rpy2 version:
3.3.4
Python version:
3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Looking for R's HOME:
    Environment variable R_HOME: None
    InstallPath in the registry: C:\R
    Environment variable R_USER: None
    Environment variable R_LIBS_USER: d:\a\_temp\Library
R version:
    In the PATH: None
    Loading R library from rpy2: cannot load library 'C:\R\bin\x64\R.dll': error 0x7e
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['C:/R/include', 'C:/R/include/x64']
  libraries:
  ['R', 'm']
  library_dirs:
  ['C:/R/bin/x64']
  extra_compile_args:
  []
  extra_link_args:
  []
```

I am using `r-lib/actions/setup-r@master` for GitHub CI, as this repo also does.

Full log: https://github.com/OpenSourceEconomics/econsa/pull/33/checks?check_run_id=800818371

Any help is welcome!

**Comment by lgautier** [comment]
rpy2's CI does use `r-lib/actions` but does not use conda:
https://github.com/rpy2/rpy2/blob/master/.github/workflows/pythonpackage.yml

I do not know whether `r-lib/actions` is meant to work with conda.

**Comment by loikein** [comment]
Thank you for your attention. I do noticed that rpy2 does not use conda, but I am using conda's embedded pip to install rpy2, so in theory it should be the same as using standalone pip.
Besides, the rpy2 installation in question did find R on both Linux and macOS, only not on Windows.

**Comment by lgautier** [comment]
A large fraction of the installation issues I am hearing about seem to be associated with conda, so I am guessing that things are not strictly as if one was installing outside of conda with pip.

I am otherwise unable to give recommendation about conda usage (as I am not using conda myself).

**Comment by loikein** [comment]
Thank you.

We have since moved to install `r-base` using conda, which still didn't work on Windows (and worked on Linux & Mac).
I have tried various methods, including adding `set R_HOME` and `setx R_HOME`, setting `os.environ["R_HOME"]` according to this [post](https://bitbucket.org/rpy2/rpy2/issues/487#comment-57433542), etc, but non has worked. You can view the full log in my PR. 

We have to move on now, but if anyone has a solution, please contact me…

**Comment by loikein** [comment]
I am happy to report that the problem was solved with downloading everything inside default channel, but not pip channel. So the `environment.yml` looks like this:

```yaml
dependencies:
…
  - numpy
  - r-base
  - r-r.utils
  - r-other-package
  - rpy2==2.9.4
```

The `rpy2==2.9.4` is needed for this on Linux to work.

**Comment by lgautier** [comment]
Good if it works for you.

Note that rpy2-2.9.4 is rather old, and this might get you a number of issues (or unresolved bugs).

**Comment by loikein** [comment]
> Note that rpy2-2.9.4 is rather old

Yes, but it seems to be the newest working version on Ubuntu for the package `condMVNorm`, which is the R package that we are using. Thank you for all your replies!
