### ISSUE TITLE
ERROR when pip installing on mac

### ISSUE THREAD

**Issue by hossam-zaki** [rpy2/rpy2#709]
Hello! Apologizes for the long issue, but I am getting this error when pip installing this package, and would really appreciate any help!
`ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-j0rkqqj2/rpy2/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-j0rkqqj2/rpy2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-7w_yuuhy/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/rpy2
         cwd: /private/tmp/pip-install-j0rkqqj2/rpy2/
    Complete output (147 lines):
    cffi mode: CFFI_MODE.ANY
    running install
    running build
    running build_py
    file _rinterface_cffi_abi.py (for module _rinterface_cffi_abi) not found
    creating build
    creating build/lib.macosx-10.6-intel-3.7
    creating build/lib.macosx-10.6-intel-3.7/rpy2
    copying ./rpy2/situation.py -> build/lib.macosx-10.6-intel-3.7/rpy2
    copying ./rpy2/_rinterface_cffi_build.py -> build/lib.macosx-10.6-intel-3.7/rpy2
    copying ./rpy2/rinterface.py -> build/lib.macosx-10.6-intel-3.7/rpy2
    copying ./rpy2/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2
    creating build/lib.macosx-10.6-intel-3.7/rpy2/rlike
    copying ./rpy2/rlike/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rlike
    copying ./rpy2/rlike/container.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rlike
    copying ./rpy2/rlike/functional.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rlike
    copying ./rpy2/rlike/indexing.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rlike
    creating build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/_rinterface_capi.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/embedded_mswin.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/na_values.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/conversion.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/openrlib.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/bufferprotocol.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/ffi_proxy.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/memorymanagement.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/callbacks.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/sexp.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/embedded.py -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    creating build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/functions.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/vectors.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/numpy2ri.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/methods.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/constants.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/conversion.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/packages_utils.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/pandas2ri.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/packages.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/language.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/environments.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/help.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    copying ./rpy2/robjects/robject.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects
    creating build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/grid.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/tidyr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/ggplot2.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/grdevices.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/dbplyr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    copying ./rpy2/robjects/lib/dplyr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/robjects/lib
    creating build/lib.macosx-10.6-intel-3.7/rpy2/interactive
    copying ./rpy2/interactive/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/interactive
    copying ./rpy2/interactive/packages.py -> build/lib.macosx-10.6-intel-3.7/rpy2/interactive
    copying ./rpy2/interactive/process_revents.py -> build/lib.macosx-10.6-intel-3.7/rpy2/interactive
    creating build/lib.macosx-10.6-intel-3.7/rpy2/ipython
    copying ./rpy2/ipython/rmagic.py -> build/lib.macosx-10.6-intel-3.7/rpy2/ipython
    copying ./rpy2/ipython/html.py -> build/lib.macosx-10.6-intel-3.7/rpy2/ipython
    copying ./rpy2/ipython/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/ipython
    copying ./rpy2/ipython/ggplot.py -> build/lib.macosx-10.6-intel-3.7/rpy2/ipython
    creating build/lib.macosx-10.6-intel-3.7/rpy2/tests
    copying ./rpy2/tests/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests
    copying ./rpy2/tests/utils.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests
    creating build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_pairlist.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_externalptr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_na.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_openrlib.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_callbacks.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_endr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_byte.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vectors.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_complex.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_memorymanagement.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_int.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_embedded_r.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_numpy.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_bool.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_str.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_bufferprotocol.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_float.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_functions.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_lang.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_vector_list.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_noinitialization.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_symbol.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_environment.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    copying ./rpy2/tests/rinterface/test_sexp.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rinterface
    package init file './rpy2/tests/rlike/__init__.py' not found (or not a regular file)
    creating build/lib.macosx-10.6-intel-3.7/rpy2/tests/rlike
    copying ./rpy2/tests/rlike/test_container.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rlike
    copying ./rpy2/tests/rlike/test_functional.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rlike
    copying ./rpy2/tests/rlike/test_indexing.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/rlike
    creating build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_formula.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_pandas_conversions.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_methods.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_packages.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_robjects.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_conversion_numpy.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_array.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_conversion.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_packages_utils.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_vector_extractdelegator.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_vector.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_vector_factor.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_translated_function.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_function.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_rs4.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_serialization.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_language.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_vector_datetime.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_help.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_environment.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    copying ./rpy2/tests/robjects/test_dataframe.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects
    creating build/lib.macosx-10.6-intel-3.7/rpy2/tests/ipython
    copying ./rpy2/tests/ipython/__init__.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/ipython
    copying ./rpy2/tests/ipython/test_html.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/ipython
    copying ./rpy2/tests/ipython/test_ggplot.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/ipython
    copying ./rpy2/tests/ipython/test_rmagic.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/ipython
    package init file './rpy2/tests/robjects/lib/__init__.py' not found (or not a regular file)
    creating build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/tests/robjects/lib/test_dbplyr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/tests/robjects/lib/test_grid.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/tests/robjects/lib/test_grdevices.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/tests/robjects/lib/test_ggplot2.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/tests/robjects/lib/test_dplyr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/tests/robjects/lib/test_tidyr.py -> build/lib.macosx-10.6-intel-3.7/rpy2/tests/robjects/lib
    copying ./rpy2/rinterface_lib/R_API.h -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    copying ./rpy2/rinterface_lib/R_API_eventloop.h -> build/lib.macosx-10.6-intel-3.7/rpy2/rinterface_lib
    file _rinterface_cffi_abi.py (for module _rinterface_cffi_abi) not found
    generating cffi module 'build/lib.macosx-10.6-intel-3.7/_rinterface_cffi_abi.py'
    running build_ext
    generating cffi module 'build/temp.macosx-10.6-intel-3.7/_rinterface_cffi_api.c'
    creating build/temp.macosx-10.6-intel-3.7
    building '_rinterface_cffi_api' extension
    creating build/temp.macosx-10.6-intel-3.7/build
    creating build/temp.macosx-10.6-intel-3.7/build/temp.macosx-10.6-intel-3.7
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -DRPY2_RLEN_LONG=True -Irpy2/rinterface_lib/ -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.6-intel-3.7/_rinterface_cffi_api.c -o build/temp.macosx-10.6-intel-3.7/build/temp.macosx-10.6-intel-3.7/_rinterface_cffi_api.o
    gcc -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.7/build/temp.macosx-10.6-intel-3.7/_rinterface_cffi_api.o -L/usr/local/lib -lpcre -llzma -lbz2 -lz -licucore -lm -liconv -o build/lib.macosx-10.6-intel-3.7/_rinterface_cffi_api.abi3.so -fopenmp -F/Library/Frameworks/R.framework/.. -framework R
    clang: error: unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-j0rkqqj2/rpy2/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-j0rkqqj2/rpy2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-7w_yuuhy/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/rpy2 Check the logs for full command output.`

**Comment by lgautier** [comment]
The error is likely the one reported by your C compiler (clang), and shown near the end of the output shared:
```
error: unsupported option '-fopenmp'
```

The ways are to address it are one of:
- install a more recent llvm with openmp (e.g., via homebrew)
- install libomp
- install gcc
- install a precompiled binary (binary wheels will eventually make it to pypi, but they are already here: https://github.com/rpy2/rpy2/actions/runs/142591376)
