### ISSUE TITLE
segmentation fault when running "import rpy2.robjects as robjects"

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#72]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/63) by Mike Lawrence (Bitbucket: [mLaw](https://bitbucket.org/mLaw), GitHub: [mLaw](https://github.com/mLaw)).**

----------------------------------------

I've actually received this with a variety of rpy2 versions, including rpy2-2.2.0alpha0, and rpy2-2.1.9. I'm on a mac with OS 10.6.5 running python 2.6.5 and have R 2.12.0 installed. Attached is the crash report.

**Comment by paulmueller** [comment]
I would suggest to close this stale issue.

It refers to a very old rpy2 version and is probably fixed already.

**Comment by lgautier** [comment]
Yes. Thanks.
