### ISSUE TITLE
Can't close R Graphics Device when running R file

### ISSUE THREAD

**Issue by TheLazyHatGuy** [rpy2/rpy2#734]
**Describe the issue or bug**

I am attempting to use rpy2 to run an R file from Python.
The current problem is that running the R file opens the R graphics device and there doesn't seem to be a way to close it

**To Reproduce**
```python
if path is not None:
    try:
        r = robj.r
        r.source(path)
    except RRuntimeError as e:
        self.logger.exception(e)
        QMessageBox.about(self, "Error", "Failed to run R file: " + str(e))
    else:
        QMessageBox.about(self, "Success", "R file ran successfully")
        r.__cleanup__()
```

**Expected behavior**
The graphics device closes

**Error**
```
Traceback (most recent call last):
  File "src/main/python/main.py", line 83, in <module>
    exit_code = app.app.exec_()
  File "src/main/python/views/RunWidget.py", line 300, in run_report
    r.__cleanup__()
  File "env/lib/python3.8/site-packages/rpy2/robjects/__init__.py", line 404, in __cleanup__
    rinterface.endEmbeddedR()
AttributeError: module 'rpy2.rinterface' has no attribute 'endEmbeddedR'
```

**Comment by lgautier** [comment]
This code was likely missed in the rewrite for rpy2-3.0.0.

I you only want to close graphical devices, there might be better ways than ending the embedded R (as it is irreversible once R's shared library is loaded).
