### ISSUE TITLE
Error in unlink(f) when trying to install packages

### ISSUE THREAD

**Issue by adamhaber** [rpy2/rpy2#735]
I've written a small [library](https://github.com/adamhaber/pybrms/issues/3) (still WIP) that uses RPy2 to provide access to R's `brms` package (a widely used package for bayesian regression models) for Python users. The main file starts with:

```python 
import rpy2.robjects.packages as rpackages
from rpy2.robjects import default_converter, pandas2ri, numpy2ri, ListVector, DataFrame, StrVector
from rpy2.robjects.conversion import localconverter

try:
    brms = rpackages.importr("brms")
except:
    utils = rpackages.importr("utils")
    utils.chooseCRANmirror(ind=1)
    utils.install_packages(StrVector(('brms',)))
    brms = rpackages.importr("brms")
```
@sreedta8 just reported a bug [here](https://github.com/adamhaber/pybrms/issues/3#issuecomment-702451947) which seems to be RPy2 related and I wasn't able to reproduce on my machine. This might be related to multiple R versions being installed simultaneously, but I'm not sure.

This is the trace:
```
Get the same error as before:

--- Please select a CRAN mirror for use in this session ---
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Warning:
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: failed to download mirrors file (long vectors not supported yet: libcurl.c:952); using local file '/home/sreezach/anaconda3/envs/bayesian/lib/R/doc/CRAN_mirrors.csv'

WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in unlink(f) :
3 arguments passed to .Internal(unlink) which requires 4

RRuntimeError Traceback (most recent call last)
in 
2 from rpy2.robjects import StrVector
3 utils = rpackages.importr("utils")
----> 4 utils.install_packages(StrVector(('brms',)))
5 brms = rpackages.importr("brms")

~/anaconda3/envs/bayesian/lib/python3.8/site-packages/rpy2/robjects/functions.py in call(self, *args, **kwargs)
195 v = kwargs.pop(k)
196 kwargs[r_k] = v
--> 197 return (super(SignatureTranslatedFunction, self)
198 .call(*args, **kwargs))
199

~/anaconda3/envs/bayesian/lib/python3.8/site-packages/rpy2/robjects/functions.py in call(self, *args, **kwargs)
123 else:
124 new_kwargs[k] = conversion.py2rpy(v)
--> 125 res = super(Function, self).call(*new_args, **new_kwargs)
126 res = conversion.rpy2py(res)
127 return res

~/anaconda3/envs/bayesian/lib/python3.8/site-packages/rpy2/rinterface_lib/conversion.py in _(*args, **kwargs)
42 def _cdata_res_to_rinterface(function):
43 def _(*args, **kwargs):
---> 44 cdata = function(*args, **kwargs)
45 # TODO: test cdata is of the expected CType
46 return _cdata_to_rinterface(cdata)

~/anaconda3/envs/bayesian/lib/python3.8/site-packages/rpy2/rinterface.py in call(self, *args, **kwargs)
622 error_occured))
623 if error_occured[0]:
--> 624 raise embedded.RRuntimeError(_rinterface._geterrmessage())
625 return res
626

RRuntimeError: Error in unlink(f) :
3 arguments passed to .Internal(unlink) which requires 4
```

Operating System: Ubuntu 20.04 using KDE Plasma
Python Distribution: Anaconda 64-bit

Any help on how to solve this would be much appreciated!

**Comment by lgautier** [comment]
If you can't reproduce it, and conda is involved, the prior is strongly suggesting that this is yet an other conda packaging issue. I regularly have several R version installed on my machine, and I never ran into this problem. I am not using conda.

Unfortunately I do not have any suggestion beside trying if reinstalling R / rpy2 in conda solves the problem (I read reports of this solving issues, even if it did not cast a light on the reason why the issue appeared). I suppose that asking to try without conda would not be a useful recommendation to someone who already relies on it for its environment.

**Comment by BruceMD** [comment]
I had a similar issue. I painstakingly went through files and removed anything and everything related to R. Reinstalled what I needed through miniConda for rpy2 and that seemed to solve the problem

**Comment by lgautier** [comment]
Using conda is at the source of many issue reports. This seems to be a conda issue, as reinstalling seems to solve the issue.
