### ISSUE TITLE
Warning about "quartz symbol" when loading extension in JupyterLab on Windows

### ISSUE THREAD

**Issue by joelostblom** [rpy2/rpy2#738]
Several of my students reported this and I can reproduce as well. When I run `%load_ext rpy2.ipython`, I see this warning: 

```
C:\Users\joelo\miniconda3\envs\531\lib\site-packages\rpy2\robjects\packages.py:365: UserWarning: The symbol 'quartz' is not in this R namespace/package.
  warnings.warn(
```

To double check, I created in a new conda env and installed pip, pandas, and jupyterlab, and then rpy2 via pip. I see the same warning as above and in addition also this warning:

```
 "The symbol '%s' is not in this R namespace/package." % name
```

This is on Win 10 with the following package version:

```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : not installed
ipython          : 5.8.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.8
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.0.8
traitlets        : 5.0.5
```

```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again         
```

The same issue was reported at the end of https://github.com/rpy2/rpy2/issues/695

**Comment by lgautier** [comment]
Support of Windows is limited, the conda binary builds for rpy2 are awfully outdated nor supported by the project in any any way.
I'd suggest to report the issue to the conda maintainer, or try a more rpy2 installed from pip.

**Comment by joelostblom** [comment]
Thanks for the reply @lgautier. Please note that this warning occurs for me with the latest version of `rpy2` (3.3.6) installed via pip. The reason you see `miniconda` in the path above is because I used conda to create a virtual environment, but then used `pip` for installation of `rpy2` within this venv.

**Comment by BryceEarner** [comment]
I have the exact same issue

**Comment by xhsahs** [comment]
I also encountered this problem. Is there a solution now?

**Comment by cjcote** [comment]
This issue went away for me when I reinstalled rpy2 through conda "conda install -c conda-forge rpy2" instead of with pip.

**Comment by godoshian** [comment]
Hey, friends! I am having this issue too 😎 

It's strange because I think that it still works... like... I just executed "%R plot(iris$Species)" 🤔 but I am new so I don't really know what's going on

**Comment by SunMoonTechnology** [comment]
I have the exact same issue, and I solved it in the following way.

Change System Locale in Windows 10:
https://docs.microsoft.com/en-us/answers/questions/587680/where-can-i-find-34beta-use-unicode-utf-8-for-worl.html

**Comment by nuclearapple** [comment]
Same issue too. But everything seems to be working fine even with the warning. Just a bit annoying to see it.

**Comment by zqh137** [comment]
Same issues too, but seems everything goes well.
