### ISSUE TITLE
KeyError exception in _release method: _R_PRESERVED[addr]

### ISSUE THREAD

**Issue by Genarito** [rpy2/rpy2#741]
**Describe the issue or bug**

I'm using rpy2 to use WCGNA package. To prevent loading times I use a **global instance** which has all the used packages as attibutes:

```python
class PipelineManager(object):
    def __init__(self):
        self.WGCNA = rpackages.importr('WGCNA')
        self.reshape2 = rpackages.importr('reshape2')
        self.enableWGCNAThreads = ro.r['enableWGCNAThreads']

        # Enables automatic convertion from R arrays to Numpy's ndarray
        numpy2ri.activate()
```

I'm calling R functions in a function executed in a [ThreadPoolExecutor](https://docs.python.org/3.8/library/concurrent.futures.html#threadpoolexecutor). Reading [this section](https://rpy2.github.io/doc/v3.3.x/html/rinterface.html#multithreading) in the official docs of rpy2 about using this library in a multithreadng environment I'm using `openrlib.rlock` **only with the function which creates multiple threads**:

```python
with openrlib.rlock:
        res = self.WGCNA.corAndPvalue(values_1, values_2)

 # Just gets the column of values
correlation_chunk: np.ndarray = self.reshape2.melt(res.rx2['cor']).astype(cor_dtype)['value']
p_value_chunk: np.ndarray = self.reshape2.melt(res.rx2['p']).astype(p_value_dtype)['value']
```

But I'm getting this error:

> Exception ignored in: <function SexpCapsule.__del__ at 0x7f6b7c524e50>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 123, in __del__
>     raise e
>   File "/usr/local/lib/python3.8/dist-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 115, in __del__
>     _release(self._cdata)
>   File "/usr/local/lib/python3.8/dist-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 64, in _release
>     count = _R_PRESERVED[addr] - 1
> KeyError: 140098907189952

**To Reproduce**

The problem is hard to reproduce as It's running on a Django's Daphne server, which has the global instance of PipelineManager which has running the tasks in a ThreadPoolExecutor, the R code creates its own threads. I don't kwon if I'm missing something about using this library in a multithreading environment.

Versions:

- Python: 3.8.5
- rpy2: 3.2.6
- R: 3.6.2

**Comment by lgautier** [comment]
Wouldn't you have multiple processes in addition to multiple thread? (see https://stackoverflow.com/questions/63785478/multithreaded-flask-application-causes-stack-error-in-rpy2-r-process)

**Comment by Genarito** [comment]
I have a Django running in an ASGI server, so a lot of async, processes or threads could be involved (I don't know how Daphne works in low level). However, I've added the two lines of my example inside the `openrlib.rlock` block: 

```python
with openrlib.rlock:
        res = self.WGCNA.corAndPvalue(values_1, values_2)

        # Just gets the column of values
        correlation_chunk: np.ndarray = self.reshape2.melt(res.rx2['cor']).astype(cor_dtype)['value']
        p_value_chunk: np.ndarray = self.reshape2.melt(res.rx2['p']).astype(p_value_dtype)['value']
```

And the error disappeared, for the moment. I'm making some tests, if there's no error anymore I'll close the issue during, I hope, the next week.

**Comment by lgautier** [comment]
You do not have to put all calls to R under one same rlock, but all calls to R that could end up being concurrently called should be under an rlock.

**Comment by Genarito** [comment]
Hi @lgautier ,
First of all thank you for your response! Secondly, I don't know the process that involves reshaping in R (the line with reshape2 method), but the problem has not ocurred again, perhaps that function makes some tasks concurrently to improve performance

**Comment by lgautier** [comment]
`reshape2` is a call to an R function (in an R package). However, before the call itself is made few preparatory steps are necessary. Those steps are themselves calls to R's C API made by rpy2, and that sequence does not necessarily handle concurrency well. This is why it safer and recommended to wrap them in a rlock.
