### ISSUE TITLE
ggplot2 facet vars

### ISSUE THREAD

**Issue by ThePengwyn** [rpy2/rpy2#742]
Hi, new to rpy2 but fluent in both R and python.

when using facet_grid from ggplot2, in R it requires the fields to be wrapped by the function `vars` and takes the unquoted field name. When interacting with this in python I tried:

`ggplot2.vars("field")`, but this returns the error:
`AttributeError: module 'rpy2.robjects.lib.ggplot2' has no attribute 'vars'`

the issue is problematic in this situation

`p = p + ggplot2.facet_grid(
    rows="field1",
    cols="field2"
)`
returning the error:
`
RRuntimeError: Error: `rows` must be `NULL` or a `vars()` list if `cols` is a `vars()` list
Run `rlang::last_error()` to see where the error occurred.`

any help would be greatly appreciated thank you

**Comment by lgautier** [comment]
Thanks for the report. That function in the R package was added after my last check that the rpy2 mapping was complete. Revision 6e6fed4 now adds this in the dev branch (future 3.4.x series), and I will probably backport the change to the rpy2 3.3.x series.
