### ISSUE TITLE
Escape "%" or "."

### ISSUE THREAD

**Issue by fbemm** [rpy2/rpy2#743]
**Describe the issue or bug**

I am trying to use a R package with one parameter that contains a dot (.). 
I don't think that this is a bug, I just don't know how to escape symbols like "." or "%in%" properly.

**To Reproduce**

Code looks like this:

```
import rpy2
import rpy2.robjects.packages as rpackages
from rpy2.robjects.vectors import StrVector
import rpy2.robjects as ro
import rpy2.robjects.numpy2ri
rpy2.robjects.numpy2ri.activate()
utils = rpackages.importr('utils')
ape = rpackages.importr('ape')
clstutils = rpackages.importr('clstutils')
r = robjects.r
nr,nc = te_distance.shape
r_distance = ro.r.matrix(te_distance, nrow=nr, ncol=nc)
r_picked = clstutils.maxDists(r_distance, N=5, include.center = TRUE) 
range(1, r.nrow(r_distance)[0])]
r_label = ro.StrVector(label)
```

**Expected behavior**

I want to use 'include.center = TRUE'.

**Error**

```
  File "<ipython-input-15-341f40d8c3c4>", line 5
    r_picked = clstutils.maxDists(r_distance, N=5, include.center = TRUE) # How to escape . | %label = [ 'picked' if i in r_picked else 'unpicked' for i in range(1, r.nrow(r_distance)[0])]
                                                  ^
SyntaxError: keyword can't be an expression

```

Glad for any help!

**Comment by lgautier** [comment]
This is answered in the doc.

dot in parameter names: https://rpy2.github.io/doc/v3.3.x/html/robjects_functions.html
syntactically invalid Python names in R packages: https://rpy2.github.io/doc/v3.3.x/html/robjects_rpackages.html
