### ISSUE TITLE
dplyr and rlang conflit

### ISSUE THREAD

**Issue by MaelleB1407** [rpy2/rpy2#748]
Hello,

I'm trying to use dplyr with rpy2 but an error message appears.

`import rpy2.robjects.lib.dplyr as dp`

LibraryError: The symbol .env in the package "rlang" is conflicting with a Python object attribute

I tried to add the line of code given in #711 :
rlang = importr('rlang', robject_translations={'.env': '__env'})

But it still doesn't work...
I tried this line by putting it before and after the attempt to import dplyr.

`
rlang = importr('rlang', robject_translations={'.env': '__env'})
from rpy2.robjects.lib.dplyr import (filter,
                                     mutate,
                                     group_by,
                                     summarize)
`
and

`
from rpy2.robjects.lib.dplyr import (filter,
                                     mutate,
                                     group_by,
                                     summarize)
rlang = importr('rlang', robject_translations={'.env': '__env'})
`

Thanks for your help

**Comment by lgautier** [comment]
The fix should happen *in* `dplyr.py`.

If you update your `rpy2` to a recent release, this is already fixed: https://github.com/rpy2/rpy2/blob/RELEASE_3_3_6/rpy2/robjects/lib/dplyr.py#L11

I am closing this is normally already addressed. Reopen if I missed something.
