### ISSUE TITLE
Fix: situation.py cannot load i386 R installation when using 32-bit python

### ISSUE THREAD

**Issue by ghendergate** [rpy2/rpy2#750]
Attempting to import certain submodules of rpy2 within a 32-bit version of python (a PyCharm venv) with a 32-bit version of R raises an error:
![image](https://user-images.githubusercontent.com/55111299/99984574-221b4b80-2da5-11eb-9ef0-31394436ae52.png)

I have added rpy2/bin to PATH and my R installation to R_HOME. I have not installed x64-bit R, however, as shown above rpy2 attempts to load from the non-existent 'x64' folder. I have tested on R 3.6.2 and 4.0.4. The R 3.6.2 had both 32 and 64-bit versions installed, however I assume that this failed to load R.dll because my python installation is 32-bit.

I have narrowed down the cause to rpy2/situation.py function get_rlib_path, which does not check the python installation and hardcodes the 'x64' folder in all cases.

The fix:
Check the python installation to determine which R folder to use, for example: 
![image](https://user-images.githubusercontent.com/55111299/99985721-3744aa00-2da6-11eb-99e5-8266bacb22d4.png)

**Comment by lgautier** [comment]
Thanks for the report, and going through the trouble of working out a proposed fix.

Would you be able to make it a pull request (or a diff) by any chance? I don't have a Windows + 32-bit version of Python handy to test, and I'd hate to miss something by trying to work out changes from screenshots.

**Comment by ghendergate** [comment]
> Thanks for the report, and going through the trouble of working out a proposed fix.
> 
> Would you be able to make it a pull request (or a diff) by any chance? I don't have a Windows + 32-bit version of Python handy to test, and I'd hate to miss something by trying to work out changes from screenshots.

It was my pleasure - I needed it fixed!
I have created a pull request for this (#750), thanks for the suggestion.

**Comment by lgautier** [comment]
Merged. Thanks again.
