### ISSUE TITLE
write+execute memory for ffi.callback()

### ISSUE THREAD

**Issue by tongjie-w** [rpy2/rpy2#755]
Hi,
I'm a newbie analyst and trying to use rpy2 recently. Does anyone know how to solve the following issue?

from rpy2.robjects.packages import importr
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
~/Documents/glioma/rna_normalisation.py in 
----> 31 from rpy2.robjects.packages import importr

~/miniforge3/lib/python3.8/site-packages/rpy2/robjects/__init__.py in <module>
     14 from functools import partial
     15 import types
---> 16 import rpy2.rinterface as rinterface
     17 import rpy2.rlike.container as rlc
     18 

~/miniforge3/lib/python3.8/site-packages/rpy2/rinterface.py in <module>
      5 from typing import Union
      6 from rpy2.rinterface_lib import openrlib
----> 7 import rpy2.rinterface_lib._rinterface_capi as _rinterface
      8 import rpy2.rinterface_lib.embedded as embedded
      9 import rpy2.rinterface_lib.conversion as conversion

~/miniforge3/lib/python3.8/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in <module>
     10 from . import openrlib
     11 from . import conversion
---> 12 from . import embedded
     13 from . import memorymanagement
     14 

~/miniforge3/lib/python3.8/site-packages/rpy2/rinterface_lib/embedded.py in <module>
      5 import warnings
      6 from . import openrlib
----> 7 from . import callbacks
      8 
      9 ffi = openrlib.ffi

~/miniforge3/lib/python3.8/site-packages/rpy2/rinterface_lib/callbacks.py in <module>
     36 @ffi_proxy.callback(ffi_proxy._consoleflush_def,
     37                     _rinterface_cffi)
---> 38 def _consoleflush():
     39     try:
     40         consoleflush()

~/miniforge3/lib/python3.8/site-packages/rpy2/rinterface_lib/ffi_proxy.py in decorator(func)
     42     def decorator(func):
     43         if get_ffi_mode(_rinterface_cffi) == InterfaceType.ABI:
---> 44             res = _rinterface_cffi.ffi.callback(definition.callback_def)(func)
     45         elif get_ffi_mode(_rinterface_cffi) == InterfaceType.API:
     46             res = _rinterface_cffi.ffi.def_extern()(func)

MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

im using macOS big sur 11.0.1. I've checked the link but not very useful for me, for very ambiguous procedure :/ also apple community doesn't help at all (some tutorial suggested ) I'd very appreciate it if anyone can make it clear how to deal with it.
btw the cffi is 1.14

**Comment by lgautier** [comment]
This can happen with the ABI mode. Try installing with the API mode.

At the moment the Mac binaries are for OSX 10.14 (https://github.com/rpy2/rpy2/actions/runs/389388210)
You'll need to compile rpy2 from source, and for this a C compiler on your system (and may be Python headers).
To force rpy2 to install in API mode you can do:
```
RPY2_CFFI_MODE=API pip install rpy2
```

**Comment by tongjie-w** [comment]
Thanks! Works for me ;)
