### ISSUE TITLE
module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'

### ISSUE THREAD

**Issue by mcui123** [rpy2/rpy2#756]
I have a pandas dataframe that I would like to convert to R data.frame.

I am doing this in Jupyter Notebook and this is what I have done

```
import pandas as pd
cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Price': [22000,25000,27000,35000]
        }

df = pd.DataFrame(cars, columns = ['Brand', 'Price'])

# Load in python library to use R 

from rpy2.robjects.packages import importr
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri

# Load in R libraries 
pandas2ri.activate()

pandas2ri.py2ri(df)
```

I got the following error messages: ```'AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'```

I checked that my rpy2 version is 3.3.6, and my pandas version is 1.1.4.

I am wondering if this is due to some version issues?

Thanks so much for your help.

**Comment by mcui123** [comment]
Found a solution: 
```
ro.conversion.py2rpy(df)

```

Use this instead

**Comment by lgautier** [comment]
Avoid using the `activate()` function. It can break too easily. Use a local converter instead (see https://rpy2.github.io/doc/latest/html/generated_rst/pandas.html)

**Comment by mcui123** [comment]
@lgautier Thank you!

**Comment by econdavidzh** [comment]
> @lgautier Thank you!

Hello mcui123, Im haveing the same problem, but I'd like to know how did you export the converted object as a .rda file?

Thank you for your response.

**Comment by ghayward** [comment]
Hey @mcui123 and all -- 
Just found this in the Pandas docs, and it may be of use. It even has the `ro.conversion.py2rpy(pd_df)` example.
https://rpy2.github.io/doc/latest/html/generated_rst/pandas.html
Cheers!
G
