### ISSUE TITLE
RPY2 does not remove Rtmp folders

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#77]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/68) by Francesca Mazzoni (Bitbucket: [framazz](https://bitbucket.org/framazz), GitHub: [framazz](https://github.com/framazz)).**

----------------------------------------

Although the content of those folders gets deleted, the folders themselves are not, so /tmp gets filled up with Rtmp* folders.

(Debian package: python-rpy2
Architecture: amd64
Version: 2.1.9-1)

**Comment by hermidalc** [comment]
As of v3.1.0 issue still exists. In Linux if I execute the following line:
```python
import rpy2.robjects as robjects
```
In `/tmp` it creates an `Rtmp*` directory that doesn’t get cleaned up on exit.

**Comment by lgautier** [comment]
May this was lost in the move to `cffi` with rpy2-3.0.0.

**Comment by lgautier** [comment]
I can reproduce with the latest release.

There is a function in R's C API to cleanup. Calling it explicitly will remove the temp directory:
```python
import rpy2.rinterface as ri
ri.initr()  # The directory /tmp/Rtmp is created

ri.openrlib.rlib.R_CleanTempDir()  # the directory is deleted

```

**Comment by lgautier** [comment]
Terminating R (through `rpy2.rinterface_lib.embedded.endr()`) will call that function: https://github.com/rpy2/rpy2/blob/master/rpy2/rinterface_lib/embedded.py#L159

**Comment by lgautier** [comment]
Initializing R with `rpy2.rinterface.initr_simple()` instead of  `rpy2.rinterface.initr()` will ensure that `endr()` is called with the Python process exits:
https://github.com/rpy2/rpy2/blob/master/rpy2/rinterface.py#L970

**Comment by lgautier** [comment]
There is a fix here: https://github.com/rpy2/rpy2/pull/628
