### ISSUE TITLE
Debian 10: RRuntimeError: Error in dyn.load unable to load shared object '/usr/local/lib/R/library/tools/libs/tools.so'

### ISSUE THREAD

**Issue by Robbie-Palmer** [rpy2/rpy2#771]
**Describe the issue or bug**

Cannot import `robjects` from `rpy2`

**To Reproduce**

I am trying to build a Docker Image with both Python and R that uses rpy2 inside
I have taken the [r-ver image from Docker Hub](https://hub.docker.com/r/rocker/r-ver) with R version 3.6.3
The operating system for this image is `Debian GNU/Linux 10`
I have installed python using `RUN apt install python3 -y && apt install python3-pip -y`
Which installs python version 3.7.3
Both Python and R are 64-bit installations
Both Python and R are installed in their default debian locations (have not used conda or virtualenv since it is a docker image)
I have installed rpy2 version 3.4.2 via pip
When I open a Python session and run `from rpy2 import robjects` an error is thrown

**Error**

```
Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  libR.so: cannot open shared object file: No such file or directory
Warning message:
package "methods" in options("defaultPackages") was not found 
Error: package or namespace load failed for ‘utils’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/utils/libs/utils.so':
  libR.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘grDevices’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/grDevices/libs/grDevices.so':
  libR.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘graphics’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/grDevices/libs/grDevices.so':
  libR.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/grDevices/libs/grDevices.so':
  libR.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘methods’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  libR.so: cannot open shared object file: No such file or directory
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘grDevices’ in options("defaultPackages") was not found 
3: package ‘graphics’ in options("defaultPackages") was not found 
4: package ‘stats’ in options("defaultPackages") was not found 
5: package ‘methods’ in options("defaultPackages") was not found 
R[write to console]: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  libR.so: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/usr/local/lib/python3.7/dist-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/usr/local/lib/python3.7/dist-packages/rpy2/robjects/robject.py", line 70, in RObjectMixin
    __show = _get_exported_value('methods', 'show')
  File "/usr/local/lib/python3.7/dist-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/library/methods/libs/methods.so':
  libR.so: cannot open shared object file: No such file or directory

```

**Additional context**

The error message seems to suggest a missing DLL but this file does exist at this location and Python can find it which I have verified with:
```
from pathlib import Path
Path('/usr/local/lib/R/library/methods/libs/methods.so').exists()
# True
```
And just to double check
```
from os import path
path.exists('/usr/local/lib/R/library/methods/libs/methods.so')
# True
```

This DLL seems to be linked to R's `show` function but I have verified that it operates as expected from an R session
I commented out the lines that use the `show` function in `rpy/robjects/eobject.py` on the off chance that the issue was concentrated to a single DLL that mightn't be needed in many places but then I received the same error for a different DLL
`unable to load shared object '/usr/local/lib/R/library/tools/libs/tools.so'`

**Comment by lgautier** [comment]
For what is worth, rpy2's Docker image do not seem to that that issue (https://github.com/rpy2/rpy2-docker/blob/master/base/Dockerfile).

I suspect that the linker does not find R's shared library at runtime. Try adding to the environment variable `LD_LIBRARY_PATH` what it returned by the following command (to run after you install rpy2):
```
python -m rpy2.situation LD_LIBRARY_PATH
```

**Comment by korommatyi** [comment]
@lgautier's answer works for me. Would you care explaining what is this environment variable and why creating it solves the issue? 😄

**Comment by lgautier** [comment]
You'll likely find on the internet better explanations than I could write, and by people who know this more in depth than I do.

In a nutshell R is a shared library (`libR.so` in the beginning of the error message) that must be loaded at run time, when rpy2 is imported. The system might not necessarily know where is that library and `LD_LIBRARY_PATH` will indicates one or several paths where libraries should be looked for. An alternative to this, would be to use `ldconfig`. If your R is coming from a package manager (deb, rpm, etc...) this normally set up for you by the package maintainer.

**Comment by lgautier** [comment]
Issue #833 looked at this. There is a fix in the dev branch. The fix will be included in rpy2-3.5.0.

**Comment by slava-keshkov** [comment]
I still face this issue even after updating rpy2 to 3.5.0 and running the 
`python -m rpy2.situation LD_LIBRARY_PATH
`

I am using Dockerfile from rocker/tidyverse:4.0.4 and install rpy2 with pip

I have tried using rpy2 Dockerfile but I am unable to re-install R version there. The default version of R comes with 3.6 in that Dockerfile, and updating it to 4.0.4 works but then there are a lot of package conflicts due to older R version installations. Removing R and packages did not help.

Any suggestions to fix this? 


> python -m rpy2.situation LD_LIBRARY_PATH

**Comment by ThyssenQi** [comment]
Thank you very much. It's use for me!


> For what is worth, rpy2's Docker image do not seem to that that issue (https://github.com/rpy2/rpy2-docker/blob/master/base/Dockerfile).
> 
> I suspect that the linker does not find R's shared library at runtime. Try adding to the environment variable `LD_LIBRARY_PATH` what it returned by the following command (to run after you install rpy2):
> 
> ```
> python -m rpy2.situation LD_LIBRARY_PATH
> ```

**Comment by cvanhoutte** [comment]
> I still face this issue even after updating rpy2 to 3.5.0 and running the
> `python -m rpy2.situation LD_LIBRARY_PATH `

Same here. I'm running the rocker/r-ver:4.3 as my base apptainer image, and rpy2==3.5.12. But I got identical behaviour as what was originally reported in this ticket.

I resolved by following @lgautier's suggestion, but I also needed to do this step too before getting it working
export LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH

**Comment by lgautier** [comment]
> > I still face this issue even after updating rpy2 to 3.5.0 and running the
> > `python -m rpy2.situation LD_LIBRARY_PATH `
> 
> Same here. I'm running the rocker/r-ver:4.3 as my base apptainer image, and rpy2==3.5.12. But I got identical behaviour as what was originally reported in this ticket.
> 
> I resolved by following @lgautier's suggestion, but I also needed to do this step too before getting it working export LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH

Thanks. Do you mean that the following is not enough?

```sh
export LD_LIBRARY_PATH="$(python -m rpy2.situation LD_LIBRARY_PATH)":${LD_LIBRARY_PATH}
```

(see https://github.com/rpy2/rpy2?tab=readme-ov-file#issues-loading-shared-c-libraries)
