### ISSUE TITLE
Memory exhausted on import in Flask

### ISSUE THREAD

**Issue by russell-phe** [rpy2/rpy2#789]
Since updating to 3.4.3. When calling `import rpy2.robjects as ro` in the Flask app the following error occurs:

```
R[write to console]: Error: cons memory exhausted (limit reached?)
R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Process finished with exit code -1073741784 (0xC0000028)
Debugger connected.
```
Unable to progress any further. It was working up until updating rpy2 to the most recent version.

OS: Windows 10
Python: 3.8
R: 4.0.2
Flask: 1.1.2

**To Reproduce**

Call `import rpy2.robjects as ro` as part of running a flask app.

**Expected behavior**

`robjects` to be available.

**Error**
```
R[write to console]: Error: cons memory exhausted (limit reached?)
R[write to console]: Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Process finished with exit code -1073741784 (0xC0000028)
Debugger connected.
```

**Comment by russell-phe** [comment]
I have also tried 

```
from rpy2.rinterface_lib import openrlib
with openrlib.rlock:
    import rpy2.robjects as ro
    pass
```
with the same bug present.

**Comment by russell-phe** [comment]
Ok, I've managed to fix this by deleting some Rhistory files.

**Comment by lgautier** [comment]
I first thought that PR #780 created an issue. However, seeing this solved by deleting Rhistory files is quite puzzling.
