### ISSUE TITLE
M1 mac MemoryError calling rpy2 in jupyter notebook

### ISSUE THREAD

**Issue by selmling** [rpy2/rpy2#790]
**Describe the issue or bug**

Calling `%load_ext rpy2.ipython` in a jupyter notebook on a M1 mac results in the following error: 
```python
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

Expected behavior is to run without an error message.

Error message in full:
```python
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-22-fb23c6edefe4> in <module>
----> 1 get_ipython().run_line_magic('load_ext', 'rpy2.ipython')

~/miniforge3/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2342                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2343             with self.builtin_trap:
-> 2344                 result = fn(*args, **kwargs)
   2345             return result
   2346 

<decorator-gen-57> in load_ext(self, module_str)

~/miniforge3/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/miniforge3/lib/python3.9/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     31         if not module_str:
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 
     35         if res == 'already loaded':

~/miniforge3/lib/python3.9/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     78             if module_str not in sys.modules:
     79                 with prepended_to_syspath(self.ipython_extension_dir):
---> 80                     mod = import_module(module_str)
     81                     if mod.__file__.startswith(self.ipython_extension_dir):
     82                         print(("Loading extensions from {dir} is deprecated. "

~/miniforge3/lib/python3.9/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~/miniforge3/lib/python3.9/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/miniforge3/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

~/miniforge3/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/miniforge3/lib/python3.9/importlib/_bootstrap.py in _load_unlocked(spec)

~/miniforge3/lib/python3.9/importlib/_bootstrap_external.py in exec_module(self, module)

~/miniforge3/lib/python3.9/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/miniforge3/lib/python3.9/site-packages/rpy2/ipython/__init__.py in <module>
----> 1 from . import rmagic
      2 
      3 load_ipython_extension = rmagic.load_ipython_extension

~/miniforge3/lib/python3.9/site-packages/rpy2/ipython/rmagic.py in <module>
     53 # numpy and rpy2 imports
     54 
---> 55 import rpy2.rinterface as ri
     56 import rpy2.rinterface_lib.callbacks
     57 import rpy2.robjects as ro

~/miniforge3/lib/python3.9/site-packages/rpy2/rinterface.py in <module>
     11 from typing import Union
     12 from rpy2.rinterface_lib import openrlib
---> 13 import rpy2.rinterface_lib._rinterface_capi as _rinterface
     14 import rpy2.rinterface_lib.embedded as embedded
     15 import rpy2.rinterface_lib.conversion as conversion

~/miniforge3/lib/python3.9/site-packages/rpy2/rinterface_lib/_rinterface_capi.py in <module>
     10 from rpy2.rinterface_lib import openrlib
     11 from rpy2.rinterface_lib import conversion
---> 12 from rpy2.rinterface_lib import embedded
     13 from rpy2.rinterface_lib import memorymanagement
     14 

~/miniforge3/lib/python3.9/site-packages/rpy2/rinterface_lib/embedded.py in <module>
      5 import warnings
      6 from rpy2.rinterface_lib import openrlib
----> 7 from rpy2.rinterface_lib import callbacks
      8 
      9 ffi = openrlib.ffi

~/miniforge3/lib/python3.9/site-packages/rpy2/rinterface_lib/callbacks.py in <module>
     37 @ffi_proxy.callback(ffi_proxy._consoleflush_def,
     38                     openrlib._rinterface_cffi)
---> 39 def _consoleflush() -> None:
     40     try:
     41         consoleflush()

~/miniforge3/lib/python3.9/site-packages/rpy2/rinterface_lib/ffi_proxy.py in decorator(func)
     42     def decorator(func):
     43         if get_ffi_mode(_rinterface_cffi) == InterfaceType.ABI:
---> 44             res = _rinterface_cffi.ffi.callback(definition.callback_def)(func)
     45         elif get_ffi_mode(_rinterface_cffi) == InterfaceType.API:
     46             res = _rinterface_cffi.ffi.def_extern()(func)

MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

The installation of rpy2 passes with pip.

Related issue [here](https://github.com/Azure/azure-cli/issues/16907)

**Comment by lgautier** [comment]
The error might happen with the ABI mode. To use the API mode you will need to build the package in an environment that can compile C extension for Python packages. There are binaries for rpy2's API mode on pypi, but not for M1.

**Comment by selmling** [comment]
@lgautier thank you for getting back -- should I hang back until there are rpy2 API binaries for M1?

**Comment by lgautier** [comment]
I am relying on Github Actions to build binaries. M1 may take a while: https://github.com/actions/virtual-environments/issues/2187

Setting up your Mac to build C-extensions Python packages should be faster. A C compiler is probably enough.

**Comment by selmling** [comment]
For anyone else experiencing the same issue on an m1 chip, here's a workaround until m1 is supported:

Port your dataframes between python and R using your system's clipboard. 

Relevant commands in R and python:

- [pandas.DataFrame.to_clipbaord](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_clipboard.html)

- [R's read.clipbard](https://www.rdocumentation.org/packages/psych/versions/1.0-17/topics/read.clipboard)

**Comment by manto32bit** [comment]
Hi there, I came across with problems when I installed rpy2 on Mac with m1 chip. 
The R version I used was 4.1.0 alpha, and I installed rpy2 with "env ARCHFLAGS="-arch arm64" pip3 install rpy"
But when I from rpy2 import rojbects it came with:

"OSError: cannot load library '/Library/Frameworks/R.framework/Resources/lib/libR.dylib': dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 2): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
	/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib: mach-o, but wrong architecture"

How can I work around this? or could you share your installation with me? thanks a lot!!

**Comment by GaoJoJo** [comment]
https://mac.r-project.org/  
download R-4.1-branch arm64/R-4.1-branch.tar.gz (arm64, 75Mb)

> Hi there, I came across with problems when I installed rpy2 on Mac with m1 chip.
> The R version I used was 4.1.0 alpha, and I installed rpy2 with "env ARCHFLAGS="-arch arm64" pip3 install rpy2"
> But when I from rpy2 import rojbects it came with:
> 
> "OSError: cannot load library '/Library/Frameworks/R.framework/Resources/lib/libR.dylib': dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 2): no suitable image found. Did find:
> /Library/Frameworks/R.framework/Resources/lib/libR.dylib: mach-o, but wrong architecture
> /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libR.dylib: mach-o, but wrong architecture"
> 
> How can I work around this? or could you share your installation with me? thanks a lot!!

https://mac.r-project.org/  
download R-4.1-branch arm64/R-4.1-branch.tar.gz (arm64, 75Mb)

**Comment by hlzl** [comment]
Seems like the problem is upstream with [PyOpenSSL](https://github.com/pyca/pyopenssl/issues/873#issuecomment-778588689).

**Comment by selmling** [comment]
The following will correctly install rpy2 on an m1 mac:

`RPY2_CFFI_MODE=BOTH pip3 install rpy2`

**Comment by lgautier** [comment]
Do you mean that the issue was solved upstream? The environment variable would mean that both ABI and API work (there is no compilation involved with ABI mode).

**Comment by selmling** [comment]
I'm not entirely certain, but here's the issue that got me to that compiling line: [Security issue running on osx-arm64 (Mac Mini M1)](https://github.com/conda-forge/rpy2-feedstock/issues/79)

**Comment by lgautier** [comment]
Thanks. This is related. I wish that issue had pinged the project upstream (that is rpy2).

**Comment by v715** [comment]
> The following will correctly install rpy2 on an m1 mac:
> 
> `RPY2_CFFI_MODE=BOTH pip3 install rpy2`

That didn't work on my M1 but `RPY2_CFFI_MODE=API pip install rpy2` did. Thanks for this thread, saved me a bunch of headache!

**Comment by sveinugu** [comment]
> Thanks. This is related. I wish that issue had pinged the project upstream (that is rpy2).

Sorry. Not sure why I didn't. I probably assumed you had this figured out already and that it was more of a configuration issue for compilation in conda that could be quickly fixed there.

**Comment by TzuTingWei** [comment]
I ran into a similar issue on my Mac M1 pro with python 3.9.9 (conda)

`>>> import rpy2.rinterface_lib.callbacks
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cindywei/miniconda3/envs/citeseq/lib/python3.9/site-packages/rpy2/rinterface_lib/callbacks.py", line 12, in <module>
    from rpy2.rinterface_lib import conversion
  File "/Users/cindywei/miniconda3/envs/citeseq/lib/python3.9/site-packages/rpy2/rinterface_lib/conversion.py", line 12, in <module>
    from rpy2.rinterface_lib import _rinterface_capi as _rinterface
  File "/Users/cindywei/miniconda3/envs/citeseq/lib/python3.9/site-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 80, in <module>
    def _capsule_finalizer(cdata: FFI.CData) -> None:
  File "/Users/cindywei/miniconda3/envs/citeseq/lib/python3.9/site-packages/rpy2/rinterface_lib/ffi_proxy.py", line 44, in decorator
    res = _rinterface_cffi.ffi.callback(definition.callback_def)(func)
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks`

> > The following will correctly install rpy2 on an m1 mac:
> > `RPY2_CFFI_MODE=BOTH pip3 install rpy2`
> 
> That didn't work on my M1 but `RPY2_CFFI_MODE=API pip install rpy2` did. Thanks for this thread, saved me a bunch of headache!

And I have tried these two methods above but they both not working.

**Comment by lgautier** [comment]
@TzuTingWei : The error message suggests that rpy2 tries to use the ABI mode.

In a terminal try:
```bash
python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'
```
If the mode is not API, that means the environment variable `RPY2_CFFI_MODE` is not set or not set to the right value.

**Comment by TzuTingWei** [comment]
> @TzuTingWei : The error message suggests that rpy2 tries to use the ABI mode.
> 
> In a terminal try:
> 
> ```shell
> python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'
> ```
> 
> If the mode is not API, that means the environment variable `RPY2_CFFI_MODE` is not set or not set to the right value.

Thank you for the tip. But as I tried `RPY2_CFFI_MODE=API pip install rpy2` to set the correct parameter, the result from `python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'` is still `CFFI_MODE.ANY`.

**Comment by lgautier** [comment]
Environment variables set with a line are not exported to child process (other than the one on the line). The example below should be self-explanatory:

```bash
$ RPY2_CFFI_MODE=API python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'
CFFI_MODE.API
$ RPY2_CFFI_MODE=ABI python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'
CFFI_MODE.ABI
$ python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'
CFFI_MODE.ANY
```

You can either specify `RPY2_CFFI_MODE` each you run Python or use `export`:

```bash
$ export RPY2_CFFI_MODE=API
$ python -c 'import rpy2.situation as s; print(s.get_cffi_mode())'
CFFI_MODE.API
```

**Comment by amillner** [comment]
I was having issue calling rpy2 in jupyter notebook and followed the instructions here but now I'm getting a new error msg. This is a recently purchased M1 Mac using miniconda for Python install and separate R installation. 

This is the error msg 

```
ImportError: dlopen(/Users/user1/opt/miniconda3/lib/python3.9/site-packages/_rinterface_cffi_api.abi3.so, 0x0002): Library not loaded: /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib
  Referenced from: /Users/user1/opt/miniconda3/lib/python3.9/site-packages/_rinterface_cffi_api.abi3.so
  Reason: tried: '/usr/local/opt/pcre2/lib/libpcre2-8.0.dylib' (no such file), '/usr/local/lib/libpcre2-8.0.dylib' (no such file), '/usr/lib/libpcre2-8.0.dylib' (no such file)
```

I've tried installing pcre2 via homebrew but homebrew [uses /opt/homebrew on M1 rather than /usr/local](https://stackoverflow.com/questions/70983104/brew-installs-not-appearing-in-usr-local-bin). Also tried installing pcre2 via conda but not working. I'd appreciate any help. Thanks.

**Comment by maciematt** [comment]
I was getting the same `ffi.callback()` error, so I went ahead with `export RPY2_CFFI_MODE=API` followed by `pip install rpy2` and `python -m rpy2.rinterface`. It seemed like rpy2 was installed correctly, but that final command came back wth the following error:

```
(var-mod-bayes) matmac@Matts-MacBook-Pro oligo-var-fix % python -m rpy2.rinterface
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/var-mod-bayes/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/var-mod-bayes/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/var-mod-bayes/lib/python3.10/site-packages/rpy2/rinterface.py", line 16, in <module>
    from rpy2.rinterface_lib import openrlib
  File "/opt/homebrew/Caskroom/miniforge/base/envs/var-mod-bayes/lib/python3.10/site-packages/rpy2/rinterface_lib/openrlib.py", line 13, in <module>
    import _rinterface_cffi_api as _rinterface_cffi  # type: ignore
ModuleNotFoundError: No module named '_rinterface_cffi_api'
```

I got the same error in a Jupyter notebook (in VSCode) when I tried to run `%load_ext rpy2.python`.

**Comment by selmling** [comment]
[this post](https://stackoverflow.com/a/58617530/11360271) is helpful for me with M2 chip under python 3.11.
