### ISSUE TITLE
Consider implicit conversion of Series that contains both int and float

### ISSUE THREAD

**Issue by krassowski** [rpy2/rpy2#794]
**Is your feature request related to a problem? Please describe.**

It is often slightly annoying to see:

```
pandas2ri.py: Error while trying to convert the column "numeric". Fall back to string conversion. The error is: Series can only be of one type, or None (and here we have <class 'int'> and <class 'float'>).
```

when converting some pandas data frames. Pandas DataFrame might happen to contain a mix of integers and floats, as it seems not due to deliberate user action, but due to certain pandas operations (`melt()` in certain conditions, but I do not have a reproducible example). Deliberate example:

```python
from pandas import DataFrame

df = DataFrame({'numeric': [1, 1., 'a']}).iloc[:2]
df
```

> |    |   numeric |
> |---:|----------:|
> |  0 |         1 |
> |  1 |         1. |

```python
df.dtype
```

> numeric    object

```python
df.unique()
```

> array([1], dtype=object)

The following does not work:

```python
%R -i df
```

> pandas2ri.py: Error while trying to convert the column "numeric". Fall back to string conversion. The error is: Series can only be of one type, or None (and here we have <class 'int'> and <class 'float'>).

The following works:

```python
df_inferred = df.infer_objects()
%R -i df_inferred
```

**Describe the solution you'd like**

I would like to be able to smoothly convert `df` to R without having to call `infer_objects()`. Coercing to the safe (larger) type appears warranted, as this is the default behaviour of pandas and can be invoked using public API. For example see:

```python
df_auto_inferred = DataFrame({'numeric': [1, 1.]}).iloc[:2]
df_auto_inferred.dtypes
```

> numeric    float64

I think that it would be fine to make the conversion here, possibly displaying a warning about it, but I am not convinced that having it raise an error is warranted.

**Describe alternatives you've considered**

As an alternative, to help less experienced users, the error message could include a suggestion in this special case: "use `infer_objects()` method to normalize data types before conversion".

**Additional context**

- rpy2   3.4.3
- pandas   1.2.1

**Comment by lgautier** [comment]
Thanks for the report.

I am hesitant about calling `infer_objects`. Rpy2 is making the choice to raise exceptions
rather than create the kind of potential surprises at the root of tricky debugging by users. I might warm up to the idea, I am just careful (since I have never encountered that situation where int and floats end up mixed). For now I have implemented the alternative you suggest (add suggestion to use `infer_objects()` in the error message).

**Comment by lgautier** [comment]
The mention of infer_objects was added to the error message. This will be the fix for now. Automatic / implicit inference can be added in a custom conversion rule by a user.
