### ISSUE TITLE
strange thousands separator in IntVector

### ISSUE THREAD

**Issue by Emmadd** [rpy2/rpy2#797]
Hi, to me the thousands separator in the rpy2.robjects.IntVector seems a bit out of place. I've never seen it in R at least and it is confusing in my opinion. 

Reproduceble example:
import rpy2
import rpy2.robjects as robjects
robjects.IntVector([1000, 1])

Current behaviour:
In: robjects.IntVector([1000, 1])
Out: 
<rpy2.robjects.vectors.IntVector object at 0x7f8967e692d0> [RTYPES.INTSXP]
R classes: ('integer',)
[1,000, 1]

Expected behaviour:
[1000, 1]

Additional information:
R version 3.5.1 (2018-07-02) -- "Feather Spray" 
rpy2.__version__ '3.4.3'

**Comment by lgautier** [comment]
Yes. I agree that it turns out to be confusing.

**Comment by lgautier** [comment]
Fixed. Will be in release 3.5.0.

**Comment by Emmadd** [comment]
Cool! Thanks for contributing to this essential package!
