### ISSUE TITLE
python to R conversion

### ISSUE THREAD

**Issue by jaisonj708** [rpy2/rpy2#798]
It seems like we can convert R matrices to python NumPy arrays instantly, since no copying is necessary.

What about the other way around? Is it possible to generate an R matrix from a python NumPy array without copying?

**Comment by lgautier** [comment]
Unfortunately it is much more difficult because R does not plan for that scenario.

If bidirectional sharing of array structures is wanted, an in-memory Arrow array could work, or at least provide better performance than vanilla Python->R in rpy2. Check https://github.com/rpy2/rpy2-arrow

**Comment by lgautier** [comment]
Answered. Closing.
