### ISSUE TITLE
Request for documentation: how to use rpy2 with a non-system R (Windows) 

### ISSUE THREAD

**Issue by parlar** [rpy2/rpy2#800]
**Is your feature request related to a problem? Please describe.**
I would like to embed R in a Qt for Python application for use in Windows. However, I'm having problems figuring out how to make rpy2 use a non-system R. By setting R_HOME to the other R, I can connect to it but not import libraries. Setting R_LIBS_USER, R_LIBS_SITE, R_LIBS does not seem to help. Have been scanning the internet for a solution but so far without success.

**Describe the solution you'd like**
If it is possible, a description in the documentation on how a different (embeded) R can be used would be helpful. I suspect more people than me might find this useful too.

**Describe alternatives you've considered**
Skip rpy2. But rpy2 is very nice and it would be a shame not to use it, if possible.

**Comment by parlar** [comment]
I may have to make a reverse on my request (above). It turns out that something was might have been wrong with my R installations that may have caused the issues. I removed all of them and and reinstalled R-4.0.5.  I'm moving it around and rpy2 seems to connect just fine with it if I set R_HOME. Sorry.

**Comment by lgautier** [comment]
So it is resolved, correct? I am closing the issue. Reopen as needed.
