### ISSUE TITLE
The pop up window "R Graphics: Device 2 (ACTIVE)" has no response!

### ISSUE THREAD

**Issue by lingchen1991** [rpy2/rpy2#803]
`from rpy2 import robjects
from rpy2.robjects import Formula, Environment
from rpy2.robjects.vectors import IntVector, FloatVector
from rpy2.robjects.lib import grid
from rpy2.robjects.packages import importr, data
from rpy2.rinterface_lib.embedded import RRuntimeError
import warnings

rprint = robjects.globalenv.find("print")
stats = importr('stats')
grdevices = importr('grDevices')
base = importr('base')
datasets = importr('datasets')

grid.activate()

r = robjects.r
r.X11()

import time
from rpy2.robjects.packages import importr
from rpy2.robjects import r
from rpy2.robjects.lib import ggplot2
grdevices = importr('grDevices')
rprint = robjects.globalenv.find("print")
mtcars = data(datasets).fetch('mtcars')['mtcars']
pp = ggplot2.ggplot(mtcars) + \
     ggplot2.aes_string(x='wt', y='mpg', col='factor(cyl)') + \
     ggplot2.geom_point() + \
     ggplot2.geom_smooth(ggplot2.aes_string(group = 'cyl'), method = 'lm')

rprint(pp)
r.windows()
rprint(pp)
grdevices.dev_off()`

I used above codes in Spyder for plotting the example from your documentation but cannot work. A window of figure popped up and then froze and had no response.

Could anyone offer some solutions?

![image](https://user-images.githubusercontent.com/36982036/116369597-22c87a00-a83c-11eb-9a97-a2cec5235b7e.png)

**Comment by lgautier** [comment]
Updates to R interactive devices (such as resizing a plot window) require R to process its event loop, and by default rpy2 will only give back the hand to R when calling it. In your example above, after you plot your figure into an interactive window and, say, resize it and feel that it is frozen you can just do:

```python
# Does nothing useful but give momentarily back the control of the main thread to R
r('TRUE')
```
This should update your figure ("unfreeze" it, if you will).

Now this is likely not optimal if you need frequent updates. In that case there are utilities to process events. It is a bit buried in the documentation but it is there:
https://rpy2.github.io/doc/v3.4.x/html/interactive.html#interactive-reventloop
https://rpy2.github.io/doc/v3.4.x/html/rinterface.html#processing-interactive-events

**Comment by lgautier** [comment]
Closing. Reopen if there is a bug.
