### ISSUE TITLE
RJDBC package won't work

### ISSUE THREAD

**Issue by AlexanderKUA** [rpy2/rpy2#808]
**Describe the issue or bug**

After installation of RJDBC package without issues(or warnings), appropriate package can't be loaded.

**To Reproduce**

```
import rpy2.robjects as ro
from rpy2.robjects.packages import importr

utils = importr('utils')
print(utils.install_packages("RJDBC", dep=True, repos = "http://cran.us.r-project.org", verbose=True))

print(ro.r('''
library(RJDBC)
'''))
```

**Expected behavior**
Package should work normally

**Error**
R[write to console]: Error in library(RJDBC) : there is no package called ‘RJDBC’

R[write to console]: In addition: 
R[write to console]: Warning messages:

R[write to console]: 1: 
R[write to console]: In (function (pkgs, lib, repos = getOption("repos"), contriburl = contrib.url(repos,  :
R[write to console]: 
 
R[write to console]:  installation of package ‘rJava’ had non-zero exit status

R[write to console]: 2: 
R[write to console]: In (function (pkgs, lib, repos = getOption("repos"), contriburl = contrib.url(repos,  :
R[write to console]: 
 
R[write to console]:  installation of package ‘RJDBC’ had non-zero exit status

**Additional context**

Both packages (RJDBC and rJava) can't be found in lib path: 
`.libPaths(): /home/ec2-user/anaconda3/envs/python3/lib/R/library`
In R language kernel both packages work as expected:
`.libPaths(): /home/ec2-user/anaconda3/envs/R/lib/R/library`

My environment SageMaker instance with:

Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) \n[GCC 9.3.0]
---
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2018.03

Matrix products: default
BLAS/LAPACK: /home/ec2-user/anaconda3/envs/python3/lib/libopenblasp-r0.3.12.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods  
[8] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3

**Comment by lgautier** [comment]
I am assuming that this is a dynamic linking issue like about all conda issues are. The dev version infers dynamic linking from the R in the path. This should solve this kind of issue. Closing for now.
