### ISSUE TITLE
RParsingError: Parsing status not OK - PARSING_STATUS.PARSE_ERROR

### ISSUE THREAD

**Issue by Liu-Yanran** [rpy2/rpy2#813]
I am testing some very simple code and I often see this error messages when using the %%R magic in the last cell where I use ggplot.

**To Reproduce**
%load_ext rpy2.ipython
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'cups_of_coffee': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    'productivity': [2, 5, 6, 8, 9, 8, 0, 1, 0, -1]
})
df.transpose()

%%R -i df
library(ggplot2)
ggplot(df, aes(x=reorder(cups_of_coffee,productivity), y=productivity)) + geom_col() + coord_flip()

**Error**
RParsingError: Parsing status not OK - PARSING_STATUS.PARSE_ERROR
---------------------------------------------------------------------------
RParsingError                             Traceback (most recent call last)
<ipython-input-5-f6b614741c8b> in <module>
----> 1 get_ipython().run_cell_magic('R', '-i df', 'library(ggplot2)\r\nggplot(df, aes(x=reorder(cups_of_coffee,productivity), y=productivity)) + geom_col() + coord_flip()\n')

C:\Software\anaconda\envs\work\lib\site-packages\IPython\core\interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2397             with self.builtin_trap:
   2398                 args = (magic_arg_s, cell)
-> 2399                 result = fn(*args, **kwargs)
   2400             return result
   2401 

<decorator-gen-122> in R(self, line, cell, local_ns)

C:\Software\anaconda\envs\work\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

C:\Software\anaconda\envs\work\lib\site-packages\rpy2\ipython\rmagic.py in R(self, line, cell, local_ns)
    761                     return_output = False
    762             else:
--> 763                 text_result, result, visible = self.eval(code)
    764                 text_output += text_result
    765                 if visible:

C:\Software\anaconda\envs\work\lib\site-packages\rpy2\ipython\rmagic.py in eval(self, code)
    266             try:
    267                 # Need the newline in case the last line in code is a comment.
--> 268                 value, visible = ro.r("withVisible({%s\n})" % code)
    269             except (ri.embedded.RRuntimeError, ValueError) as exception:
    270                 # Otherwise next return seems to have copy of error.

C:\Software\anaconda\envs\work\lib\site-packages\rpy2\robjects\__init__.py in __call__(self, string)
    435 
    436     def __call__(self, string):
--> 437         p = rinterface.parse(string)
    438         res = self.eval(p)
    439         return conversion.rpy2py(res)

C:\Software\anaconda\envs\work\lib\site-packages\rpy2\rinterface_lib\conversion.py in _(*args, **kwargs)
     43 def _cdata_res_to_rinterface(function):
     44     def _(*args, **kwargs):
---> 45         cdata = function(*args, **kwargs)
     46         # TODO: test cdata is of the expected CType
     47         return _cdata_to_rinterface(cdata)

C:\Software\anaconda\envs\work\lib\site-packages\rpy2\rinterface.py in parse(text, num)
    101     robj = StrSexpVector([text])
    102     with memorymanagement.rmemory() as rmemory:
--> 103         res = _rinterface._parse(robj.__sexp__._cdata, num, rmemory)
    104     return res
    105 

C:\Software\anaconda\envs\work\lib\site-packages\rpy2\rinterface_lib\_rinterface_capi.py in _parse(cdata, num, rmemory)
    650     # PARSE_EOF
    651     if status[0] != openrlib.rlib.PARSE_OK:
--> 652         raise RParsingError('Parsing status not OK',
    653                             status=PARSING_STATUS(status[0]))
    654     return res

RParsingError: Parsing status not OK - PARSING_STATUS.PARSE_ERROR

**Comment by krassowski** [comment]
Cross-ref https://stackoverflow.com/questions/68055242/how-do-i-solve-the-parsing-error-when-using-rpy2.

I wonder if this could be something about Windows-style `\r\n` new lines. It works well on Ubuntu:

![Screenshot from 2021-06-20 12-23-52](https://user-images.githubusercontent.com/5832902/122672293-caba4e00-d1c2-11eb-9835-351d4a78ed67.png)

**Comment by Liu-Yanran** [comment]
> Cross-ref https://stackoverflow.com/questions/68055242/how-do-i-solve-the-parsing-error-when-using-rpy2.
> 
> I wonder if this could be something about Windows-style `\r\n` new lines. It works well on Ubuntu:
> 
> ![Screenshot from 2021-06-20 12-23-52](https://user-images.githubusercontent.com/5832902/122672293-caba4e00-d1c2-11eb-9835-351d4a78ed67.png)

It's possible. Is there a way around this?
Forgot to mention that I tested it on Google Colab and it worked well.

**Comment by Liu-Yanran** [comment]
> Cross-ref https://stackoverflow.com/questions/68055242/how-do-i-solve-the-parsing-error-when-using-rpy2.
> 
> I wonder if this could be something about Windows-style `\r\n` new lines. It works well on Ubuntu:
> 
> ![Screenshot from 2021-06-20 12-23-52](https://user-images.githubusercontent.com/5832902/122672293-caba4e00-d1c2-11eb-9835-351d4a78ed67.png)

**Comment by Liu-Yanran** [comment]
A work around is something like this:

get_ipython().run_cell_magic(
    "R",
    "-i df",
    '''
    library(ggplot2)
    ggplot(df, aes(x=reorder(cups_of_coffee,productivity), y=productivity)) + 
    geom_col() + 
    coord_flip()
    '''
)

Since this is not a rpy2 issue I will close it.
