### ISSUE TITLE
Some code does not work when using python style

### ISSUE THREAD

**Issue by liuzj039** [rpy2/rpy2#815]
**Describe the issue or bug**

Thank developers for bringing such a powerful tool.
I recently tried to use rpy2 to call the R package Seurat to complete some analysis. When the code is R style, it does a great job. But when using python style, it will keep taking CPU and won't finish.

**To Reproduce**

```
### initialization
import rpy2
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import numpy2ri, pandas2ri
from rpy2.robjects.conversion import localconverter
R = ro.r

import pandas as pd
import numpy as np
seurat = importr('Seurat')

### data preparation
df = pd.DataFrame(np.ones((1000, 5000)))
with localconverter(ro.default_converter + numpy2ri.converter + pandas2ri.converter):
    dfR = ro.conversion.py2rpy(df)
seuR_test = R.CreateSeuratObject(dfR)

### R style
ro.globalenv['seuR_test'] = seuR_test
R("seuR_test <- ScaleData(seuR_test)") # take about 2 seconds

### python style
seuR_test = seurat.ScaleData(seuR_test) # take up CPU but never finish

```

**Comment by liuzj039** [comment]
With python style, it finally finished after running for over one hour.

**Comment by lgautier** [comment]
This is not necessarily a bug in `rpy2`. My first sentiment is that it is a peculiarity of the `Seurat` package, and likely an issue with it, although admittedly triggered by an edge case.

In the following your data structure bound to `seuR_test` in Python will have its conversion to R bound to an R symbol `seuR_test` ( see https://rpy2.github.io/doc/v3.4.x/html/robjects_environments.html#environments):

```python
### R style
ro.globalenv['seuR_test'] = seuR_test
R("seuR_test <- ScaleData(seuR_test)") # take about 2 seconds
```

In the following your data structure `seurR_test` in Python will not be bound to an R symbol but its conversion will be passed as an anonymous data structure (see https://rpy2.github.io/doc/v3.4.x/html/rinterface.html#r-space-and-python-space):

```python
### python style
seuR_test = seurat.ScaleData(seuR_test) # take up CPU but never finish
```

What is likely happening is that the function in `Seurat` will try to do something like building a plot label or something else with the unevaluated R expression passed as a an argument. In the case of an anonymous data structure, the expression can be very large as it will list all data items and values in the structure. This can cause the compute overhead you are experiencing. Ideally `Seurat` should be able to handle gracefully anonymous data structures. In the meantime `rpy2` has something to help work around the issue: https://rpy2.github.io/doc/v3.4.x/html/robjects_environments.html#environments-as-temporary-local-contexts

**Comment by lgautier** [comment]
I agree that this is a quirk, but it is not an rpy2 bug. I am closing this. Reopen if I got it wrong.
