### ISSUE TITLE
as.factor, R function does not work.

### ISSUE THREAD

**Issue by EIzquierdo** [rpy2/rpy2#817]
I'm using rpy in a Windows 10 OS using Paycharm v2018.2.2
A previous version of rpy2 (exactly 2.9.4) the function as.factor (including in base package of R) worked and I could use RRF package training random forest as classifier with the following code:

```python
import rpy2.robjects as robjects
as_factor = robjects.r['as.factor']
from rpy2.robjects.package import importr
RRF = importr('RRF)
from rpy2.objects import numpy2ri
numy2ri.activate()

rf = RRF.RRF(robjects.Vector(X_train), as_factor(robjects.Vector(Y_train)), flagReg=0)
```
where X_train and Y_train are numpy array float 64. 

However, for the new version of rpy2 (3.4.4), I changed the code to:
```python
import rpy2.robjects as robjects
as_factor = robjects.r['as.factor']
from rpy2.robjects.package import importr
RRF = importr('RRF)
rf = RRF.RRF(X_train, as_factor(Y_train), flagReg=0) 
```

the function as.factor seems that it does not work and therefore, the random forest works as regressor and not as classifier. I try different options and I could make work as unsupervised method but never as classifier. I would like to know if something there is something wrong.

Thanks in advance.

**Comment by lgautier** [comment]
Your rpy2 code is changing in several places between your two versions, and I don't that it is possible to tell what is going on without knowing how `Y_train` is created. What seems likely is that you end up with a numerical vector rather than a factor vector on the R side, and the random forest fitting function will switch to regression rather than classification.

The R function `as.factor` works as advertised otherwise:
```python
>>> as_factor(rpy2.robjects.vectors.StrVector(['a', 'b', 'c']))
<rpy2.robjects.vectors.FactorVector object at 0x7fb4372fbb80> [RTYPES.INTSXP]
R classes: ('factor',)
[a, b, c]
```

Note that the rpy2 class can be used to create instances:
```python
>>> import rpy2.robjects.vectors as vectors
>>> vectors.FactorVector(['a', 'b', 'c']) 
<rpy2.robjects.vectors.FactorVector object at 0x7fb440a2e980> [RTYPES.INTSXP]
R classes: ('factor',)
[a, b, c]
```

**Comment by EIzquierdo** [comment]
Thank you very much for your answer, it helped me a lot.
Y_train is a numpy array float64 and X_train is numpy array 2D float 64. Guided by your answer, I solved the problem. I write here the solution, just in case someone needs it:
rf = RRF.RRF(robjects.r.matrix(X_train, nrow=1600, ncol=204), robjects.vectors.FactorVector(Y_train), flagReg=0)
But Y_train has to be a list of string elements now.
