### ISSUE TITLE
partial argument match of 'quiet' to 'quietly'

### ISSUE THREAD

**Issue by bersbersbers** [rpy2/rpy2#821]
1. Use `.Rprofile` with
```R
options(
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE,
)
```

2. Run
```shell
python -c "import rpy2.robjects as robjects"
```

Gives
```
R[write to console]: Warning message:

R[write to console]: In (function (package, lib.loc = NULL, quietly = FALSE, warn.conflicts,  :
R[write to console]: 
 
R[write to console]:  partial argument match of 'quiet' to 'quietly'
```

Supposedly related: https://github.com/rpy2/rpy2/blob/384dddcba29aab774d4657c1c895150524a0c30f/rpy2/robjects/methods.py#L14-L15

**Comment by lgautier** [comment]
Indeed. Thanks. Fixed in the dev branch. I can backport to current release series if a blocker on your end.

**Comment by bersbersbers** [comment]
Thanks - no need to backport, I can easily ignore the warning ;)
