### ISSUE TITLE
Functionality to check the version / release history of an R package

### ISSUE THREAD

**Issue by sglambert** [rpy2/rpy2#829]
**Is your feature request related to a problem? Please describe.**
There is no functionality to check the version / release history of an R package. I can check if I have a package installed, but not if it's the most up-to-date version, or if it's the version I want.

**Describe the solution you'd like**
I'd like the ability to check the version / release history of an R package. 

**Describe alternatives you've considered**
I could get the package version from rpy2 and then cross reference that with the package version on github.

**Additional context**
This is what my code looks like:

`def get_source_package(self, package_name):
        
        # Check if R package is installed. If it is installed, import it
        # I'd also like to be able to check if the package is up-to-date here 
        # and if not, install a particular version.
        if packages.isinstalled(package_name):
            self.source_package = packages.importr(package_name)
            return self.source_package

        # Check if R package is installed. If not, install and then import it
        else:
            utils = packages.importr('utils')
            utils.chooseCRANmirror(ind=1)
            utils.install_packages(package_name)
            self.source_package = packages.importr(package_name)
            return self.source_package`

**Comment by lgautier** [comment]
It is possible to check the version of an R package, either by calling R (exercise left to the reader) or using the attribute `__version__` in Python:

```python
dplyr = importr('dplyr')
dplyr.__version__
```
(used here https://github.com/rpy2/rpy2/blob/master/rpy2/robjects/lib/dplyr.py#L21)

Checking whether a package is the latest version on an R package repository can through calling R few R functions. Starting with `utils::old.packages` might be the easiest.

```python
utils = importr('utils')
old_packs = utils.old_packages()
if package_name in old_packs.rx(True, 1):
    # install latest version of the R package
    pass
rpack = importr(package_name)
```

That's not an issue with rpy2 though. Usage issue should be asked on a user forum or similar (e.g., StackOverflow).
