### ISSUE TITLE
Interrupting long-running compute in R

### ISSUE THREAD

**Issue by cgc** [rpy2/rpy2#831]
I've run into issues in Python scripts where I'm unable to interrupt long-running compute in R (fitting a hierarchical model on a large dataset, for example). I'd expect to be able to interrupt the script using control-C or a SIGINT signal, but can't. In the test case for process interruption (`testInterruptR`) the infinite loop tested returns control back to the Python process periodically with `Sys.sleep()`, but that's not really an option when I'm doing model fitting using an existing library.

I don't understand the limitations of signals in these embedded contexts, so I can totally see how this isn't really a bug, but just part of how it works for embedded code. That's at least my sense from this SO post: https://stackoverflow.com/a/33652496. However, given that I see logs for `KeyboardInterrupt` in the below sample I assume R is checking for events appropriately, which makes me curious if there's any way to optionally halt the embedded R process from `_processevents` or some downstream site.

**To Reproduce**
I'm on Mac 10.15.7, Python 3.9.7, Rpy2 3.4.5

```bash
$ cat test.py
import rpy2.robjects as ro
ro.r("""
writeLines('loop for 5 seconds. Try control-C now.')
start = Sys.time()
while (Sys.time() < start + 5) {}
writeLines('done with loop')
""")
$ python test.py
loop for 5 seconds. Try control-C now.
^CException ignored from cffi callback <function _processevents at 0x10eeca8b0>:
Traceback (most recent call last):
  File "/Users/carlos/pu/tmp/rpy2hang/env/lib/python3.9/site-packages/rpy2/rinterface_lib/callbacks.py", line 277, in _processevents
    try:
  File "/Users/carlos/pu/tmp/rpy2hang/env/lib/python3.9/site-packages/rpy2/rinterface.py", line 87, in _sigint_handler
    raise KeyboardInterrupt()
KeyboardInterrupt: 
done with loop
$
```

**Expected behavior**

The KeyboardInterrupt should halt the R interpreter instead of just logging the `KeyboardInterrupt`.

**Comment by lgautier** [comment]
Note: a PR to fix this was submitted by @cgc (PR #832 ).

**Comment by lgautier** [comment]
My understanding is that R is periodically checking for interrupt events at the C level. This is not a given for C extensions in R packages though. The C must call a function in the R API at what the extension finds to be suitable points (see - https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Allowing-interrupts).

I do not know if the Python side of this can override the R mechanism, and how bad it can leaves things in.

**Comment by cgc** [comment]
Since my above code doesn't go into a C extension (it is just doing a while loop), I spent a little time trying to understand how interrupts propagate with embedded R. I have a proposed solution in PR #832 now that seems to work well. With the proposed fix, I can now successfully interrupt `while(TRUE){}` during embedded execution in rpy2. As you note, this sort of fix doesn't by itself make C-extensions work, however. It also seems that this sort of solution might not be able to halt [subprocesses in R](https://github.com/rstudio/rstudio/issues/2565). But, this does seem to fix my above issue with long-running compute. Here's some of the justification/relevant code I used for the PR:

When R is typically initialized, signal handlers are set with `init_signal_handlers` in [src/main/main.c](https://github.com/wch/r-source/blob/430360aa394b02046dd7175c0fc55e347e947f80/src/main/main.c#L654-L681). However, it seems pretty typical when embedding R to disable these default signal handlers by setting `R_SignalHandlers = 0`, the approach rpy2 takes, which is also in [Rstudio](https://github.com/rstudio/rstudio/blob/51009f4cff7b0f45f9bd8762d7c0514b0de537bd/src/cpp/r/session/REmbeddedPosix.cpp#L59-L76), [Rcall.jl](https://github.com/JuliaInterop/RCall.jl/blob/52a97c561f98e5a8274da3c610af86bc75b1e41c/src/setup.jl#L65), and hinted at in the [R extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Threading-issues).

Based on a quick skim of the R source code & Rstudio code for interrupt handling, it seems like a reasonable solution might simply set interrupt flags on the R instance that are handled in the R event loop. The interrupt flag in Mac/Unix is `R_interrupts_pending`, which is set in the [default interrupt handler](https://github.com/wch/r-source/blob/68ecee90f8fee6f3ba607d39575333dd1d84321b/src/main/main.c#L432-L436). It's checked periodically throughout the R codebase, and in particular seems to be checked in `R_CheckUserInterrupt`, called out in the R extension manual as being critical for allowing interrupts to propagate. In the [implementation of `R_CheckUserInterrupt`](https://github.com/wch/r-source/blob/68ecee90f8fee6f3ba607d39575333dd1d84321b/src/main/errors.c#L137-L155), when `R_interrupts_pending` is set, `onintr()` is called, which interrupts the R process. From a quick read, Rstudio uses this flag to interrupt [its embedded R process](https://github.com/rstudio/rstudio/blob/2853a5/src/cpp/r/RExec.cpp#L590-L599).

On the Windows side, it seems there's an analogous flag `UserBreak` that's [set by Rstudio](https://github.com/rstudio/rstudio/blob/2853a5/src/cpp/r/RExec.cpp#L590-L599) and used by R, both [when handling the interrupt](https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/gnuwin32/psignal.c#L134-L163) and [in actually interrupting R in run.c and system.c](https://github.com/wch/r-source/search?q=userbreak)).

**Comment by lgautier** [comment]
Thanks for the report and PR. The PR is merged, so I am closing this. Reopen if this was premature.
