### ISSUE TITLE
Documentation on rpy2.robjects.r.summary object

### ISSUE THREAD

**Issue by mauriceling** [rpy2/rpy2#843]
Hi all,

I have the following code:
```
>>> import rpy2
>>> rpy2.__version__
'3.4.5'
>>>
>>> import pandas as pd
>>> from rpy2 import robjects as ro
>>> from rpy2.robjects import pandas2ri
>>> pandas2ri.activate()
>>> R = ro.r
>>> pd.__version__
'1.1.5'
>>>
>>> df = pd.DataFrame({'x': [1,2,3,4,5],
...                    'y': [2,1,3,5,4],
...                    'z': [1,2,5,3,4]})
>>> model = R.lm('y ~ x + z', data=df)
>>> print(R.summary(model).rx2("fstatistic"))
[1.83333333 2.         2.        ]
>>> print(R.summary(model).rx2("coefficients"))
[[ 0.70588235  1.49045405  0.47360222  0.68244633]
 [ 0.88235294  0.58823529  1.5         0.27239312]
 [-0.11764706  0.58823529 -0.2         0.85997199]]
>>>
```

Can I ask whether there is documentation on rpy2.robjects.r.summary object (i.e., ```R.summary(model)```) to pull the results out from? For example, what options in rx2()? And how to read the results?

Thanks
Maurice

**Comment by lgautier** [comment]
The issue tracker should be used to track issues with the software. User question will be better answer on StackOverflow (or forums & mailing-lists you'd identify).

`rpy2` performs a dynamic creation of Python docstrings from the corresponding R documentation when using `importr`. The documentation should answer your questions or provide a good starting point.

https://rpy2.github.io/doc/v3.4.x/html/generated_rst/introduction_nb.html#help-on-a-topic-within-a-given-package-or-currently-loaded-packages

https://rpy2.github.io/doc/v3.4.x/html/introduction.html#linear-models
