### ISSUE TITLE
Build OSX wheels for python3.9 and python3.10

### ISSUE THREAD

**Issue by Thijss** [rpy2/rpy2#846]
**Is your feature request related to a problem? Please describe.**
I have a lot of trouble building the package from source on OSX systems.
Thankfully there are wheels available for OSX.
However, the wheels are only available for Python 3.6, 3.7 & 3.8.

**Describe the solution you'd like**
It would be nice to also have wheels for Python 3.9 and 3.10

Additionally, the python 3.6 wheel should perhaps be dropped in a future release, since Python 3.6 is now officially deprecated

**Describe alternatives you've considered**
My alternative is installing `rpy2` from source. So far, I've not been able to make that work on my Macbook. Until then, I'm stuck with Python 3.8 + wheel

**Comment by Thijss** [comment]
seems that `master` branch already has support for 3.9 wheels. 
When is the next release scheduled?

**Comment by lgautier** [comment]
I had hoped to release at the very end of last year. I still hope to release "soon".

Python 3.6 is dropped from the builds (https://github.com/rpy2/rpy2/blob/master/.github/workflows/pythonpublish.yml#L21).

**Comment by lgautier** [comment]
Python 3.10 is added to the test/build matrices in PR #853.

**Comment by lgautier** [comment]
The wheels are built through CI with PR #853. They will need to be uploaded pypi when the next release happens.
