### ISSUE TITLE
ValueError: openrlib.R_HOME cannot be None. happens when I import from Jupyter Notebook

### ISSUE THREAD

**Issue by iadubovoy** [rpy2/rpy2#858]
**Describe the issue or bug**

I import rpy2 and that works fine, but when I import any three of the other lines below, I get the error. When I import the same lines in the terminal or Spyder, they import fine. It seems to be an error that is only with Jupyter and rpy2.

**To Reproduce**

I am on macOS M1, and I am using Conda to install everything. I create an environment with the libraries I am using for my project. I am using Jupyter to run my code.

I use the following code to create my environment:

<i>conda create --name myenv python=3.9 pygraphviz pandas ipykernel readline rpy2=3.4.5</i>

**Expected behavior**
It should be importing all four lines below.

**Error**
ValueError: openrlib.R_HOME cannot be None.

**Additional context**
<img width="839" alt="1DFD77FD-11DB-4E64-9724-679987D2DFFE" src="https://user-images.githubusercontent.com/70456827/159104016-3a581359-cbc7-4636-98a4-d661b731eaf1.png">

**Comment by iadubovoy** [comment]
For anyone else who may come across this error, I fixed it by installing r-irkernel and starting Notebook with this environment.

**Comment by lgautier** [comment]
conda and its packages is at the source of a few issues. The best is to report the problem to conda and/or the maintainers of the conda package for rpy2.
