### ISSUE TITLE
Windows conda Rpy2 version

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#86]
**[Original report](https://bitbucket.org/rpy2/rpy2/issue/577) by germayne (Bitbucket: [germayne](https://bitbucket.org/germayne), GitHub: [germayne](https://github.com/germayne)).**

----------------------------------------

Hi, i am currently on windows and using conda. The easiest way for me to install rpy2 is to do it through conda. However, there are some bug fixes that are on the newer 3.0.X version. Is there anyway i can upgrade to those version? For example, bugs that i have are the jupyter output not printing : [https://stackoverflow.com/questions/38438931/jupyter-rpy2-outputs-to-command-prompt-instead-of-notebook-cell](https://stackoverflow.com/questions/38438931/jupyter-rpy2-outputs-to-command-prompt-instead-of-notebook-cell)  
  
Conda version installed is the latest from conda [https://anaconda.org/r/rpy2](https://anaconda.org/r/rpy2)

**Comment by stonebig** [comment]
Until cgohlke succeeds to provide a rpy2-3.2.x, hope is limited.

**Comment by lgautier** [comment]
The community of Windows users could also try to lift a finger to help itself...

Since release 3.0.0 `rpy2` is using `cffi` and does not strictly require compiling in order to work (it can either use `cffi`'s ABI or API mode), and a stub for an intialization of the embedded library on Windows was written with a call for anyone with interest in Windows to help finish it (https://github.com/rpy2/rpy2/blob/master/rpy2/rinterface_lib/embedded_mswin.py).

**Comment by stonebig** [comment]
small question: is now the official rpy2 repo on github ? it may help to grab some Windows users interest

**Comment by lgautier** [comment]
The official rpy2 is now on Github.

**Comment by lgautier** [comment]
Binary wheels for windows now built by the CI pipeline.

Dev binaries are uploaded to pypi and can be installed with
```sh
pip install -U --pre rpy2
```
