### ISSUE TITLE
Error in intro

### ISSUE THREAD

**Issue by chaoshengt** [rpy2/rpy2#864]
when I run the demo code in "https://rpy2.github.io/doc/latest/html/vector.html'
```python
x = robjects.ListVector({'a': 1, 'b': 2, 'c': 3})
x[x.names.index('b')] = 9
```
It show an error:
'int' object has no attribute '__sexp__'

**Comment by lgautier** [comment]
Fixed. This will be in release 3.5.1. In the meantime an explicit conversion is required:

```python
x[x.names.index('b')] = robjects.IntVector([9])
```
