### ISSUE TITLE
sometimes empty images when saving graphics to disk from R script

### ISSUE THREAD

**Issue by abubelinha** [rpy2/rpy2#867]
Hello. This is not a bug, but a pretty **basic question**.

I have just discovered rpy2 and I was able to run basic R scripts by following the [evaluating R code example](https://rpy2.github.io/doc/latest/html/introduction.html#evaluating-r-code).
I was interested in modifying that sample script to generate some R-graphics

```Python
scriptR = '''
	library(UpSetR)
	listInput <- list(
		one = c(1, 2, 3, 5, 7, 8, 11, 12, 13), 
		two = c(1, 2, 4, 5, 10), 
		three = c(1, 5, 6, 7, 8, 9, 10, 12, 13)
	)
	png("upsetRpy2.png")
	upset(fromList(listInput), order.by = "freq")
	dev.off()
	'''
import rpy2
import rpy2.robjects as robjects
result = robjects.r(scriptR)
print(result)
```
output:
```
null device
          1
```
If I run the script in `scriptR` from R console, the image is correctly saved to the .png file (I can see the nice graph).
When running the python script, I am getting the image file generated in disk. But when I open, it's a blank empty image.

I know there is a [graphics section](https://rpy2.github.io/doc/latest/html/graphics.html) in rpy2 documentation.
But I have not clear if that documentation is focused on how to control R-graphics functions from Python code (i.e. passing the Python data to R in order to be plotted, or passing other parameters to R-functions, taken from Python variables).

But can I leave the R script to do everything by itself, and generate the graphic by just calling the script?
I am not trying to show the plot on screen, and I also dont want to get the graphics from R into Python.
I just want R to generate and save it on disk, so I thought this approach should work.

If not, what's the way to make this work with the minimal modifications to the original R script?

Thanks a lot in advance.

**Comment by abubelinha** [comment]
I tried to simplify the graph to something more basic. This worked:

```Python
scriptR = '''
	library(UpSetR)
	cars <- c(3, 2, 6, 4, 9)
	png("plotRpy2.png")
	plot(cars)
	dev.off()
	'''
import rpy2
import rpy2.robjects as robjects
result = robjects.r(scriptR)
print(result)
```
Now the generated plotRpy2.png files contains the graphic:
![plotRpy2](https://user-images.githubusercontent.com/698946/162492110-38c5c93c-aaa0-482b-a53a-9cf3cf923d5e.png)


Any idea about the reason the upsetRpy2.png file is not saved properly in the previous script?

**Comment by lgautier** [comment]
The issue tracker is better suited for bug reports, or discuss possible new features or improvements.

Here I don't think that this is a bug with rpy2. The display of R objects that call the `grid` plotting system (such as `ggplot2` objects) can require an explicit call to `print()` in some situations (e.g., rendering R markdown documents or weaving `Rnw` file). The following change would make your code output the figure in the active graphical device (the PNG file opened) as expected.

```r
print(upset(fromList(listInput), order.by = "freq"))
```

**Comment by abubelinha** [comment]
@lgautier thank you so much, print() was it!

Yes, when I ran my 2nd script I realized this was not a bug and edited my first sentence. 
Sorry about misusing the issue tracker.  
Is there any good place for asking questions about rpy2 usage?

As I would mainly use it for recycling my graphics R-scripts and reuse them for Python pre-processed data, I would say it is much easier for me to run them like in the example above: loading my data from Python and let R do all the graphic work by itself. 
Would this example be the correct approach? (I plan to do the same with big dataframes)

```Python
import rpy2
import rpy2.robjects as robjects

pyints = [5, 3, 8, 2, 1] # in production, this would be a pandas dataframe after much Python pre-processing.
#  I want to make pyints available to my R script below (i.e., load pyints from R)
robjects.globalenv['pyints'] = robjects.IntVector(pyints)

scriptR = '''
	xdata<-c(1,2,3,4,5)
	ydataR <- c(3, 2, 6, 4, 9)
	ydataP <- pyints # use data from Python variable above
	mypath="C:\\dropboxs\\abu\\Dropbox\\python\\"
	png("simple_plot.png")
	plot(ydataR, col="blue",pch="R", xlim=c(1,5),ylim=c(0,10) )
	points(ydataP, col="red", pch="P")
	dev.off()
	'''
result = robjects.r(scriptR)
print(result)
```

This seems to work and it's pretty straightforward to re-use my current R scripts this way.
I just wonder if this is the most efficient approach (memory, speed), when managing huge datasets. 
Would be more efficient to reconstruct the script using rpy2 methods to handle R-plotting functions, objects, etc from Python code?

Thanks a lot

**Comment by abubelinha** [comment]
@lgautier thank you so much, print() was it!

Yes, when I ran my 2nd script I realized this was not a bug and edited my first sentence. 
Sorry about misusing the issue tracker.  Is there any good place for asking questions about rpy2 usage?

As I would mainly use it for recycling my graphics R-scripts and reuse them for Python pre-processed data, I would say it is much easier for me to run them like in the example above: loading my data from Python and let R do all the graphic work by itself. Would this example be the correct approach? (I plan to do the same with big dataframes)

```Python
import rpy2
import rpy2.robjects as robjects

pyints = [5, 3, 8, 2, 1] # in production, this would be a pandas dataframe after much Python pre-processing.
#  I want to make pyints available to my R script below (i.e., load pyints from R)
robjects.globalenv['pyints'] = robjects.IntVector(pyints)

scriptR = '''
	xdata<-c(1,2,3,4,5)
	ydataR <- c(3, 2, 6, 4, 9)
	ydataP <- pyints # use data from Python variable above
	png("simple_plot.png")
	plot(ydataR, col="blue",pch="R", xlim=c(1,5),ylim=c(0,10) )
	points(ydataP, col="red", pch="P")
	dev.off()
	'''
result = robjects.r(scriptR)
print(result)
```

This seems to work and it's pretty straightforward to re-use my current R scripts this way.
I just wonder if this is the most efficient approach (memory, speed), when managing huge datasets. 
Would be more efficient to reconstruct the script using rpy2 methods to handle R-plotting functions, objects, etc from Python code?

Thanks a lot
