### ISSUE TITLE
Unable to suppress startup warning messages

### ISSUE THREAD

**Issue by shil3754** [rpy2/rpy2#869]
OS: CentOS 7.2
Python: 3.6.9
R: 3.6.1 (and 3.6.2, 3.6.3)
rpy2: 3.4.5

Whenever I run 
`from rpy2 import robjects`
in a Python console, I get the following warnings.

> During startup - Warning messages: 
> 1: package ‘methods’ was built under R version 3.6.1  
> 2: package ‘datasets’ was built under R version 3.6.1  
> 3: package ‘utils’ was built under R version 3.6.1  
> 4: package ‘grDevices’ was built under R version 3.6.1  
> 5: package ‘graphics’ was built under R version 3.6.1  
> 6: package ‘stats’ was built under R version 3.6.1

I find this confusing because these are all core packages which are supposed to come with R itself. 
No such messages are seen when I import libraries in an R console. 

I have tried to update R to newer versions (3.6.2, 3.6.3), but the messages are still there, only that the version number in the messages are also updated accordingly.

When I use rpy2 3.2.6, these messages can be suppressed by first running
`import logging`
`from rpy2.rinterface_lib.callbacks import logger as rpy2_logger`
`rpy2_logger.setLevel(logging.ERROR)`

However, when I update rpy2 to 3.4.5, the above method does not work anymore. 
So the questions are
1. why are there startup warning messages in the first place?
2. how to suppress them?

### update
It seems that the issue is caused by the difference between the R versions in the base environment (R 3.6.0) and the active environment (3.6.1). If I downgrade the R version in the active environment to 3.6.0, the warning messages are gone.
But this solution is not ideal. What if I really want to use a newer version of R in the active environment?

**Comment by lgautier** [comment]
You likely have packages (in a directory defined by the environment variable `R_LIBS`, or defined in a custom R startup configuration) that were installed with a different version of R.

Otherwise you R version is quite old. I am quite unsure that a relatively recent version of rpy2 will work with it. You Python version is also old.
