### ISSUE TITLE
Recursion error still in 3.5.1 release

### ISSUE THREAD

**Issue by ejolly** [rpy2/rpy2#873]
https://github.com/rpy2/rpy2/issues/866 was closed because this fix was apparently made in 3.5.1, but I can reproduce the error and encounter it regularly using `pandas2ri.converter`, .e.g.

```
with localconverter(robjects.default_converter + pandas2ri.converter):
  p_df = robjects.conversion.rpy2py(r_df)
```

Casting directly, e.g. `pd.DataFrame(r_df)`, works but the outputted frame is transposed and all column names are lost. This is causing a lot of failures for my library which heavily depends on rpy2 https://github.com/ejolly/pymer4

It also looks like another user (@bakaleks) commented about this in the closed issue thread.

**Comment by lgautier** [comment]
I prefer reopening issue #866 than creating a new one to track.
