### ISSUE TITLE
ETA on a Python 3.10 build on pypi?

### ISSUE THREAD

**Issue by mharvey-jt** [rpy2/rpy2#877]
Hi, is there a Python 3.10 release to pypi planned?

**Comment by lgautier** [comment]
Do you mean precompiled binaries / wheels for OSX? I rely on the easy availability of Python 10 on OSX on Github for this. May be it is the case already. I have not checked.

**Comment by lgautier** [comment]
OSX builds for Python 3.10 are on pypi.
