### ISSUE TITLE
Iterating through items as labels in an R factor results in an error any item is `NA`

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#879]
**Describe the issue or bug**

As the title says.

**To Reproduce**

```python
import rpy2.robjects as ro
v = ro.r('factor(c("a", NA, "b"))')
tuple(v.iter_labels())
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [14], in <cell line: 1>()
----> 1 tuple(v.iter_labels())
```

**Expected behavior**

Should return the items as labels without error.

**Error**
See above

**Additional context**

**Comment by yangzou** [comment]
Hi lgautier,

I suspect your change may break the `%%R` magic cell and the `%R` magic line functionality in Google's Colab.

I have the following in the colab cell:

```
%reload_ext rpy2.ipython

%%R
123
```

Then I got the following error:
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-2-20d50b77dfc3>](https://localhost:8080/#) in <module>
----> 1 get_ipython().run_cell_magic('R', '', '123\n')

8 frames
<decorator-gen-122> in R(self, line, cell, local_ns)

[/usr/local/lib/python3.7/dist-packages/rpy2/robjects/conversion.py](https://localhost:8080/#) in _py2rpy(obj)
    240     raise NotImplementedError(
    241         "Conversion 'py2rpy' not defined for objects of type '%s'" %
--> 242         str(type(obj))
    243     )
    244 

NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'str'>'


However, if I downgrade to version 3.5.1, the above code will work again. And the above code starts to break in version 3.5.2

After checking the changes between 3.5.1 and 3.5.2, I tend to think this could be the change that breaks it.

Could you take a look? Or if there any workaround if this is the intended behavior? Thanks!

**Comment by lgautier** [comment]
This is an issue with Colab: https://github.com/googlecolab/colabtools/issues/3212
