### ISSUE TITLE
 Pandas converter: add support and tests for BoolenDtype and Float64Dtype etc.

### ISSUE THREAD

**Issue by jsture** [rpy2/rpy2#880]
In reference to #669 where `StringDtype` was fixed

`robjects.conversion.py2rpy` breaks for dataframes containing [pandas.BooleanDtype](https://pandas.pydata.org/docs/reference/api/pandas.BooleanDtype.html) and `Float64Dtype` which were introduced in pandas version `1.0.0`. 

```
AttributeError: 'Float64Dtype' object has no attribute 'isnative'
File ".../numpy2ri.py", line 83, in numpy2rpy
    if not o.dtype.isnative:
```

`rpy==3.5.2`

**Comment by lgautier** [comment]
Fixed with PR #881.
