### ISSUE TITLE
DOC: Version warning in dev docu point to wrong stable/release version

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [rpy2/rpy2#884]
I am new to the project and not sure.

But please look into Line 15 in https://github.com/rpy2/rpy2/blob/master/doc/index.rst . The line points to 3.3. as the latest release. But isn't 3.5.1 the latest stable release?

If I am right I would suggest
 - Remove the version number and *don't* put the right one in it. This prevent from the need to modify this file everytime a new release comes out.
 - Modify your doc system that way that you can provide a link like this https://rpy2.github.io/doc/release or https://rpy2.github.io/doc/stable .

**Comment by lgautier** [comment]
> I am new to the project and not sure.
> 
> But please look into Line 15 in https://github.com/rpy2/rpy2/blob/master/doc/index.rst . The line points to 3.3. as the latest release. But isn't 3.5.1 the latest stable release?

It is 3.5.2 actually.

> 
> If I am right I would suggest
> 
>     * Remove the version number and _don't_ put the right one in it. This prevent from the need to modify this file everytime a new release comes out.

Fair. Fixing this now.

>     * Modify your doc system that way that you can provide a link like this https://rpy2.github.io/doc/release or https://rpy2.github.io/doc/stable .

Indeed. I don't know how to have URL aliases with Github pages (rather that make a copy of the pages). Alternatively I could have an HTML page with a redirect.
