### ISSUE TITLE
Proper signature for `rternalize`d functions

### ISSUE THREAD

**Issue by krassowski** [rpy2/rpy2#905]
**Is your feature request related to a problem? Please describe.**

`rternalize` is super useful for passing custom Python functions to R. However, there are some cases when the current implementation is suboptimal, mostly related to dispatch logic in R:
- when the number of arguments of the R function matters and different things are passed depending on how many arguments it can accept
- sometimes evaluation of rternalized function fails due to indiscriminate usage of `...` (`'...' used in an incorrect context` - I haven't gotten to understanding this fully, but there are some curious edge cases)

I encountered these problems when working on clustering distance function and custom annotation function to be passed to complex heatmap (respectively).

**Describe the solution you'd like**
I would like the R signature of the Python function to be reasonably close to Python signature (of course it would not be identical due to differences in `*args` and `**kwargs` vs `...`).

My solution was to re-write the `rternalize` function to so that the generated function template includes the same arguments as the Python function by using inspect, [available](https://github.com/krassowski/rpy2-complex-heatmap-grammar/blob/8b608b8ccd59706d4ba366e18285ce7bcd6d8848/heatmap_grammar/rpy2_helpers.py#L52-L138).

Briefly, for Python function:

```python
@rternalize_with_signature
def full(a, /, b, c=1, *, d=2, e):
    pass
```

it generates R code:

```R
    function(a, b, c, d, e) {
        RPY2_ARGUMENTS <- base::list(
           ".Python",
           RPY2_FUN_PLACEHOLDER
        )

        
        RPY2_ARGUMENTS <- base::c(RPY2_ARGUMENTS, base::list(a))
        
        if (!base::missing(b)) {
            RPY2_ARGUMENTS[['b']] <- b
        }
        
        if (!base::missing(c)) {
            RPY2_ARGUMENTS[['c']] <- c
        }
        
        if (!base::missing(d)) {
            RPY2_ARGUMENTS[['d']] <- d
        }
        
        if (!base::missing(e)) {
            RPY2_ARGUMENTS[['e']] <- e
        }
        

        do.call(
           .External,
           RPY2_ARGUMENTS
        );
    }
```

I would like to bring this implementation to rpy2 proper if you are happy with it. If you know of another, better solution, please let me know.

The limitation of the current implementation is namespace collisions: if users define a function:

```python
@rternalize_with_signature
def test(RPY2_ARGUMENTS):
    pass
```

we would have a conflict between `RPY2_ARGUMENTS` argument and our `RPY2_ARGUMENTS` variable (of course we can workaround by detecting/blocking/appending suffix, etc); all other nodes should be collision-safe (this is the purpose of using explicit `base::` namespace prefix).

**Describe alternatives you've considered**
Sorry, no better ideas :(

**Comment by lgautier** [comment]
(...)
> - when the number of arguments of the R function matters and different things are passed depending on how many arguments it can accept

Do you mean R functions with signatures with an ellipsis (e.g., `function(x, ..., foo=TRUE)` in R) that should map to `*args` and `**kwargs` in Python?

This is indeed not handled at at all. It makes sense to try to address this.

> - sometimes evaluation of `rternalized` function fails due to indiscriminate usage of `...` (`'...' used in an incorrect context` - I haven't gotten to understanding this fully, but there are some curious edge cases`)

The only I can think of that would lead you to that error is with something like:

```python
import rpy2.robjects as ro
import rpy2.rinterface as ri

@ri.rternalize
def foo(x):
    print(x) 

foo(ro.rl('...'))
```
You'd get the same error if doing the same in R. Can you share how you get to that error if different?

(...)
> ```python
> @rternalize_with_signature
> def full(a, /, b, c=1, *, d=2, e):
>     pass
> ```

That's neat. There is no functional equivalent in R to `/` and `*` in Python's function signatures. Using them helps bring safety through constrains on the way the function can be called.

Let's start a PR for this.

**Comment by krassowski** [comment]
> > - when the number of arguments of the R function matters and different things are passed depending on how many arguments it can accept
>
> Do you mean R functions with signatures with an ellipsis (e.g., function(x, ..., foo=TRUE) in R) that should map to *args and **kwargs in Python?

Well, I meant code like [this snippet from ComplexHeatmap](https://github.com/jokergoo/ComplexHeatmap/blob/1ad73d81f578e92d64b9f959cf6e83f896ebc13a/R/utils.R#L191-L201) package:

```R
get_dist = function(matrix, method) {
    if(is.function(method)) {
        nargs = length(as.list(args(method)))
        if(nargs == 2) { # a distance function
            dst = method(matrix)
        } else if(nargs == 3) {
            dst = dist2(matrix, method)
        } else {
            stop_wrap("Since your distance method is a function, it can only accept one or two arguments.")
        }
    } 
    # other non-relevant code
}
```

It explicitly checks for number of arguments the function accepts, and calls the `method` differently (as `method(matrix)` or `method(x, y)`) depending on the number of arguments, so if we want to provide a Python function for distance method, it needs to have the number of arguments properly translated.


> > - sometimes evaluation of rternalized function fails due to indiscriminate usage of ... ('...' used in an incorrect context - I haven't gotten to understanding this fully, but there are some curious edge cases`)
>
> The only I can think of that would lead you to that error is with something like:
> ...
> You'd get the same error if doing the same in R. Can you share how you get to that error if different?

Well, I encountered this with `ComplexHeatmap` implementation of custom annotations. [Here is a notebook](https://gist.github.com/krassowski/5b370eeb626ae9bc84b38ca248b8066e) with step-by-step reproduction and explanation. Long story short, if signature of a function (`formals`) gets modified for any (holy or unholy) reason and no longer includes `...`, the current body of `rternalize` still has `...`, whereas the proposed `rternalize_with_signature` doesn't, hence it works while the former doesn't.

**Comment by lgautier** [comment]
> Long story short, if signature of a function (formals) gets modified for any (holy or unholy) reason and no longer includes ..., the current body of rternalize still has ..., whereas the proposed rternalize_with_signature doesn't, hence it works while the former doesn't.

R code modifying a function signature dynamically the way `ComplexHeatmap` does make me raise an eyebrow. This is problematic outside of `rpy2`. R function writers can see their own code modified at run time without a warning. What could go wrong... It should fail with an error message if the expected signature `index = , k = 1, n = 1` is not present. Up to the function writer to comply to the expected signature.

The wish to have rpy2's "rternalized" Python functions see their signature mirrored on the R side is legitimated though. Without that we cannot use it with R code checking the signature of callbacks.

Your PR is a great start. I am suggesting additions.

**Comment by lgautier** [comment]
Merged. Will be in rpy2-3.5.4 (released today).
