### ISSUE TITLE
Seurat functions taking forever to execute when running using rpy2

### ISSUE THREAD

**Issue by ankur26197-acog** [rpy2/rpy2#906]
I am implementing general steps of scRNA study like QC, integration, clustering and cell annotation on a dataset. I am using Seurat to implement each of these functions and anndata2ri and rpy2 for interchangeability of anndata to SCE object. I basically source all my R scripts using r.source from robjects module and call them from my notebook. However when trying to run several Seurat functions, I find that each of the basic steps like normalising data or finding variable features takes hours for a single sample but they execute smoothly when I try running my code using magic functions described here https://github.com/theislab/anndata2ri. 

Steps to reproduce-

- Load a scRNA dataset in anndata.

- Write functions for analysis like QC, normalisation, integration, clustering, etc. in R

- Source each of these function using r from rpy2.robjects module and call them from a notebook/python file. Make sure all these functions calling the respective R functions are in the same notebook/python file. Pass the same anndata object modified after every function call.

- Also implement the previous step using magic functions

- In ideal case after running QC if you try integration using https://satijalab.org/seurat/reference/integratedata , you will see that each of the basic steps provided there take hours for executing while it runs smoothly using the magic functions.

`Ubuntu 20.04` `Python version 3.8.8` `anndata version 0.8.0` `anndata2ri version 1.0.3` `rpy version 3.2.7` `R version 4.2.0`

**Comment by lgautier** [comment]
Hi, without a self-contained minimal example there is too much left to guess about what you are trying to achieve and whether this is a possible issue with rpy2 or with an other package (here `anndata2ri`).

**Comment by ankur26197-acog** [comment]
Hello,
Here is starter code that you can use.

In a jupyter notebook

`from rpy2.robjects import r
import anndata2ri
anndata2ri.activate()
ipython.magic("%load_ext rpy2.ipython")

#Load a sc exp data in anndata variable  for exp, adata
r.source('/home/baseline_integration.R') #Give path to R script
r.baseline_integration(adata) # Call the R function passing anndata 

baseline_integration.R  can have the following code

`baseline_integration <- function(adata){
    suppressPackageStartupMessages(library(Seurat))
    comb_data<-as.Seurat(adata,counts='X',data=None)
    ob.list <- SplitObject(comb_data, split.by = "sample")
    
    # Normalization and variable feature selection
    data_list<-lapply(ob.list, FUN = function(sample_data) {
    sample_data<-NormalizeData(sample_data, normalization.method = "LogNormalize")
    sample_data<-FindVariableFeatures(sample_data, selection.method = "vst", nfeatures = 2000)
    })

    # Integrate data
    # Integrated data has a cell-level meta data (comb_data@meta.data) named "orig.ident" storing the sample where the cell is from.
    # Cell barcode will also be modified to add sample index.
    anchors<-FindIntegrationAnchors(object.list = data_list, dims = 1:20)
    comb_data<-IntegrateData(anchorset = anchors, dims = 1:20)

    DefaultAssay(comb_data)<-"integrated"
    return(as.SingleCellExperiment(comb_data))
}`

The R code is taken from https://satijalab.org/seurat/reference/integratedata

**Comment by lgautier** [comment]
This is likely your culprit:

> anndata2ri.activate()

Conversion can be arbitrarily expensive to run, and ultimately unnecessary if merely chaining calls to R functions (using the output of a function call as input in the next function call).

Besides that, the use of global and persistent conversion rule changes with `activate` is discouraged (and deprecated in the rpy2 code base).

This is likely more an issue for the package `anndata2ri`. Closing. Reopen if not the case.
