### ISSUE TITLE
Adding pd.Timestamp and pd.Timedelta to pandas conversions

### ISSUE THREAD

**Issue by kenahoo** [rpy2/rpy2#912]
**Is your feature request related to a problem? Please describe.**
I have timeseries data in dataframes that I want to pass between Python and R.  A fellow StackOverflow user (https://stackoverflow.com/questions/73115921/rpy2-converting-dataframes-data-frames) helped me figure out how to convert `pd.Timestamp` columns, but I'm stumped on `pd.Timedelta` columns.  Additionally, `pd.Timestamp` data doesn't seem to be handled unless it's actually a column in a `pd.DataFrame`.

**Describe the solution you'd like**
It would be great to beef up the conversions in `rpy2.robjects.pandas2ri` to handle some additional common Pandas types.

**Describe alternatives you've considered**
The alternatives are to write custom converters, but I've had a tough time figuring out how to do that for these types.

**Additional context**
Here's a test case that shows some of the conversions I think it would be great to support:

```
import pandas as pd
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

ro.r("""
my_r_function <- function(now, delta, data) {
  stopifnot(inherits(now, 'POSIXct'))
  stopifnot(inherits(delta, 'difftime'))
  data[data$datetime + delta >= now, ]
}
""")

now = pd.to_datetime('2022-02-22 02:22:22Z')
data = pd.DataFrame({'datetime': now + pd.to_timedelta([-1, 0, 1], 'hours'),
                     'offset': pd.to_timedelta([3, 2, 1], 'minutes'),
                     'variable': 'loudness',
                     'value': 4,
                     'size': 3.1})

converter = ro.default_converter + pandas2ri.converter

with localconverter(converter):
    result = ro.r['my_r_function'](now, pd.to_timedelta(1, 'minute'), data)

assert(isinstance(result, pd.DataFrame))
assert(pd.api.types.is_datetime64tz_dtype(result.datetime))
assert(pd.api.types.is_timedelta64_dtype(result.offset))
```

**Comment by kenahoo** [comment]
I submitted a pull request related to some of these issues:  https://github.com/rpy2/rpy2/pull/917

**Comment by lgautier** [comment]
The PR was merged.
