### ISSUE TITLE
rpy2.robjects.POSIXct([datetime]) does not work

### ISSUE THREAD

**Issue by kenahoo** [rpy2/rpy2#914]
**Describe the issue or bug**

Neither a timezone-aware nor timezone-naive `datetime` object in Python can be converted successfully using the `ro.POSIXct()` function.

**To Reproduce**

```
import datetime

import pytz
import rpy2.robjects as ro


dt = ro.POSIXct([datetime.datetime(2002, 2, 22, 2, 22, 22)])
# Fails (but doesn't throw exception):
# R[write to console]: 1:
# R[write to console]: In strptime(x, "%Y-%m-%d-%H-%M-%OS", tz = tz) :
# R[write to console]:  unknown timezone 'CST'
#
# R[write to console]: 2:
# R[write to console]: In as.POSIXct.POSIXlt(strptime(x, "%Y-%m-%d-%H-%M-%OS", tz = tz),  :
# R[write to console]:
#
# R[write to console]:  unknown timezone 'CST'


tz = pytz.timezone("America/Los_Angeles")
dt = ro.POSIXct([tz.localize(datetime.datetime(2002, 2, 22, 2, 22, 22))])
# Fails (throws exception):
# Traceback (most recent call last):
#   File "/Users/kwilliams/.pyenv/versions/my_venv/lib/python3.9/site-packages/rpy2/rinterface_lib/sexp.py", line 612, in from_object
#     mv = memoryview(obj)
# TypeError: memoryview: a bytes-like object is required, not 'tuple'
#
# During handling of the above exception, another exception occurred:
# AttributeError: 'America/Los_Angeles' object has no attribute 'encode'
```

**Expected behavior**

A timezone-aware `datetime` object should be converted in the obvious way to an R `POSIXct` object, preserving the same timezone.

A timezone-naive `datetime` object is problematic, because (for good reason, IMO) there are no timezone-naive `POSIXt` objects in R.  The approach of using a default timezone is sort of okay, but does lead to mysterious behavior - and in this case to a timezone `"CST"` that's invalid (not in the Olsen database).  I would rather have it throw an exception in this case.

**Error**
See example above.

**Additional context**

I'm also wondering why it's doing any `strptime()` (parsing a string into a `POSIXt` object) at all, as shown in the first chunk of output above.  The `datetime` fields should have enough information to create a `POSIXct` object without needing a string parse, right?

**Comment by lgautier** [comment]
Does PR #917 completely fix this?

**Comment by kenahoo** [comment]
@lgautier Yes it does, thanks!  I just ran this same test script against `master` (4c05729a) and now the results are as expected.

I also have a separate branch where I'm trying to sort out a bit more `pandas` functionality with datetimes, I'll likely create another issue/PR for that soon.

**Comment by lgautier** [comment]
Thanks. I am closing this since resolved. rpy2-3.5.4 will normally be released today.
