### ISSUE TITLE
Value labels lost for pandas categories

### ISSUE THREAD

**Issue by buhtz** [rpy2/rpy2#919]
**Describe the issue or bug**

I am not sure if this problem is cause of MatchIt or rpy2. But with clean R code I am not able to reproduce that behaviour with MatchIt.

When I have Pandas dataframe with a column of dtype category (in the example below `haircat`), using it in an R function via rpy2 and then get it back the value labels are lost and transformed to integers.
This does not happen if that column is just a `str`, which is the current workaround for me.

**To Reproduce**

```python
#!/usr/bin/env python3
import sys
import platform
import pandas as pd
import random as rd
import rpy2
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects
import rpy2.robjects.pandas2ri as pandas2ri
pandas2ri.activate()

if __name__ == '__main__':
    rd.seed(0)

    robjects.packages.importr('MatchIt')

    print('MatchIt {}'.format(robjects.r['packageVersion']('MatchIt')))
    print(f'pandas {pd.__version__}')
    print(f'rpy2 {rpy2.__version__}')
    print(f'Python {sys.version}')
    print(f'{platform.system()} {platform.version()}')

    # prepare data
    df = pd.DataFrame({
        'ID': range(100),
        'treat': rd.choices(['Controll', 'Treat'], k=100, weights=[3, 1]),
        'age': rd.choices(range(20, 80), k=100),
        'hairstr': rd.choices(['blue', 'red'], k=100),
        'haircat': rd.choices(['blue', 'red'], k=100)
    })
    df.treat = df.treat.astype('category')
    df.haircat = df.haircat.astype('category')

    formula = robjects.Formula('treat ~ age + hairstr + haircat')
    match_result = robjects.r['matchit'](
        formula = formula,
        data = df,
        method = 'nearest',  # nearest_neighbor
        distance = 'glm',  # generalized linear model
    )

    match_dataframe = robjects.r['match.data'](match_result)
    match_dataframe = robjects.conversion.rpy2py(match_dataframe)


```

Please see the result in column `hairstr` and `haircut`.

```
>>> match_dataframe
    ID  treat  age hairstr  haircat  distance  weights  subclass
0    0      2   57    blue        2  0.409451      1.0         1
1    1      2   70    blue        2  0.425715      1.0         7
2    2      1   34    blue        2  0.381175      1.0        30
6    6      2   67     red        1  0.308268      1.0        22
7    7      1   39     red        1  0.278426      1.0        13
..  ..    ...  ...     ...      ...       ...      ...       ...
94  94      2   44    blue        2  0.393382      1.0        33
95  95      2   44    blue        1  0.494318      1.0        34
96  96      2   62     red        2  0.223681      1.0        35
97  97      1   45    blue        1  0.495604      1.0        34
98  98      1   59    blue        2  0.411941      1.0         1

[70 rows x 8 columns]
```

**Additional context**

```
MatchIt [1] '4.4.0'
pandas 1.2.5
rpy2 3.5.3
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
Windows 10.0.19043
```

**Comment by lgautier** [comment]
This line should issue a warning advising against continuing to do it:
```python
pandas2ri.activate()
```
Please try with the currently recommended way to perform conversions to pandas data structures.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thank you very much for your reply.

> This line should issue a warning advising against continuing to do it:
> 
> ```python
> pandas2ri.activate()
> ```

I checked it again. There is now warning or error message about this.
Should be treated as a bug or not? I couldn't find a unittest for that case.

> Please try with the currently recommended way to perform conversions to pandas data structures.

What is recommended? There are a lot of variants on the web, e.g. StackOverflow. Did you mean this?
https://rpy2.github.io/doc/latest/html/generated_rst/pandas.html#r-and-pandas-data-frames

I am confused about this `with...` and doing `+` with converter objects. Feels wired to me and is not self explaining. Is there more background info about it in the docs?

This code works now. I have helper function encapsulating the with-thing.

```
#!/usr/bin/env python3
import sys
import logging
import platform
import random as rd
import pandas
from typing import Union
import rpy2
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects
import rpy2.robjects.pandas2ri as pandas2ri


def convert_data_frame(df: Union[pandas.DataFrame,
                                 rpy2.robjects.vectors.DataFrame]
                        ) -> Union[pandas.DataFrame,
                                   rpy2.robjects.vectors.DataFrame]:
    """Converts a data frame from Python pandas to R or vis-à-vis.

    The direction of the convertion is automatically recognized.
    """
    with robjects.conversion.localconverter(
        robjects.default_converter + pandas2ri.converter):

        # Pandas to R
        if isinstance(df, pandas.DataFrame):
            logging.debug('Convert Pandas data frame to R.')
            return robjects.conversion.py2rpy(df)

        # R to Pandas
        if isinstance(df, rpy2.robjects.vectors.DataFrame):
            logging.debug('Convert R data frame to Pandas.')
            return robjects.conversion.rpy2py(df)

        raise TypeError('Need a R or Pandas data frame! But it is {}'
                        .format(type(df)))


if __name__ == '__main__':
    rd.seed(0)

    robjects.packages.importr('MatchIt')

    print('MatchIt {}'.format(robjects.r['packageVersion']('MatchIt')))
    print(f'pandas {pandas.__version__}')
    print(f'rpy2 {rpy2.__version__}')
    print(f'Python {sys.version}')
    print(f'{platform.system()} {platform.version()}')

    # prepare data
    df = pandas.DataFrame({
        'ID': range(100),
        'treat': rd.choices(['Controll', 'Treat'], k=100, weights=[3, 1]),
        'age': rd.choices(range(20, 80), k=100),
        'hairstr': rd.choices(['blue', 'red'], k=100),
        'haircat': rd.choices(['blue', 'red'], k=100)
    })
    df.treat = df.treat.astype('category')
    df.haircat = df.haircat.astype('category')

    formula = robjects.Formula('treat ~ age + hairstr + haircat')
    match_result = robjects.r['matchit'](
        formula = formula,
        data = convert_data_frame(df),
        method = 'nearest',  # nearest_neighbor
        distance = 'glm',  # generalized linear model
    )

    match_dataframe = robjects.r['match.data'](match_result)
    match_dataframe = convert_data_frame(match_dataframe)

    print(match_dataframe)

```

**Comment by lgautier** [comment]
> Thank you very much for your reply.
> 
> > This line should issue a warning advising against continuing to do it:
> > ```python
> > pandas2ri.activate()
> > ```
> 
> I checked it again. There is now warning or error message about this. Should be treated as a bug or not? I couldn't find a unittest for that case. What is about the test in `TestPandasConversions.testActivate`? Itself using the `activate()` but don't check for a warning.

The point is that the function is deprecated. Too many odd things can happen when using it. Issue reports should used the recommended way.

The warning itself comes from the fact that it is deprecated. A unit-test for this seems superfluous.

> > Please try with the currently recommended way to perform conversions to pandas data structures.
> 
> What is recommended? There are a lot of variants on the web, e.g. StackOverflow. Did you mean this? https://rpy2.github.io/doc/latest/html/generated_rst/pandas.html#r-and-pandas-data-frames

The evolution of code may lead to variations in the answers on StackOverflow. That doc page should be good. That part of the documentation is ensuring that all examples are running.

> I am confused about this `with...` and doing `+` with converter objects. Feels wired to me and is not self explaining. Is there more background info about it in the docs?

Conversion rules can be layered on the top of each others using the operator `+` to create a combined set of conversion rules. This allows a syntax like `rule_set_C = rule_set_A + rule_set_B`. See https://rpy2.github.io/doc/v3.5.x/html/robjects_convert.html#converter-objects

`with` is using a context manager to handle the setting of new conversion rules and restoring them how they were after the code block is executed. See https://rpy2.github.io/doc/v3.5.x/html/robjects_convert.html#local-conversion-rules

> This code works now. I have helper function encapsulating the with-thing.

The conversion system is designed to use dispatch to specify conversion rules for each type, but if the code as you have it works for you this is also good.

Does this mean that the error reported is no longer present?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> The warning itself comes from the fact that it is deprecated. A unit-test for this seems superfluous.

**Again**: There is **no** deprecation warning or any other warning or error when using that function.

> > What is recommended? There are a lot of variants on the web, e.g. StackOverflow. Did you mean this? https://rpy2.github.io/doc/latest/html/generated_rst/pandas.html#r-and-pandas-data-frames
> 
> The evolution of code may lead to variations in the answers on StackOverflow. That doc page should be good. That part of the documentation is ensuring that all examples are running.

Your answer seems unspecific to me. Again my question: What is the recommended way? Is the doc link I proposed the right one? Yes or no? For non-nativ-english speakers it is important to answer clear short and direct.

> > This code works now. I have helper function encapsulating the with-thing.
> 
> The conversion system is designed to use dispatch to specify conversion rules for each type, but if the code as you have it works for you this is also good.

Again I don't understand what you mean.
What do you mean with "dispatch"?

Is my code correct? Doesn't follow the currently recommended way?

> Does this mean that the error reported is no longer present?

To many open questions to close this.

What should be wrappend in the `with` block? Is it OK (recommended!) to have two separate `with` blocks for Pandas-2-R and back from R-2-Pandas conversions? Or does there happen some magic behind and such a two-way-conversion should be handled in one `with` block together?

**Comment by lgautier** [comment]
> > The warning itself comes from the fact that it is deprecated. A unit-test for this seems superfluous.
> 
> **Again**: There is **no** deprecation warning or any other warning or error when using that function.
> 
> > > What is recommended? There are a lot of variants on the web, e.g. StackOverflow. Did you mean this? https://rpy2.github.io/doc/latest/html/generated_rst/pandas.html#r-and-pandas-data-frames
> > 
> > 
> > The evolution of code may lead to variations in the answers on StackOverflow. That doc page should be good. That part of the documentation is ensuring that all examples are running.
> 
> Your answer seems unspecific to me. Again my question: What is the recommended way? Is the doc link I proposed the right one? Yes or no? For non-nativ-english speakers it is important to answer clear short and direct.

Instruction in a doc page for the matching version of the package should be working. If not, that's an issue to report.
Answers on StackOverflow may correspond to early version, and more important are outside of this software repository. StackOverflow has its own voting and comment system. This is the way to influence its content.

> > > This code works now. I have helper function encapsulating the with-thing.

Good. So I'll close the issue.

> > 
> > The conversion system is designed to use dispatch to specify conversion rules for each type, but if the code as you have it works for you this is also good.
> 
> Again I don't understand what you mean. What do you mean with "dispatch"?

"Dispatch" means finding the right function to run. For example `converter.rpy2py(someobject)` will delegate (dispatch) the the handling of `someobject` to a specific function depending on the type (class) of `someobject)`.  For example, if `converter` is from `pandas2ri`, and the type is `pandas.DataFrame` this the function `someobject` will be dispatched to: https://github.com/rpy2/rpy2/blob/master/rpy2/robjects/pandas2ri.py#L53
 
> Is my code correct? Doesn't follow the currently recommended way?

Correct code is code that does what you want without being accidentally correct (e.g., rely on a bug without being aware of it).

I understand your code to function as a switch. If an object is a `pandas.DataFrame` is will convert it to an R `data.frame`, and the other way around. I wouldn't have a good use-case for this and would think that it going to result in issues (unpredictability, code hard to read), but at the same time I do not know the context in which you are using it. I cannot answer in a definitive way.

> > Does this mean that the error reported is no longer present?
> 
> To many open questions to close this.

The questions are not about an issue in software though. If there are issues in the software it is easier to manage when having one question/issue per GitHub issue.

> What should be wrappend in the `with` block? Is it OK (recommended!) to have two separate `with` blocks for Pandas-2-R and back from R-2-Pandas conversions? Or does there happen some magic behind and such a two-way-conversion should be handled in one `with` block together?

I do not understand the question well. This seems like a usage question. StackOverflow, or another forum with a community of users will get the attention of more people able to answer.
