### ISSUE TITLE
Incorrect `pandas` conversion when duplicated column names in R data frame objects

### ISSUE THREAD

**Issue by lgautier** [rpy2/rpy2#925]
**Describe the issue or bug**

It is possible to create R data frames with duplicated column names. When the case, its conversion to pandas drop all columns with the same name excepts the last one but places it in the position of the first colum with that name.

**To Reproduce**

```python
In [1]: %load_ext rpy2.ipython

In [2]: %%R -o dataf
    ...: 
    ...: dataf <- data.frame(x=1:3, y=4:6, x=7:9, check.names=FALSE)
    ...: dataf
    ...: 
    ...: 
  x y x
1 1 4 7
2 2 5 8
3 3 6 9

In [3]: dataf
Out[30]: 
   x  y
1  7  4
2  8  5
3  9  6
```

**Expected behavior**

I think that Pandas does not allow `DataFrame` objects to have several columns with the same name. What to do in this situation can be:

a. fail with an error
b. make names unique (for example, by appending a number) and issue a warning
c. make names unique silently

I am leaning toward b.

**Error**

There is no error message.

**Additional context**

I found this by investigating issue #921 .

**Comment by krassowski** [comment]
Pandas does allow `DataFrame`s to have columns with the same name:

```python
df = DataFrame([[1, 2], [1, 2]])
df.columns = ['a', 'a']
df
```

  | a | a
-- | -- | --
0 | 1 | 2
0 | 1 | 2

I think that rpy2 could just convert to pandas as-is.

**Comment by lgautier** [comment]
Good. This makes things simpler.

(But bad, this is can be the cause of nasty bugs in R code).

Now how does one create a `pandas.DataFrame` from a sequence of vectors? The main constructor takes the data row-wise rather than column-wise and there does not appear to be a way to change that. The constructor `.from_dict()` does take data column-wise but it requires a `dict` as input with keys giving column names (which we cannot have because the column names are not unique).

**Comment by lgautier** [comment]
Got it:

```python

pandas.concat(<iterable of Series>, axis=1)
```

**Comment by lgautier** [comment]
The fix will be included in the next release.
