### ISSUE TITLE
Error with SexpExtPtr

### ISSUE THREAD

**Issue by jeffwong** [rpy2/rpy2#929]
I am attempting to use SexpExtPtr to exchange c data back and forth from python and R. However, the [example](https://rpy2.github.io/doc/latest/html/rinterface.html#rpy2.rinterface.SexpExtPtr) of using an external pointer doesn't work. 

```
import rpy2.rinterface as rinterface
import ctypes

class Point2D(ctypes.Structure):
    _fields_ = [("x", ctypes.c_int),
                ("y", ctypes.c_int)]

rinterface.initr()
pt = Point2D()
ep = rinterface.SexpExtPtr(pt)
```

Gives an error `ValueError: The constructor must be called with an instance of rpy2.rinterface.Sexp or an instance of rpy2.rinterface._rinterface.SexpCapsule`

Running on rpy2 3.5.3

**Comment by lgautier** [comment]
Thanks. It was a typo in the doc (and those examples are not checked by automated testing). Fixed with [e9c9cc8](https://github.com/rpy2/rpy2/commit/e9c9cc850e0003f4aabe3449c46e581aaee69ea7)
