### ISSUE TITLE
Performance issue of dataframe conversion

### ISSUE THREAD

**Issue by xinstein** [rpy2/rpy2#943]
**Is your feature request related to a problem? Please describe.**
two approaches to transfer dataframe from python to r and their performances:
1. pandas2ri conversion. Takes 50~60 seconds.
2. `pandasdf.to_parquet()`, and `arrow::read_parquet()`. Very same dataframe, takes 2~3 seconds. Performed on an old SSD drive (500MB/s).

**Describe the solution you'd like**
Does the current implementation of pandas2ri have room for performance improvement?

**Describe alternatives you've considered**
Simply use parquet format as the intermediary, better yet if it's passed by RAM.

**Comment by lgautier** [comment]
The conversion shipping with rpy2 is all in Python. Or rather mostly so. Moving parts down to C might happen again, as it used to be the case before `rpy2`'s codebase migrated to use `cffi`.

In the meantime I can offer you to even go 100-200 times faster than the mostly all-Python conversion shipping with `rpy2` by using `rpy2-arrow`: https://github.com/rpy2/rpy2-arrow

**Comment by xinstein** [comment]
Thank you for the clarification, that's a good enough solution, and the separation of this functionality into an extension is very reasonable.
Closing this
/close
