### ISSUE TITLE
TaggedList gives AttributeError after unpickling in python versions >= 3.7

### ISSUE THREAD

**Issue by puneetsl** [rpy2/rpy2#947]
**Describe the issue or bug**

When using picking and unpickling a `TaggedList` object, python version 3.7 and above give 
`AttributeError: 'TaggedList' object has no attribute '_TaggedList__tags'`

**To Reproduce**

```python
import pickle
from rpy2.rlike.container import TaggedList
t = TaggedList(["Yo!"], ["NYC"])
t.append("Hello", "World")
print(t)
x = pickle.dumps(t)
y = pickle.loads(x)

y.append("Show", "Reality")
print(y)
```
This usually happens when running through pyspark where spark sometime pickle the object to serialize and distribute.

**Expected behavior**
It should print
```
['Yo!', 'Hello']
['Yo!', 'Hello', 'Show']
```
**Error**
```
['Yo!', 'Hello']
Traceback (most recent call last):
  File "dic.py", line 206, in <module>
    y = pickle.loads(x)
  File "dic.py", line 87, in extend
    self.append(item, tag=tag)
  File "dic.py", line 73, in append
    self.__tags.append(tag)
AttributeError: 'TaggedList' object has no attribute '_TaggedList__tags'
```

**Comment by lgautier** [comment]
I can reproduce.

I believe that this is because `TaggedList` inherits from `list`, and with this it directly inherits a serialization / unserialization that drops the initialization of `__tags` along the way.

The following seems to confirm this suspicion:

```python
>>> t.__reduce__()
(<function copyreg._reconstructor(cls, base, state)>,
 (rpy2.rlike.container.TaggedList, list, ['Yo!', 'Hello']),
 {'_TaggedList__tags': ['NYC', 'World']}) 
```
If I understand the documentation correctly (https://docs.python.org/3/library/pickle.html#object.__reduce__), the dictionary that is last in the returned `tuple` is optional and should be used to update the `__dict__` of the instance when there is no method `__setstate__()`. As far as I can tell this method is not defined.

```python
>>> hasattr(t, '__getstate__')
False
```

I would be tempted to think that this is a bug in Python and/or an error in its documentation if this was not something likely to have been noticed and reported earlier.

I am also reading in doc that an additional optional element may be present in the `tuple` returned by `__reduce__`.

```
Optionally, an iterator (and not a sequence) yielding successive items. These items will be appended to the object either using obj.append(item) or, in batch, using obj.extend(list_of_items). This is primarily used for list subclasses, but may be used by other classes as long as they have append() and extend() methods with the appropriate signature. (Whether append() or extend() is used depends on which pickle protocol version is used as well as the number of items to append, so both must be supported.)
```

I am suspecting a bad combo of `.__reduce__()`, the parent class `list` having custom (and likely C-level unpickling), and `TaggedList` having a method `,setitem()`.

**Comment by lgautier** [comment]
`copyreg._reconstructor` seems to only consider the constructor (`__init__`) of the base (`list`):
 
```python
def _reconstructor(cls, base, state):
    if base is object:
        obj = object.__new__(cls)
    else:
        obj = base.__new__(cls, state)
        if base.__init__ != object.__init__:
            base.__init__(obj, state)
    return obj
```

This is somewhat puzzling, but I assume that there is a rationale around performance optimization and subclassing `list` is a less trodden path. I might have to dig deeper into what Python is exactly doing around pickling and unpickling list.

**Comment by lgautier** [comment]
A bit of a rabbit hole, but the Python API is likely not fully functional when subclassing `list`. 
The existence of the class `collections.UserList` would support this: https://docs.python.org/3/library/collections.html#userlist-objects
Subclassing `list` used to be not really possible. It has become better but there are still edge cases.

Replacing `TaggedList`'s parent class `list` with `UserList` fixes this issue. I don't know yet whether a viable fix (that is what is the possible impact elsewhere).

**Comment by puneetsl** [comment]
Thanks for taking a look at this!
Upon checking further, this seems to be an issue with pickle.loads calling list.extend method.
Since you have an overridden extend method
https://github.com/rpy2/rpy2/blob/master/rpy2/rlike/container.py#L218
a list object is passed as `iterable` instead of an instance of TaggedList, its only at that time python thinks that the class it is recreating it a list. Once the extend method is called, it switches back to TaggedList with all its attributes. This is weird behavior.
One way to solve this is to change the extend function like this
```py
  def extend(self, iterable):
      """ Extend the list with an iterable object.

      :param iterable: iterable object
      """
      if isinstance(iterable, TaggedList):
          itertags = iterable.itertags()
      else:
          itertags = [None, ] * len(iterable)

      for tag, item in zip(itertags, iterable):
          if tag is None and not hasattr(self, '_TaggedList__tags'):
            # Fringe case
            super(TaggedList, self).append(item)
          else:
            self.append(item, tag=tag)

 ```

**Comment by puneetsl** [comment]
I think here is where it tries to call extend https://github.com/python/cpython/blob/75751f4aa5d70f65856645a9128fd42d92d6692c/Lib/pickle.py#L1668

I'll file a bug in python

**Comment by puneetsl** [comment]
Found an already filed bug: https://github.com/python/cpython/issues/88112
and fortunately less ugly solution is to add this to the class
```py
  def __reduce__(self):
    return super(TaggedList, self).__reduce__()
```

**Comment by lgautier** [comment]
Thanks. This can be argued to be a documentation issue then.

That last fix seems way better. Do you want to update your PR accordingly?
