### ISSUE TITLE
FutureWarning raised by pandas2ri.py

### ISSUE THREAD

**Issue by hermanzhaozzzz** [rpy2/rpy2#953]
in jupyterlab

a cell
-------------------------
%%R -i df_pois
df_pois <- as.data.frame(df_pois)
# head(df_pois, 5)
-------------------------
# raise this:
..../lib/python3.10/site-packages/rpy2/robjects/pandas2ri.py:54: 
FutureWarning: iteritems is deprecated and will be removed in a future version. 
Use .items instead.
  def py2rpy_pandasdataframe(obj):

-------------------------
please have a try to fix it. I think it's a small case. Thanks!

**Comment by tikuma-lsuhsc** [comment]
This has already been addressed by PR #946
