### ISSUE TITLE
Issue with R Parallelism in rpy2 calls

### ISSUE THREAD

**Issue by lukeaanderso** [rpy2/rpy2#961]
**Describe the issue or bug**

I'm having intermittent hanging issues with rpy2 making mclapply calls. It appears that R is hanging somewhere between forking the new process, and its execution. I've written a fairly pared down example below. I've reproduced this in EC2 and on my local machines.

**To Reproduce**

Starting with the below code. I've written some basic R that makes a data.frame, calls mclapply to do some trivial work, print the forked PID, then print Done when complete.

```
import rpy2.robjects as robjects

_ = robjects.r("print('foo');")

parcmd = '''
tbl <- data.frame(a=letters, b=LETTERS);
parallel::mclapply(1:10, function(i) {
foo <- 3; print(Sys.getpid())},
mc.cores=5, mc.preschedule=FALSE);
print('Done');
'''
```

The base output looks something like
```

In [4]: _ = robjects.r(parcmd)
   ...:
[1] 9529
[1] 9530
[1] 9531
[1][1] 9534
[1] 9535
 9532
[1] 9533
[1] 9536
[1] 9537
[1] 9538
[1] "Done"
```

When called in a loop, it generally works ok
```
for i in range(1, 100):
  _ = robjects.r(parcmd)
```

However, when called sequentially, my probability of getting the hang is much higher

```
_ = robjects.r(parcmd)
_ = robjects.r(parcmd)
_ = robjects.r(parcmd)
... etc
```
And the output is something like, where the interpreter (Ipython in this case), is just waiting
```
In [5]: _ = robjects.r(parcmd)
   ...:
[1][1] 9546
 9547
[1] 9551
[1] 9552
[1] 9553
[1] 9554
[1] 9555
```

Because, the PIDs are printing but not the 'Done' message, it appears hung within the mclapply call. Based on the PIDs, I can guess which PID is hung, and see it sleeping. From the above, the highest PID was 9547 so checking 9548
```
[ec2-user@ip-172-31-79-19 ~]$  ps -Flww -p  9548
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
1 S ec2-user  9548  7726  0  80   0 - 153895 -     99520   0 20:12 pts/1    00:00:03 /usr/bin/python3 /home/ec2-user/.local/bin/ipython
```

Versions I'm using are below 
```
[ec2-user@ip-172-31-79-19 ~]$ ipython
Python 3.7.10 (default, Jun  3 2021, 00:02:01)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

[ec2-user@ip-172-31-79-19 ~]$ R --version
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-koji-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.


In [8]: rpy2.__version__
Out[8]: '3.5.6'
```
**Expected behavior**

I expect mclapply to consistently spawn and collect children processes when called from rpy2.

**Additional context**

From what I've read and seen similar issues, this is probably related to shared memory, and the python interpreter and the spawned PID being blocked by some sort of mutex. For the purposes of making this ticket I spun up an EC2 instance to grab this data. It didn't seem to happen on single core machines (probably because R wasn't actually forking then). This is the full output from the ec2 instance 

![image](https://user-images.githubusercontent.com/5738190/205381671-fd999c3c-0d5c-49ab-a649-d63a38dcbe40.png)
And the machine info

![image](https://user-images.githubusercontent.com/5738190/205381756-a2cf82f4-14b2-4de9-a847-0e665ed1e835.png)

My local machine is a slightly different OS (Centos) but has a similar issue. The ps on the sleeping PID on my machine seems to indicate its waiting on a futex
```
ps -Flww -p 188472
F S UID         PID   PPID  C PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
1 S landers+ 188472 165315  0  84   4 - 348249 futex_ 96336 99 16:20 pts/27   00:00:00 /srv/walleye/local/anaconda3/bin/python /srv/walleye/local/bin/ipython
```

I fully understand this is crappy bug to reproduce so trying to include as much detail as possible, apologies for all the data and thank you in advance for any and all help.
```
python -m rpy2.situation

[ec2-user@ip-172-31-79-19 ~]$ python3 -m rpy2.situation
rpy2 version:
3.5.6
Python version:
3.7.10 (default, Jun  3 2021, 00:02:01)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /usr/lib64/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/usr/lib64/R/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/lib/jvm/jre/lib/server:/usr/java/packages/lib/amd64:/lib:/usr/lib
R version:
    In the PATH: R version 4.0.2 (2020-06-22) -- "Taking Off Again"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/include/R']
  libraries:
  ['R', 'tre', 'pcre2-8', 'lzma', 'bz2', 'z', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib64/R/lib']
  extra_compile_args:
  []
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-z,relro']
```

**Comment by lgautier** [comment]
> When called in a loop, it generally works ok
> 
> ```python
> for i in range(1, 100):
>   _ = robjects.r(parcmd)
> ```
> 
> However, when called sequentially, my probability of getting the hang is much higher
> 
> ```python
> _ = robjects.r(parcmd)
> _ = robjects.r(parcmd)
> _ = robjects.r(parcmd)
> # ... e
> ```

Both code clock should be functionally identical. The second version is unrolling the for loop (why do so in Python and while the cost of calling `robjects.r()` is far more expensive than Python's management of the loop.

My only guess is that there is a race condition around a global used by R / `mcapply` and garbage collection. Remember that a few things in the R C-API is not re-entrant, and `cffi` used to interface with R's C API frees Python's GIL.

Try adding the following at the end your loop or between your unrolled calls:

```python
del(_)
# optionally also add:
# import gc; gc.collect()
```

If this does not solve it might be an issue upstream with `mcapply`: https://github.com/HenrikBengtsson/Wishlist-for-R/issues/94

**Comment by lukeaanderso** [comment]
Hi,

Thanks for your response. I agree with the loop unrolling, was just doing both because the unrolled loop seems to have a higher probability of issues (similar in that this happens with a normal Python interpreter but less often than IPython). Your notes on cffi are helpful. I'll keep digging and post if I get anywhere but it does seem like some intersection of garbage collection and the GIL. I can confirm adding extra GC's doesn't seem to help the issue. Thanks again for looking.

Luke

**Comment by lgautier** [comment]
I wish `cffi` had an option to not release the GIL. This was brought up on the cffi list but at the time this was ruled by the authors.

`rpy2` has an `rlock` but this should only help if multithreading is involved:
https://rpy2.github.io/doc/v3.5.x/html/rinterface.html#multithreading

**Comment by alonme** [comment]
Any news regarding this issue? 
I am encountering something very similar

**Comment by alonme** [comment]
Also - I tried to disable the python GC, but it had no effect.

When trying to trace the stuck process i see the following running over and over again (MacOS)

```
gettimeofday(0x7FF7B87745A8, 0x0, 0x0)		 = 0 0
psynch_cvwait(0x107A18218, 0x519A0100519B00, 0x18900)		 = -1 316
```

**Comment by lgautier** [comment]
R in is embedded in Python,
through rpy2. The R man page for `parallel:mclapply` has a warning about this situation (see below).
My understanding is that either a fix is managed upstream (in R, or the
R package `parallel`), or a non-fork alternative is used through `makeCluster` and `clusterApply`.

```
Warning:

     It is _strongly discouraged_ to use these functions in GUI or
     embedded environments, because it leads to several processes
     sharing the same GUI which will likely cause chaos (and possibly
     crashes).  Child processes should never use on-screen graphics
     devices.

(...)

     It is _strongly discouraged_ to use these functions with
     multi-threaded libraries or packages (see ‘mcfork’ for more
     details).  If in doubt, it is safer to use a non-FORK cluster (see
     ‘makeCluster’, ‘clusterApply’).
```

**Comment by lgautier** [comment]
The last comment suggests a documented limitation in R's `parallel::mcapply`. rpy2 cannot do much about this.
