### ISSUE TITLE
Conversion error when rpy2 is used in a thread

### ISSUE THREAD

**Issue by DE0CH** [rpy2/rpy2#965]
**Describe the issue or bug**

The automatic conversion from python types to r types fail when it is called in a thread. It works normally if the function is called, but if the function is called with python `multithreading.Thread`, the conversion just fails. 

**To Reproduce**

```
from threading import Thread
from rpy2.robjects import r

def fail():
    Thread(target=stuff).start()

def success():
    stuff()
    print("It worked nomally.")

def stuff():
    f = r('f <- function(s) {s}')
    f('abc')

if __name__ == '__main__':
    success()
    fail()
```

**Expected behavior**
Both the `fail` and `success` function should work without error.

**Error**
```
It worked nomally.
Exception in thread Thread-1 (stuff):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chend/iracepy/test.py", line 12, in stuff
    f = r('f <- function(s) {s}')
  File "/home/chend/.local/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 459, in __call__
    res = self.eval(p)
  File "/home/chend/.local/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 434, in __getattribute__
    return self.__getitem__(attr)
  File "/home/chend/.local/lib/python3.10/site-packages/rpy2/robjects/__init__.py", line 440, in __getitem__
    res = conversion.get_conversion().rpy2py(res)
  File "/usr/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/chend/.local/lib/python3.10/site-packages/rpy2/robjects/conversion.py", line 252, in _rpy2py
    raise NotImplementedError(
NotImplementedError: Conversion 'rpy2py' not defined for objects of type '<class 'rpy2.rinterface.SexpClosure'>'
```

**Additional context**

The output of running `python -m rpy2.situation`:
```
rpy2 version:
3.5.6
Python version:
3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
Looking for R's HOME:
    Environment variable R_HOME: None
    Calling `R RHOME`: /usr/lib64/R
    Environment variable R_LIBS_USER: None
R's additions to LD_LIBRARY_PATH:
/usr/lib64/R/lib:/usr/lib/jvm/java-19-openjdk/lib/server
R version:
    In the PATH: R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:
  include:
  ['/usr/include/R/']
  libraries:
  ['R', 'pcre2-8', 'lzma', 'bz2', 'z', 'tirpc', 'rt', 'dl', 'm', 'icuuc', 'icui18n']
  library_dirs:
  ['/usr/lib64/R/lib']
  extra_compile_args:
  []
  extra_link_args:
  ['-Wl,--export-dynamic', '-fopenmp', '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now', '-flto=auto']
```

**Comment by lgautier** [comment]
The conversion rules are stored in a Python `ContextVar`: https://github.com/rpy2/rpy2/blob/master/rpy2/robjects/conversion.py#L354

Special care is needed when using multithreading. See for example:
https://stackoverflow.com/questions/71511061/python-copy-context-contextvars-context-to-a-separate-thread

**Comment by DE0CH** [comment]
Why is it storing them in a Python `ContextVar`?

**Comment by lgautier** [comment]
Because rules can be context-sensitive (see the context manager `rpy2.robjects.conversion.localconverter`). A `ContextVar` leverages what Python has for this.

**Comment by DE0CH** [comment]
I see. Is there a way to set the default converter when a user creates a new thread? I think having to ask them to manage context var when they create a new thread can be a bit confusing. 

Or alternatively, in the error of `rpy2.objects.conversion._py2rpy`, we can have the error write about the context var and link to relevant documentation?

**Comment by lgautier** [comment]
> I see. Is there a way to set the default converter when a user creates a new thread? I think having to ask them to manage context var when they create a new thread can be a bit confusing.

My understanding is that this is up to the developer creating threads. The context can be fetched with `contextvars.copy_context()` and passed to the thread / thread executor.

> Or alternatively, in the error of `rpy2.objects.conversion._py2rpy`, we can have the error write about the context var and link to relevant documentation?

The current default for the `ContextVar` is an empty set of rules (no conversion). I am discovering that `ContextVar` is breaking existing assumptions about multithreading in Python (e.g., `ipykernel` was only fixed relatively recently, and Google's Colab is still broken).  I agree that it would make sense to have a default converter that raises an error message. `rpy2` is otherwise defining its default here: https://github.com/rpy2/rpy2/blob/master/rpy2/robjects/__init__.py#L80

**Comment by lgautier** [comment]
@DE0CH - Does the proposed error message here look informative enough to point a development to the right direction?
https://github.com/rpy2/rpy2/pull/966

**Comment by DE0CH** [comment]
Thanks for the explanation. And thanks for creating the PR. Really appreciate it.

I am developing a library to wrap a R package (irace) so that users can use it like a normal python module. My goal is to make the process as transparent as possible, so ideally they should be able to create threads and find it still working as expected without having to deal with `rpy2`. 

I've solved the problem by using `localconverter` everywhere so that it should work.

Out of curiosity, what existing assumptions does `ContextVar` break? Do you have the link to the relevant issue in `ipykernel` Google's Colab?

**Comment by lgautier** [comment]
> Thanks for the explanation. And thanks for creating the PR. Really appreciate it.
> 
> I am developing a library to wrap a R package (irace) so that users can use it like a normal python module. My goal is to make the process as transparent as possible, so ideally they should be able to create threads and find it still working as expected without having to deal with `rpy2`.

`rpy2` is a Python module. Whether a normal one is in the eye of the beholder.
R itself is unable to manage multi-threading, and `cffi` is releasing the GIL. You can consider writing wrappers for multi-threading but that won't prevent a user decide to use multi-threading in Python's standard lib.

> I've solved the problem by using `localconverter` everywhere so that it should work.

I do not know enough about what you are building, but note that users may use their own localconverter (this is the recommended way to customized conversion rules).

> Out of curiosity, what existing assumptions does `ContextVar` break? Do you have the link to the relevant issue in `ipykernel` Google's Colab?

https://github.com/googlecolab/colabtools/issues/3212
