### ISSUE TITLE
Rpy2 doesn't recognize import "rpy2.robjects" out a function

### ISSUE THREAD

**Issue by iBuitron** [rpy2/rpy2#975]
Hi! 
I'm making an app whith Plotly-Dash and some code whit R (rpy2)

When i test my code in notebook(ipynb) or and standalone .py it works, but when i embed the code in my main app (Dash) it doesn't works.

just a single test:

```
import rpy2.robjects as robjects  #!import out the function

def code_test():
    r_test = robjects.r(
    """
    print(pi)
    """
    )
```

**`on an standalone .py file or .ipynb it works perfectly`** 
```output: [1] 3.141593```

**`but when i embed this code into a Plotly-Dash app i get:`** 

> NotImplementedError:   Conversion rules for `rpy2.robjects` appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.

Solution: move the import into the function.

```
def test_r():
    import rpy2.robjects as robjects   #!import inside the function
    r_test = robjects.r(
    """
    print(pi)
    """
    )
```
```output: [1] 3.141593```

i don't know if i doing something wrong, 
but i have 2 functions with rpy2 in a module and when i call those it works.
![image](https://user-images.githubusercontent.com/102157308/212351234-43d2c78a-8a7e-432c-b704-33f3feebf6d8.png)

**Comment by iBuitron** [comment]
Solved: 

Adding "with default_converter" into the function [https://rpy2.github.io/doc/latest/html/robjects_convert.html](url)
it works perfectly (new feature in 3.5.7)

**Comment by lgautier** [comment]
Python's standard lib `contextvars` seems to be break a few 3rd-party packages using threading, or multi-processing
(#965 or #985 for example).

Adding a local converted can indeed be a workaround, with the understanding that conversion rules are then fixed in that code block.
