### ISSUE TITLE
Issue with rpy2 and contextvars.ContextVar when multithreading in Apache Flink

### ISSUE THREAD

**Issue by ncuriale** [rpy2/rpy2#985]
**Describe the issue or bug**

I am trying to use Apache Flink but process the incoming data stream with an R function - can't seem to figure out how to solve this error. 

`
NotImplementedError: 
    Conversion rules for 'rpy2.robjects' appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.
`

I have seen other similar threads like these:
https://github.com/rpy2/rpy2/issues/729
https://github.com/rpy2/rpy2/issues/965

Also the recent rpy2 change notes here:
https://rpy2.github.io/doc/latest/html/changes.html

But it's not really clear to me what I am supposed to add to this to make this work ... Something to do with using rlock or localconverter? Any help or advice here?

**To Reproduce**

`from pyflink.common import Types, Configuration`
`from pyflink.datastream import StreamExecutionEnvironment`

`PYTHON_PATH = "/usr/bin/python3.7"`
`config = Configuration()`
`config.set_string("python.client.executable", PYTHON_PATH)`
`env = StreamExecutionEnvironment.get_execution_environment(config)`
`env.set_python_executable(PYTHON_PATH)`

`data_stream = env.from_collection(`
`    collection=[`
`        (1, '{"name": "Flink"}'),`
`        (2, '{"name": "hello"}'),`
`        (3, '{"name": "world"}'),`
`        (4, '{"name": "PyFlink"}')`
`    ],`
`    type_info=Types.ROW_NAMED(["id", "info"], [Types.INT(), Types.STRING()])`
`)`

`def py_map(data):`
`    return 1`

`import rpy2.robjects as robjects`
`robjects.r('''`
`    map = function() return(1L)`
`''')`
`r_map = robjects.globalenv['map']`

`mapped_stream = data_stream.map(r_map, output_type=Types.INT())`
`#mapped_stream = data_stream.map(py_map, output_type=Types.INT())    <<<<<< USING THIS WORKS`

`mapped_stream.print()`

`env.execute()`

**Expected behavior**
Should work fine - here is a copy of the terminal output when run with the `py_map` object as the function

Warning message:
package ‘methods’ was built under R version 4.2.2 
Loading required namespace: curl
During startup - Warning messages:
1: package ‘datasets’ was built under R version 4.2.2 
2: package ‘utils’ was built under R version 4.2.2 
3: package ‘grDevices’ was built under R version 4.2.2 
4: package ‘graphics’ was built under R version 4.2.2 
5: package ‘stats’ was built under R version 4.2.2 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.flink.api.java.ClosureCleaner (file:/home/nathanc/.local/lib/python3.7/site-packages/pyflink/lib/flink-dist-1.16.0.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.apache.flink.api.java.ClosureCleaner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
8> 1
7> 1
5> 1
6> 1

**Error**
`
NotImplementedError: 
    Conversion rules for 'rpy2.robjects' appear to be missing. Those
    rules are in a Python contextvars.ContextVar. This could be caused
    by multithreading code not passing context to the thread.
`

**Comment by lgautier** [comment]
The warning messages suggest that there is an additional issue with your environment where R picks up standard libraries from a different version of R.

This is not necessarily an rpy2 bug.

**Comment by lgautier** [comment]
Preserving the context is either something that Apache Fink should do automatically, or allow to pass the context in which the `map()` method should evaluate the tasks. The latter is the most likely. I am not familiar enough with Fink so you'll have to look up it documentation.

A quick workaround can be explicitly set conversion rules local to the code block. This is looks like below:
 
```python
from pyflink.common import Types, Configuration
from pyflink.datastream import StreamExecutionEnvironment
import sys
import rpy2.robjects as robjects

PYTHON_PATH = sys.executable
config = Configuration()
config.set_string("python.client.executable", PYTHON_PATH)
env = StreamExecutionEnvironment.get_execution_environment(config)
env.set_python_executable(PYTHON_PATH)

data_stream = env.from_collection(
    collection=[
        (1, '{"name": "Flink"}'),
        (2, '{"name": "hello"}'),
        (3, '{"name": "world"}'),
        (4, '{"name": "PyFlink"}')
    ],
    type_info=Types.ROW_NAMED(["id", "info"], [Types.INT(), Types.STRING()])
)


robjects.globalenv['map'] = robjects.r('''
    function(data) return(1L)
''')

def r_map(data):
    with robjects.default_converter:
        return robjects.globalenv['map'](data)


mapped_stream = data_stream.map(r_map, output_type=Types.INT())

mapped_stream.print()
env.execute()
```

However, it will now fail because rpy2 does not know about Fink's `Row` objects and how to convert them to R objects.

```
    raise NotImplementedError(
NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'pyflink.common.types.Row'>'
```
